### ISSUE TITLE
A recuperação de gid dos usuários está inconsistente

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#105]
A solução vai ser implementar um endpoint, aberto, na api da ej, que vai receber o mtc_id e o _ga. Esse endpoint fica responsável por atualizar o contato no mautic

Como mecanismo de segurança, validar que a requisição vem do site da campanha. No primeiro momento essa validação será implementada na infra.

Num segundo momento, esse tipo de configuração será rotinizado via painel de configuração da conversa na EJ (issue #106)

**Comment by davidCarlos** [comment]
Fix feito em produção. A nova tag, para envio do _ga do analytics para o mautic, é a seguinte:

```
  mt('send', 'pageview');

	function getCookie(cookieName) {
		var cookies = document.cookie;
		var cookieIndex = cookies.indexOf(cookieName);
		var cookieValue = '';
		if (cookieIndex != -1) {
			var cookieKeyAndValue = cookies.substring(cookieIndex, cookies.length);
			cookieValue = cookieKeyAndValue.split("=")[1];
			if (cookieValue.indexOf(";") != -1) {
				cookieValue = cookieValue.split(";")[0];
			}
		}
		return cookieValue;
	}
    setTimeout(function() {
	var mtc_id = getCookie("mtc_id");
	var _ga = getCookie("_ga");
	var ej_host = "https://ejplatform.org";
	    fetch(`${ej_host}/mautic/contacts/?mtc_id=${mtc_id}&_ga=${_ga}`)
		    .then(res => {
			    console.log(res)
		    })
    }, 6000);

**Comment by davidCarlos** [comment]
Fix feito em produção. A nova tag, para envio do _ga do analytics para o mautic, é a seguinte:

```
  mt('send', 'pageview');

	function getCookie(cookieName) {
		var cookies = document.cookie;
		var cookieIndex = cookies.indexOf(cookieName);
		var cookieValue = '';
		if (cookieIndex != -1) {
			var cookieKeyAndValue = cookies.substring(cookieIndex, cookies.length);
			cookieValue = cookieKeyAndValue.split("=")[1];
			if (cookieValue.indexOf(";") != -1) {
				cookieValue = cookieValue.split(";")[0];
			}
		}
		return cookieValue;
	}
    setTimeout(function() {
	var mtc_id = getCookie("mtc_id");
	var _ga = getCookie("_ga");
	var ej_host = "https://ejplatform.org";
	    fetch(`${ej_host}/mautic/contacts/?mtc_id=${mtc_id}&_ga=${_ga}`)
		    .then(res => {
			    console.log(res)
		    })
    }, 6000);
``` 
O bug ocorre porquê o script `mt`, do mautic, não é capaz de atualizar o gid de contatos já existentes. Para contornar essa situação, implementamos um endpoint na EJ (`/mautic/contacts/`), que recebe o mtc_id e o _ga via parâmetros na url, e atualiza o respectivo contato no mautic.
