### ISSUE TITLE
Complementações no relatório dos notebooks do jupyter

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#117]
- [x] [Análise apenas EJ] número de usuários com pelo menos 1 voto no período de 17 a 23/abril
- [x] [Análise apenas EJ] número de usuários criados no período de 17 a 23/abril e, desse conjunto, quantos nunca tinham votado antes (i.e. novas aquisições qualificadas com voto)

- [x] [Análise apenas EJ] número de usuários criados no período de 24 a 26/abril
- [x] [Análise apenas EJ] número de usuários com pelo menos 1 voto no período de 24 a 26/abril e, desse conjunto, quantos nunca tinham votado antes (i.e. novas aquisições qualificadas com voto)

- [x] [Análise apenas EJ] número de usuários criados no período de 27/abril a 14/maio
- [x] [Análise apenas EJ] número de usuários com pelo menos 1 voto no período de 27/abril a 14/maio e, desse conjunto, quantos nunca tinham votado antes (i.e. novas aquisições qualificadas com voto)

- [x] [Análise apenas EJ] número de usuários criados no período de 28/abril a 1/maio
- [x] [Análise apenas EJ] número de usuários com pelo menos 1 voto no período de 28/abril a 1/maio e, desse conjunto, quantos nunca tinham votado antes (i.e. novas aquisições qualificadas com voto)

- [x] [Análise apenas EJ] número de usuários criados no período de 28/abril a 14/maio
- [x] [Análise apenas EJ] número de usuários com pelo menos 1 voto no período de 28/abril a 14/maio e, desse conjunto, quantos nunca tinham votado antes (i.e. novas aquisições qualificadas com voto)

- [x] [Análise apenas EJ] número de usuários criados no período de 08/maio a 14/maio
- [x] [Análise apenas EJ] número de usuários com pelo menos 1 voto no período de 08/maio a 14/maio e, desse conjunto, quantos nunca tinham votado antes (i.e. novas aquisições qualificadas com voto)

- [x] Padronizar o texto do número de usuários que nunca tinham votado antes: "_Desse conjunto de usuários acima, quantos nunca tinham votado antes_". Aí a lógica seria de contar os usuários sem votos anteriores ao período em questão.

- [x] Manter a análise dos 10 mais votantes, porém ampliar pra 50

- [x] Voltar pro relatório a análise dos mais votantes, considerando apenas aqueles com email válido no mautic, e ampliar pra 50

**Comment by davidCarlos** [comment]
Relatorio atualizado: [osf (10).pdf](https://github.com/cidadedemocratica/ej-server/files/4658135/osf.10.pdf)

**Comment by ricardopoppi** [comment]
@davidCarlos estou analisando os outros dados mas já te passou um primeiro feedback: também nos dados cruzados, expandir a lista de top usuários votantes pra 50, tanto pra lista atual só com emails válidos quando criando uma nova lista com qq email

**Comment by ricardopoppi** [comment]
@davidCarlos  analisei os dados exportados e fiz um exercício bem exaustivo de como compor o relatório considerando o valor de aquisições qualificadas de já convertidos. Se vc olhar nos slides 4 a 10 da apresentação do relatório 1 eu demonstro lá onde cada dado desse será utilizado.

Cheguei a conclusão que para produzir o relatório 1 com a aquisição qualificada das conversões, vamos precisar necessariamente dessas complementações:

**AJUSTES PARA COMPOR O PRIMEIRO RELATÓRIO**

- [ ] Cruzar a lista de top votantes do EJ (item 1.1.7) com o email do usuário no mautic utilizando a info do mtc_id como chave. Expandir a lista para contemplar todos os usuários da conversa (no último report, 146 usuários);
ALTERNATIVA COM PERDAS:  Criar uma nova lista cruzada por gid composta por usuários com qualquer valor no campo de email;
PARA IDENTIFICAR CONVERSÕES APOS USO DA EJ: Incluir na lista de top votantes com email mautic a informação de criação do usuário na EJ e no mautic, para identificar aqueles usuários cuja data de criação no EJ seja anterior a data de criação do contato no mautic;
PARA IDENTIFICAR COMENTADORES: Incluir na lista de top votantes a informação do número de comentários de autoria do usuário que foram aprovados, rejeitados ou estão em moderação;

- [ ] Expandir a lista cruzada por gid de top votantes (item 1.2.2) pra 50, mantendo a abordagem atual de só listar usuários com emails válidos;

- [ ] Listar o email mautic e a quantidade de votos por usuário dos 22 usuários identificados no ítem 1.1.1 usando a info do mtc_id como chave;

- [ ] Listar o email mautic e a quantidade de votos por usuário dos 18 usuários identificados no ítem 1.1.2 usando a info do mtc_id como chave;

- [ ] Listar o email mautic e número de votos dos 35 usuários detectados no ítem 1.2.6 marcando os que tem email válido;

- [ ] Listar o email mautic e número de votos do único usuário detectados no ítem 1.2.9;


**AJUSTES MENOS PRIORITÁRIOS**

- [ ] Corrigir o texto da data no ítem 1.1.4 (abril com maio invertido no algoritmo e no texto);
- [ ] Gerar uma lista de top comentadores listando email mautic deles;
