### ISSUE TITLE
Plano de teste da nova versão do compoente e sonda

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#129]
NOVA VERSÃO DA SONDA

- [x] Analytics e mautic configurados na pagina, mas componente autenticando via gid (setar componente pro método analytics, usar página da ucc com conversa de teste)
- [x] Analytics configurado na página (sem mautic), mas componente autenticado via gid (desativar tracking do mautic e setar componente pro método analytics, usar página de teste votorantim)
- [x] Analytics e mautic configurados na pagina, mas componente autenticando via mtc_id (comportamento na versão atualmente em produção, usar página da ucc com conversa de teste)
- [x] Teste geral com a sonda de email, tema osf/ucc na nova versão do componente (autenticação via mautic, direcionar para página de teste ucc)
- [x] Teste com a sonda de email, tema osf/ucc, usando códigos UTM no link enviado via mautic (autenticação via mautic, direcionar para página de teste ucc)
- [x] Teste com a sonda de email, tema votorantim, usando o teste A/B do mautic alterando o comentário destacado no envio (autenticação via mautic, direcionar para página de teste agentesdacidadania com a tag do mautic ativada) - testar monitoramento de cliques
- [x] Teste com a sonda de email, tema osf/ucc na nova versão do componente (autenticação via gid, direcionar para página de teste ucc)
- [x] Teste com a sonda de email, tema osf/ucc, usando códigos UTM no link enviado via mautic (autenticação via gid, direcionar para página de teste ucc)

**Comment by ricardopoppi** [comment]
Teste 1: Analytics e mautic configurados na pagina, mas componente autenticando via gid (setar componente pro método analytics, usar página da ucc com conversa de teste)

Versão do componente setada pra "`1.7.0-beta`"
Conversa nova criada na EJ, zerada, com dois comentarios iniciais (`cid="60"`)
Conversa renderizada na url [/testeopiniao](https://unidoscontraacorrupcao.org.br/testeopiniao/) com método `authenticate-with="analytics"`
Página da coleta foi acessada por desktop e mobile, ambos fizeram um comentário cada e votaram em todos
Horário aproximado do teste: 21/06 - 18:30

**Comment by ricardopoppi** [comment]
**Teste 2**: Analytics configurado na página (sem mautic), mas componente autenticado via gid (desativar tracking do mautic e setar componente pro método analytics, usar página de teste votorantim)

Versão do componente setada pra "1.7.0-beta"
Conversa renderizada na url [/opiniaogid](https://agentesdacidadania.org.br/opiniaogid) apontado pra conversa com método authenticate-with="analytics"

**Comment by ricardopoppi** [comment]
**Teste 3**: Analytics e mautic configurados na pagina, mas componente autenticando via mtc_id (comportamento na versão atualmente em produção, usar página da ucc com conversa de teste)

Conversa renderizada na url [/testeopiniao](https://unidoscontraacorrupcao.org.br/testeopiniao/) apontado pra conversa teste `cid="60"` com método `authenticate-with="mautic"`
Usuário via desktop que já tinha acessado antes no modo analytics, acessou a mesma página no modo mautic, votou 3 vezes e fez um novo comentário
Usuário via desktop em aba anônima, votou em todas e fez um comentário
Usuario via mobile, em aba anônima, votou em todas e fez um comentário
_Horário aproximado do teste_: 21/06 - 21hs

**Comment by ricardopoppi** [comment]
*Teste 4*: Voto via sonda, direcionado pra dominio customizado /testeopiniao na página UCC com mautic e analytics rodando na página e auth definida via mautic
Conversa: `cid="62"`
Usuário via desktop em aba anônima, votou em todas e fez um comentário
Usuario via mobile, em aba anônima, votou em todas e fez um comentário
Horário aproximado do teste: 29/06 - 14h20

Bugs identificados:

- Cookie do mautic aparentemente não carregou o que levou o componente a exigir o registro
- O voto que veio da sonda na URL não foi feito

**Comment by ricardopoppi** [comment]
**Teste 5**: Sonda com códigos UTM no link autenticação via mautic

Funcionou igualzinho, os UTM não interferiram
_Horário aproximado do teste: 18:13_

**Comment by ricardopoppi** [comment]
**Teste 6**: Foi testado apenas o teste A/B do mautic para avaliar o monitoramento de cliques, monitorou direitinho

**Comment by ricardopoppi** [comment]
**Teste 7**: Página do agentes e da ucc, ambas com método analytics
Correu tudo bem, apenas o problema de registrar os votos que se repetiu
_Horário aproximado dos testes: entre 18h40 a 19h10_

Bugs identificados:

- Assim como nos testes anteriores, os votos vindos pela sonda não foram computados

**Comment by ricardopoppi** [comment]
**Teste 8**: Igual ao anterior só que com UTM

Correu tudo bem, apenas o problema de registrar os votos que se repetiu
Horário aproximado dos testes: 29/06 - 19h20

Bugs identificados:

Assim como nos testes anteriores, os votos vindos pela sonda não foram computados

**Comment by ricardopoppi** [comment]
**CONSOLIDANDO O RESULTADO DOS TESTES**

- Voto que vem da sonda não é registrado no componente:
-- Seja no modo analytics pelo [link do mautic](https://mautic.pencillabs.com.br/r/b2e9e77ac936ff2cbad14e7fa?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo1OiJlbWFpbCI7aToxO2k6NDA7fXM6NToiZW1haWwiO2k6NDA7czo0OiJzdGF0IjtzOjIyOiI1ZWZhNjllY2NlOWFhNTQyMzQ3MzAyIjtzOjQ6ImxlYWQiO3M6NDoiOTU1MSI7czo3OiJjaGFubmVsIjthOjE6e3M6NToiZW1haWwiO2k6NDA7fX0%3D&), seja pelo link direto, [com UTM](https://agentesdacidadania.org.br/opiniaogid/?cid=62&comment_id=855&choice=disagree&utm_medium=fase3&utm_campaign=emailsondapolemicajunho) ou [sem UTM](https://agentesdacidadania.org.br/opiniaogid/?cid=62&comment_id=855)

**Comment by davidCarlos** [comment]
Fechando essa issue. Mover os bugs encontrados para uma nova issue, marcar como `bug` e `webcomponent e me assinar.
