### ISSUE TITLE
Informar a url destination

### ISSUE THREAD

**Issue by MarthaDs** [cidadedemocratica/ej-server#147]
- [ ] Informar a url destination a que os dados se referem (gráficos 1 e 2) - no futuro isso pode virar um campo aberto ou dropdown pro usuário do dash selecionar a url, mas por agora pode ser apenas informativo

**Comment by davidCarlos** [comment]
Atualmente, os dados do analytics são requisitados pelo cliente passando o argumento `ga:pagePath==/opiniao/`. (**src/dashboard/services/analytics.py**). A ideia é esse argumento seja um atributo do serviço, e possa ser acessado pelo componente.
