### ISSUE TITLE
Erros ao carregar o primeiro e segundo gráfico do dashboard

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#156]
Ao alterar os parametros dos primeiros dois gráficos (datas por exemplo) o dashboard apresenta erros. Reproduzo abaixo:

![Captura de tela de 2020-09-18 16-50-24](https://user-images.githubusercontent.com/1162183/93639363-4175b100-f9cf-11ea-90ea-f06897155d8b.png)

Errors (3)
⛑️
Callback failed: the server did not respond.
16:48:30
Callback failed: the server did not respond.
(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)
⛑️
Callback failed: the server did not respond.
16:47:50
Callback failed: the server did not respond.
(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)
⛑️
Callback failed: the server did not respond.
16:46:29
Callback failed: the server did not respond.
(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)

**Comment by davidCarlos** [comment]
Fiz uma correção no container do nginx e aparentemente o problema foi resolvido.
