### ISSUE TITLE
Inconsistencias no dashboard dos comentarios

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#157]
Comentários com inconsistencias:

Com a saída de Sérgio Moro do governo e o enfraquecimento da LAVA JATO estamos órfãos novamente. Nunca foi entre a esquerda é a direita, mas sempre entre os políticos corruptos e o povo.
No dash: 
93% de participacao no geral
92% de participacao no grupo prolavajato
Na EJ:
64% de participacao no geral
49% de participacao no grupo prolavajato

A imprensa é um lixo e engana o povo. Isso não é liberdade! Tem mais que proibir mídia mentirosa e manipuladora. O Presidente tá certo
No dash:
94% de participacao no geral
93% de participacao no grupo prolavajato
Na EJ:
63% de participacao no geral
48% de participacao no grupo prolavajato

**Comment by davidCarlos** [comment]
@MarthaDs @ricardopoppi essa inconsistência se dá porquê a gente tá somando o número de concordâncias e o número de discordâncias e usando isso como a % de participação. O que temos que fazer é utilizar o calculo que a própria EJ faz, ao invés de fazer essa conta de padaria atual  :smile: :smile: . Eu vou puxar essa issue.

**Comment by ricardopoppi** [comment]
Ahhh então é isso mesmo, a EJ considera os pulos também, ela entende que o pular é uma participação

**Comment by davidCarlos** [comment]
Exatamente.
