### ISSUE TITLE
Possível inconsistência nos graficos do dashboard

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#162]
- [ ] Gráfico Engajamento vs Aquisição (EJ): quebra no período referente a fase 2: 16/07 a 19/08. Esse período é anterior ao disparo do mailing e posterior a fase 1 onde houve algumas inconsistencias de analytics. Era esperado que os dados estivessem consistentes

![newplot (10)](https://user-images.githubusercontent.com/1162183/94690632-bc5f9580-0306-11eb-8c35-927cf7d0b45a.png)

- [ ] Aquisição Qualificada: provável inconsistência no período da fase 2 também (16/07 a 19/08) mas a mesma mediana (54) está retornando para outros períodos testados (mês de maio, mes de junho etc). 

Exportei os dados, separei apenas o período de 16/07 a 19/08 e calculei manualmente a mediana: 46

Gráfico referente ao mes de maio, por exemplo:

![newplot (11)](https://user-images.githubusercontent.com/1162183/94690663-c5506700-0306-11eb-9cd1-1012b684c9e6.png)

**Comment by davidCarlos** [comment]
Sobre o primeiro bug: Naõ consegui reproduzir. Colocando o período informado o dash me parece retornar corretamente o engajamento.
![image](https://user-images.githubusercontent.com/2847027/94704283-20d62100-0316-11eb-88fd-aac3a2d9090a.png)

**Comment by davidCarlos** [comment]
Sobre o primeiro bug: Naõ consegui reproduzir. Colocando o período informado o dash me parece retornar corretamente o engajamento.
![image](https://user-images.githubusercontent.com/2847027/94704283-20d62100-0316-11eb-88fd-aac3a2d9090a.png)

**Comment by ricardopoppi** [comment]
> Sobre o primeiro bug: Não consegui reproduzir. Colocando o período informado o dash me parece retornar corretamente o engajamento.

Testou em prod? Aca
