### ISSUE TITLE
Subir ambiente de produção para lançamento da versão 1.0 do dashboard

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#170]
- [ ] Implementar arquivos de stack para deploy em produção
- [ ] Implementar arquivo de configuração do nginx para o ambiente de produção
- [ ] Configuração do domínio de produção do dash
- [ ] Replicar o dash para a conversa do EJ Educacional
- [ ] Remover do CI da EJ o passo que clona o repositório. O próprio gitlab já clona o repositório a partir do commit que dispara a pipeline. O repositório é clonado dentro de `/builds/pencillabs/ej/ej-server/`
- [ ] Corrigir ambiente de homologação
- [ ] Visualização no primeiro gráfico não funcionou para o filtro `campanhadoparticipante`. Intervalo de data 01/10/2018 - 05/01/2021. Print nos comentários.

**Comment by MarthaDs** [comment]
>  Referente a task de visualização no primeiro gráfico com filtro de campanhadoparticipante.

![Screenshot from 2021-01-05 17-39-17](https://user-images.githubusercontent.com/12221656/103696542-4ad65980-4f7d-11eb-8340-8914843547ea.png)

**Comment by davidCarlos** [comment]
Fechando essa issue. Tudo que foi desenvolvido para o dashboard, será incorporado à EJ nas próximas sprints, pela frente de DataViz do projeto demo.eco.
