### ISSUE TITLE
Implementar testes de aceitação com selenium

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#174]
- [ ] Incluir no .gitlab-ci um step no pipeline para execução dos testes.

**Comment by davidCarlos** [comment]
https://dash.plotly.com/testing

**Comment by MarthaDs** [comment]
Encontrado no forum : [Exemplo de implementação de teste](https://community.plotly.com/t/automated-gui-testing/5445)

**Comment by davidCarlos** [comment]
Precisamos testar o comportamento das visualizações quando houver dados faltantes. Os componentes não podem quebrar, e precisam apresentar a mensagem "Não há dados para apresentar". Para fazer esse teste provavelmente vamos precisar tornar customizável o diretório de onde o Dash lê os arquivos json. Pelo que eu notei da nossa ultima reunião, estamos rodando os testes de aceitação utilizando os arquivos csv de produção/homologação, mas precisamos de uma base apenas para rodar os testes.

- O primeiro passo pra isso é tornar o path de onde o dash lê os arquivos customizável. De preferência lendo, de uma variável de ambiente, qual o diretório em que os arquivos csv estão. Hoje esse diretório está hardcoded nos serviços.
- Sendo customizável, podemos apontar o dash para um diretório vazio, garantindo que os componentes não terão dados para apresentar.
- Não tendo dados para apresentar, conseguimos testar se o dash irá apresentar a mensagem esperada.

**Comment by MarthaDs** [comment]
### Roteiro de Teste
#### Teste Page
- [ ] Testar Titulo da pagina
- [ ] Testar se na imagem da EJ parece na navbar
- [ ] Testar se o botão de reload existe e é clicável
- [ ] Testar se os panéis dos graficos existem e estão sendo mostrados

#### Teste Grafico 1 - Analytics
- [ ] Testar se o painel do gráfico possui titulo e se eles está correto
- [ ] Testar se filtros de DropDown existem, se são clicável e se existem opções de input
- [ ] Testar input dos filtros de DropDown
- [ ] Testar filtro calender existe, se eh possível escolher as datas
- [ ] Testar se opção de exportar existe, se o link para baixar aparece e é clicavel
- [ ] Testar se as "paginas analisas" existe
- [ ] Testar se a imagem dos dados é mostrada e quando não houver dados se existe uma mensagem informando

#### Teste Grafico 2 - Votes
- [ ] Testar se o painel do gráfico possui titulo e se eles está correto
- [ ] Testar se filtros de DropDown existem, se são clicável e se existem opções de input
- [ ] Testar input dos filtros de DropDown
- [ ] Testar se checkbox de emails validos existe e é clicável
- [ ] Testar filtro calender existe, se eh possível escolher as datas
- [ ] Testar se opção de exportar existe, se o link para baixar aparece e é clicavel
- [ ] Testar se a imagem dos dados é mostrada e quando não houver dados se existe uma mensagem informando

#### Teste Grafico 3 - Comments
- [ ] Testar se link da conversa existe e é clicável
- [ ] Testar se filtro de DropDown existem, se são clicável e se existem opções de input
- [ ] Testar input do filtro de DropDown
- [ ] Testar se input de participação existe, se funciona corretamente(espera enter do usuário)
- [ ] Testar se opção de exportar existe, se o link para baixar aparece e é clicavel
- [ ] Testar se a tabela dos dados é mostrada e quando não houver dados se existe uma mensagem informando

**Comment by MarthaDs** [comment]
Os testes serão feitos em outra issue pois necessitam de uma base de dados para funcionarem.
