### ISSUE TITLE
Subir novamente o mautic em um domínio EJ

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#181]
- [x] Restaurar dump do banco antigo
- [x] Alterar arquivos do nginx para novo domínio
- [x] Gerar certificados ssl

**Comment by ricardopoppi** [comment]
Domínio criado:

contatos.ejparticipe.org > 72.14.178.49

(usei o mesmo ip atual mas se precisar alterar só me falar que eu atualizo na zona dns)

**Comment by ricardopoppi** [comment]
@davidCarlos chamo atenção para essa issue, já que até podemos homologar em mautic de terceiros mas o experimento tem que ser feito no mautic com dominio EJ

**Comment by davidCarlos** [comment]
Essa história técnica está prevista para a próxima sprint, que começa segunda que vem.

**Comment by ricardopoppi** [comment]
perfeito

**Comment by davidCarlos** [comment]
https://contatos.ejparticipe.org/s/login
