### ISSUE TITLE
Implementar endpoint na EJ para expor resumo da conversa

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#188]
- 5 Comentários mais positivos
- 5 Comentários mais negativos

**Comment by ricardopoppi** [comment]
Nossa referência

![screenshot-www ejparticipe org-2020 12 04-19_17_08](https://user-images.githubusercontent.com/1162183/101220918-5aecd780-3665-11eb-928b-bdf4142ef144.png)

**Comment by davidCarlos** [comment]
issue movida para #190
