### ISSUE TITLE
Como participante da coleta, gostaria de visualizar um resumo da conversa no componente

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#190]
**Issues**
- [x] Implementar visualização por abas. Primeira aba deve ser o card para comentários, segunda aba deve ser card de resumo;
- [x] Implementar endpoint na EJ para expor resumo da conversa #188 
     - [x]  5 comentários mais positivos (por cluster)
     - [x] 5 comentários mais negativos (por cluster)
- [x] Apresentar mensagem que ainda não há informações sobre os grupos caso o número de votos seja inferior a 500;
- [x] Replicar UX da EJ na mudança de cluster
- [x] Apresentar comentários por cluster

**Comment by ricardopoppi** [comment]
Sugestão de UX:

Este resumo pode ser exibido sempre que o usuário clicar num ícone de informação (a exemplo do implementado no dashboard) ou automaticamente ao final da votação em todos os comentários

**Comment by ricardopoppi** [comment]
Nossa referência

![screenshot-www ejparticipe org-2020 12 04-19_17_08](https://user-images.githubusercontent.com/1162183/101220918-5aecd780-3665-11eb-928b-bdf4142ef144.png)

**Comment by ricardopoppi** [comment]
@davidCarlos me ocorreu uma questão de ux importante. Acredito que teríamos que ter uma forma da pessoa desabilitar essa exibição na tag script do componente, talvez via parametrização (como ocorre no caso do tema). Principalmente porque até um determinado momento esses resultados vão estar confusos (sem grupos), principalmente no inicio da coleta. Essa é uma questão né?

**Comment by davidCarlos** [comment]
Fazer via tag não é a melhor opção. O ideal é o componente prever que nem sempre esses dados estarão disponíveis e apresentar uma aviso que ainda não há dados suficientes para serem apresentados, quando for o caso.

**Comment by davidCarlos** [comment]
O que eu pensei, pra tela de informações não ficar vazia quando isso acontecer, é incluir aquelas informações de número total de votos, comentários e participantes. Caso haja dados clusterizados, apresentamos, caso não, informamos que ainda não há infos suficientes.

**Comment by ricardopoppi** [comment]
@davidCarlos minha preocupação ao propor a solução via tag (mesmo trazendo uma complexidade a mais pro gestor) é porque não temos hoje nenhum mecanismo que informe quando um cluster não está formado, já que a EJ exibe clusteres unitários quando você cria as personas. Então a tendência é sempre ter informação de cluster, mesmo quanto essa informação é fake e/ou ainda não foi devidamente processada. 

Me parece que depender dessa informação vinda da EJ pode ficar complexo, arriscado e com alta probabilidade de exibir informações incorretas para todos os participantes sem a gente ter muito controle disso. Meu ponto é só a prudência: sabendo que personas e clusteres tem um forte componente manual feito pela gestão da conversa, apostar numa exibição automática na parte mais sensível - que é o usuário na ponta - pode ser perigoso...

Faz sentido?

**Comment by davidCarlos** [comment]
Faz sentido sim. Concordo que apresentar dados ao usuário que podem não ser confiáveis deve ser evitado a todo custo. Inicialmente eu já não ia apresentar a visualização dos clusters no componente por questões técnicas. A primeira versão viria apenas com os top 5 comentários positivos e os top 5 comentários negativos (agrupados por cluster). Além de dados mais gerais como número de participantes, e etc. Mas refletindo aqui, eu acho que a visualização dos clusters pode entrar como parte da nossa estratégia de engajamento, e não como uma feature no componente. O que eu imagino então:

1. Nessa aba de informações teríamos sempre dados gerais da conversa. Incluíndo os top 5 comentários mais concordados (independente dos clusters) e os top 5 comentários mais discordados (independente dos clusters).
2. Na issue #179 podemos incluir a justificativa que, ele nos informando o email, podemos mandar um "relatório" apresentando os grupos consolidados ao final da coleta. Podemos apresentar uma imagem de exemplo de quais dados seriam esses. Isso seria uma motivação a mais para a pessoa nos informar, por exemplo, o seu email. Eu gostaria de saber em qual cluster eu fui "marcado". Isso evita que os usuários vejam clusters não confiáveis no componente, e abriria um canal de comunicação a partir do envio de um relatório com os grupos de opinião gerados ao final da coleta. Para esse item, teríamos que avaliar uma forma automática de gerar esse relatório e enviar para os participantes, mas eu acho uma feature muito interessante para fidelizar esse usuário que além de participar, ainda nos deu mais pontos de informação.

O que acha?

**Comment by ricardopoppi** [comment]
Gostei da abordagem do (1) pois aí sim sempre teríamos dados pra mostrar. Mesmo sem os clusters ainda, no início da coleta, vai haver um certo viés nos comentários gerais por conta do número baixo de participantes, mas pelo menos não vai ser um resultado "fake" como seria no caso dos clusters. Claro que sem a exibição do gráfico de clusteres esse resumo vai ficar mais "durão" mais baseado em texto, que perde um pouco a atratividade, mas entendo a complexidade de refazer esse dataviz no componente, parametrizar a biblioteca etc etc acredito que exija uma certa curva de aprendizado né?

Sobre o (2) acho que pode ser uma ótima estratégia de engajamento no fornecimento dos dados de contato! Uma troca de valor com o usuário né? Só não estou seguro se vale a pena fazer tudo isso no componente e na EJ, tendo a achar que não é um bom caminho pensando no futuro. Eu apostaria em fazer isso via mautic. Um estudo legal pra issue #179 aproveitando que ela não vai ser pra agora, seria ver a possibilidade do gestor conseguir incluir um focus (form) do mautic nesse lugar, algo mais complexo mas que me parece viável de ser trabalhado no roadmap do projetão.

Por que o mautic? Porque nesse formzinho de coleta de dados pessoais vamos ter que lidar com a questão dos consentimentos e também com a possibilidade do usuário colocar o telefone, aí o mautic já estaria mais preparado que a EJ pra enviar o relatório por email pra quem deu email e pelo conector de whatsapp pra quem deu fone. Essa automatização é nativa no mautic. Outro motivo é que contextos diferentes podem pedir coleta de dados diferentes, como genero, raça etc. E aí se for via mautic a customização do que coletar, mesmo que seguindo alguns parâmetros de quantidade de campos e estilo, seria toda via admin, empoderando o gestor.

**Comment by davidCarlos** [comment]
Eu acho que qualquer dado que a gente apresentar de cluster no componente pode ser um problema. Pela experiência nos já sabemos que os clusters nem sempre representam de fato a base, o que exige uma intervenção humana de remodelagem. Fora o fato de que mesmo com a modelagem correta, sem um número considerável de votos não dá pra confiar na visualização que a EJ gera. Então eu não vejo outra opção para aquela área de infos que não sejam os dados mais gerais da conversa mesmo.

Quanto ao mautic vamos precisar discutir isso melhor e avaliar a complexidade. Não digo nem pelo form, julgo que isso seria simples. O problema é a descentralização dos dados, uma vez que os dados dos clusters vão estar na EJ mas os dados do usuário vão estar no mautic. Isso traz uma complexidade que é: Como vamos fazer pra juntar os dados que foram informados via form, com os dados que a EJ clusterizou? Nós teríamos que ter um mecanismo para exportar um relatório por usuário (já que uma das infos que a EJ gera é em qual cluster o usuário se encontra), e importar isso no Mautic. O relatório seria uma replicação da tela de grupos de opinião na EJ, e ai ela é específica por usuário. Talvez um plugin que comunique EJ e mautic, mas será que vale o esforço? Será que uma simples modal no componente que já envie tudo pra EJ, e uma integração simples com mailgun apenas para enviar o relatório para essa base já não seria o suficiente pra validarmos essa feature?

Acho que pensar em soluções mais simples de começo permitem que a gente valide mais rápido o impacto a nível de negócio. Talvez em uma v2 dessa feature possamos integra-la com o mautic para gerar as campanhas automaticamente, por exemplo.

**Comment by ricardopoppi** [comment]
Maravilha, concordo que ainda precisamos aprofundar mais essa questão sobre a coleta dos dados de contatos e as automatizações e também com a diretriz de que a solução tem que ser a mais simples possível para validarmos. Perfeito. Só um ponto: de qq forma pra poder fazer qq tipo de comunicação segmentada pras campanhas vamos precisar recuperar a informação do cluster do usuário via airflow, cruzar e atualizar no mautic. Esse vai ser parte do roadmap do projetão por ser um requisito das campanhas e não necessariamente dessa feature especificamente. Mas legal que já construimos vários parametros aqui nessa conversa, deixemos o aprofundamento desse assunto pro planejamento de 2021.

Sobre a exibição, apesar de existir sempre esses ajustes dos clusters ao longo/final da conversa, exibir informações sobre os clusters me parece um requisito de transparência importante pra ferramenta. Das 3 coletas reais que fizemos esse ano de 2020, a primeira nenhum grupo funcionou (consulta agentes da cidadania). Na segunda (UCC) dois grupos funcionaram e dois grupos não (50%). E na terceira (agentes da cidadania), os dois grupos (100% nesse caso) funcionaram. Só pra gente ter o parametro, eu diria que é um indicador bom pra gente manter essa exibição, mesmo sabendo que ela vai se alterar ao longo da conversa. Se na sua avaliaco não é possível replicar o dataviz, acho importante manter a explicação inicial dos grupos de opinião e as abas dos clusters ao lado da aba geral, afinal esse é o caráter distintivo entre a EJ e uma simples enquete. Do ponto de vista comercial pra EJ essa distinção é importante.

**Comment by ricardopoppi** [comment]
Avançando na reflexão e nos encaminhamentos dessa issue, assumindo como premissa que um resumo de conversa da EJ precisa necessariamente falar de grupos, fica pendente a decisão sobre qual a melhor forma de controlar essa exibição: se vai ser uma tag disponível para o gestor ou algum dado que já esteja disponível na API da EJ (uma constante de número mínimo de participantes?)

**Comment by davidCarlos** [comment]
A exibição das informações relacionadas ao cluster podem ser liberadas a partir um número mínimo de votos. Se vai apresentar os grupos no componente, então a ideia de "enviar um relatório" para o usuário perde o sentido pra mim, já que ele já vai ter acesso à todas as infos pelo componente.

**Comment by davidCarlos** [comment]
A questão da transparência, pode ser alcançada de diferentes formas. Eu acho a ideia de algumas informações no componente, e outras sendo enviadas de forma direta para os usuários (via email), fortalece nossa estratégia de engajamento com o público que interage com a coleta. Ainda acho que apresentar tudo via componente, joga fora uma oportunidade de saber exatamente quem é esse usuário sem a necessidade de preencher um form anterior a coleta, ou cruzamento de dados com o mautic. Nós saberemos quem ele é simplesmente porque ele quer saber mais do que a EJ pode oferecer. É quase uma estratégia de curso gratuito que instiga o usuário a comprar o curso pago.

**Comment by ricardopoppi** [comment]
Acho que para esse escopo tá ótimo: exibe a explicação, as informações gerais, as informações dos grupos a partir de um número de votos (sugestão: default 500 e eventualmente configurável via tag).

Essa parte da transação coleta de dados de contato e envio de relatórios automatizados por email/zap tem tudo a ver com o contexto do projetão vamos poder discutir isso bem melhor e com mais info do panorama geral. Concordo plenamente com a premissa e acho uma baita ideia, mas prefiro não decidirmos assim na pressa. Muitos alunos que vão usar nosso teste nem email tem, por exemplo. Tem várias incertezas que vamos poder trabalhar melhor olhando essa questão com a energia e recursos adequados para isso.

**Comment by davidCarlos** [comment]
Beleza, vamos seguir nesse plano.

**Comment by davidCarlos** [comment]
**Issues**
- [ ] Implementar visualização por abas. Primeira aba deve ser o card para comentários, segunda aba deve ser card de resumo;
- [ ] Apresentar mensagem que ainda não há informações sobre os grupos caso o número de votos seja inferior a 500;
- [ ] Replicar visualização dos comentários por cluster existente na área da conversa na EJ

**Comment by ricardopoppi** [comment]
Página do componente já com a nova versão.

Qdo selecionamos a exibição de grupos, aparentemente o endpoint tá retornando com 404:

p-2fe6417d.js:1 TypeError: Cannot read property 'name' of undefined
    at u.render (p-5h15sjdr.entry.js:1)
    at z (p-2fe6417d.js:1)
    at Array.l (p-2fe6417d.js:1)
    at _ (p-2fe6417d.js:1)
    at v (p-2fe6417d.js:1)

p-5h15sjdr.entry.js:1 GET https://ejplatform.pencillabs.com.br/api/v1/clusterizations/57/clusters/ 404

TypeError: this.clusters.map is not a function
    at u.render (p-5h15sjdr.entry.js:1)
    at z (p-2fe6417d.js:1)
    at Array.l (p-2fe6417d.js:1)
    at _ (p-2fe6417d.js:1)
    at v (p-2fe6417d.js:1)

(via inspector)

**Comment by davidCarlos** [comment]
> Página do componente já com a nova versão: https://cidadedemocratica.org.br/ej/
> 
> Qdo selecionamos a exibição de grupos, aparentemente o endpoint tá retornando com 404:
> 
> p-2fe6417d.js:1 TypeError: Cannot read property 'name' of undefined
> at u.render (p-5h15sjdr.entry.js:1)
> at z (p-2fe6417d.js:1)
> at Array.l (p-2fe6417d.js:1)
> at _ (p-2fe6417d.js:1)
> at v (p-2fe6417d.js:1)
> 
> p-5h15sjdr.entry.js:1 GET https://ejplatform.pencillabs.com.br/api/v1/clusterizations/57/clusters/ 404
> 
> TypeError: this.clusters.map is not a function
> at u.render (p-5h15sjdr.entry.js:1)
> at z (p-2fe6417d.js:1)
> at Array.l (p-2fe6417d.js:1)
> at _ (p-2fe6417d.js:1)
> at v (p-2fe6417d.js:1)
> 
> (via inspector)

Cria uma issue separada pra esse comentário, e adiciona o label `bug` nela. Inclui na descrição uma referência pra essa história aqui, por favor. Também adiciona essa nova issue no milestone que representa a sprint atual (1.7.13).

**Comment by ricardopoppi** [comment]
combinado. Feito
