### ISSUE TITLE
Implementar mecanismo que permita ao usuário consentir que o componente utilize seu cookie do analytics para autentica-lo na EJ.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#192]
Proposta preliminar de texto. O texto deve ser específico por tema do componente, como é hoje, já que a parte do início, com o objetivo da coleta, pode mudar de acordo com a aplicação. O restante do texto tende a permanecer igual para várias aplicações do componente:

"_Essa consulta tem o objetivo de coletar opiniões para melhorar o ambiente escolar. Nós utilizamos os cookies do google analytics e mautic para fazer a sua autenticação e para melhorar a eficiência desta ferramenta ao combinar os dados de opinião com as informações comportamentais que você nos fornece ao navegar pelo nosso domínio. Caso você tenha nos fornecido ou forneça no futuro, diretamente, alguma informação pessoal (email, telefone etc) usaremos os cookies para te identificar. Caso contrário sua autenticação será anônima. Não fornecemos suas informações pessoais para ninguém e caso queira que seus dados sejam excluídos por favor clique na opção opt-out. Para obter mais detalhes de nossa política de privacidade, por favor acesse-a diretamente no link abaixo._"

Proposta de implementação:
https://app.goadopt.io/

Ver ele aplicado: https://agentesdacidadania.org.br/
Por enquanto só está funcionando no visual. Para funcionar de verdade (ou seja, impedir a carga dos cookies), será necessário configurar os callbacks: https://docs.goadopt.io/callbacks
Além disso, não vi ser possível customizar o texto, o que pra nós vai ser um problema. Mas ainda vou consultá-los sobre essa possibilidade, senão existem outras plataformas de consentimento pra LGPD, aí podemos achar uma que permita.

Implementando via AdOpt, podemos eliminar aquela primeira tela do board e já cair direto no onboarding da conversa (o tutorial)

Outras referencias:

**Mobile:**
https://www.youtube.com/watch?v=RBZLFhgmCkI

**Desktop:**
![IMG-20201209-WA0009](https://user-images.githubusercontent.com/1162183/101834673-6df62080-3b19-11eb-8418-b62a3bafaff6.jpg)

**Comment by ricardopoppi** [comment]
Update do suporte da plataforma de gestão de consentimento AdOpt sobre o uso do cookie analytics para duas finalidades, ou seja, autenticação e tratamento de dados comportamentais:

_Então, temos 2 caminhos, baseado no que nossos clientes tem enfrentado:

1 - a Google tem feito um movimento de unificar essas funcionalidades sob a mesma tag/cookie, de fato sendo muito difícil dierencia-los. O que força as empresas a colocarem a tag google como necessaria, logo não é opcional o consentimento, logo "passa boi, passa boiada da google". O que muitos tem feito é assumido esse risco mas, detalhado a quebra dos serviços dentro da política de privacidade e termos de uso. Essa seria a versão fácil

2- A versão mais complexa, que sabemos que seria um caminho mas, nunca vimos ninguém fazer é: estudar todas as tags/cookies do google para saber se elas de fato têm distinção, para poder categorizá-las corretamente, dando a opção mais transparente para o usuário. O problema é que o google tem atualizado as tags e cookies, continuamente.
então esse serviço fica sempre mais **difícil**_


Meu comentário sobre isso: podemos fazer um roadmap de assumir a mais fácil agora no curto prazo e deixar essa análise no radar pro médio prazo, considerando que vamos ter que ter capacidade de gestão pra monitorar as atualizações desse tipo feitas pela google

**Comment by davidCarlos** [comment]
Minha posição técnica: Não vale a pena integrar um serviço com fluxo de UX próprio (que difere do fluxo do componente) agora. O ideal, para o dia 15, é implementar o concentimento diretamente via board no componente. Podemos avaliar pós dia 15 se será necessário integrar o componente com um serviço de terceiros, ou se apenas o concentimento via board já é suficiente. Não podemos esquecer que o componente não é um site, ele é uma tag html, como uma div, então depender de qualquer recurso externo ao componente tem que ser sempre avaliado com cautela. 

Existe um outro ponto de reflexão aqui: Os sites em que o componente estará incluído podem ter suas próprias políticas de cookies, e nada garante que nós poderemos incluir um outro sistema externo (via header) para também gerenciar os cookies apenas na pagina do componente. Uma solução built-in no componente, por exemplo, não depende, e não impacta, a gestão de cookies do resto do site.

**Comment by ricardopoppi** [comment]
Ok, entendido. Vamos assim então pro dia 15 e avaliamos a integração pro roadmap maior de LGPD do projeto de 2021

**Comment by davidCarlos** [comment]
Perfeito
