### ISSUE TITLE
Como participante da coleta, gostaria de consentir que o componente utilize o cookie do analytics para cruzar meus dados de opinião e comportamento.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#193]
**Issues**
- [x] Alterar texto da primeira modal, para que ele esteja alinhado com a LGPD;
- [x] Bloquear criação do usuário enquanto os termos da LGPD não forem aceitos;

**Critérios de aceitação**

- [x] Caso o usuário não aceite os termos, nenhum dado dele deve ser coletado (inclusive os cookies).
- [x] Caso o usuário não aceite os termos, deve haver uma opção dele concordar com os termos novamente (Já existe esse comportamento, essa issue deve manter o mesmo fluxo).
- [x] Caso a autenticação seja via analytics/mautic, enquanto o termo da LGPD não for aceito, deve aparecer o componente de registro. Após aceite, a autenticação via cookie é feita, e o componente de comentários deve ser apresentado;

**Comment by ricardopoppi** [comment]
Acredito que com a redação sugerida na issue #192 e com o uso de uma plataforma de gestão de consentimento (como a AdOpt) acredito que essa issue se torna desnecessária.

O texto lá proposto, contempla o consentimento específico para duas finalidades (autenticação e cruzamento) com menção explícita dos cookies que fornecem essa informação, com a possibilidade do usuário desativar individualmente cada um na totalidade. Vale uma consulta externa sobre se isso traz algum risco, ainda que essa seja a forma com que está sendo implementado pelas plataformas comerciais de gestão de consentimento no brasil (LGPD).

Acredito que essa implementação se deva ao fato do texto da lei dizer que o importante é a determinação das finalidades específicas, evitando consentimentos genéricos.

Nessa referencia abaixo, de uma plataforma de gestão de consentimento que atende a LGPD no Brasil, a linha é parecida com a que propus na issue #192 ou seja, o consentimento é por tipo de cookies, nesse caso sem permitir a ativação/inativação de cookies específicos, como no caso da AdOpt que além de permitir desabilitar os grupos também permite que o usuário inabilite cada cookie individualmente

![Captura de tela de 2020-12-10 22-50-29](https://user-images.githubusercontent.com/1162183/101851352-2469fd80-3b3a-11eb-8bbd-1312357184ea.png)
![Captura de tela de 2020-12-10 22-50-35](https://user-images.githubusercontent.com/1162183/101851359-28961b00-3b3a-11eb-8264-b5b06cbd7458.png)

**Comment by ricardopoppi** [comment]
Ainda sobre isso, no caso da ref do https://ico.org.uk/ o texto explicita duas finalidades, a depender do tipo de cookies. Os necessários com a finalidade de fazer o site funcionar e os opcionais com a finalidade de aprimorar o site. Uma linha parecida com a proposta na issue #192 cujas finalidades apresentadas são a de autenticar e a de aprimorar a eficiência da ferramenta, num primeiro momento de forma anônima, mas com a possibilidade de identificação por dados pessoais caso o usuário forneça, diretamente, essas informações pra nós em qq momento do passado ou do futuro de sua interação com os nossos domínios.

**Comment by davidCarlos** [comment]
Não vejo que pelo fato do concentimento de uso do cookie para autenticação essa issue se torne desnecessária. Note que no caso da isse #192 estaremos usando o cookie para criar o usuário na EJ e permitir a participação na coleta. No caso dessa issue, o impacto chega até o airflow/dash, porquê se o usuário não permitir o uso do analytics para cruzamento, nos não podemos nem coletar nem cruzar os dados via airflow. 

Então esse issue prevê a seguinte discussão: Como faremos para que o airflow não cruze os dados de um usuário que permitiu a autenticação via analytics, mas não permitiu o cruzamento dos seus votos com seus dados comportamentais? Provavalmente teremos que guardar no usuário da EJ, se o concetimento foi parcial (apenas autenticação), ou total (autenticação e cruzamento).

**Comment by davidCarlos** [comment]
Existe uma questão relacionada à arquitetura do ecossistema EJ quando se trata de cruzamento de dados. Note que no caso da isse #192 estaremos usando o cookie para criar o usuário na EJ e permitir a participação na coleta. No caso dessa issue, o impacto chega até o airflow/dash, porquê se o usuário não permitir o uso do analytics para cruzamento, nos não podemos nem coletar nem cruzar os dados via airflow. 

Então esse issue prevê a seguinte discussão: Como faremos para que o airflow não cruze os dados de um usuário que permitiu a autenticação via analytics, mas não permitiu o cruzamento dos seus votos com seus dados comportamentais? Provavalmente teremos que guardar no usuário da EJ, se o concetimento foi parcial (apenas autenticação), ou total (autenticação e cruzamento).

**Comment by ricardopoppi** [comment]
Sim vamos precisar avaliar isso. Neste momento, como não temos como fazer esse tratamento diferenciado, sugiro implementarmos um consentimento único no board, informando que fazemos dois usos: autenticação e cruzamento. Se o usuário recusar estará recusando os dois, ou aceitando os dois. Não é o ideal pra LGPD mas é uma saída provisória possível (há implementações fazendo isso hoje)

**Comment by davidCarlos** [comment]
Beleza. Vamos seguir nesse caminho então, ou aceita ambas as opções ou não participa da coleta.
