### ISSUE TITLE
Componente não exibe informação dos grupos

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#197]
Página do componente já com a nova versão: https://cidadedemocratica.org.br/ej/

Qdo selecionamos a exibição de grupos, aparentemente o endpoint tá retornando com 404:

p-2fe6417d.js:1 TypeError: Cannot read property 'name' of undefined
at u.render (p-5h15sjdr.entry.js:1)
at z (p-2fe6417d.js:1)
at Array.l (p-2fe6417d.js:1)
at _ (p-2fe6417d.js:1)
at v (p-2fe6417d.js:1)

p-5h15sjdr.entry.js:1 GET https://ejplatform.pencillabs.com.br/api/v1/clusterizations/57/clusters/ 404

TypeError: this.clusters.map is not a function
at u.render (p-5h15sjdr.entry.js:1)
at z (p-2fe6417d.js:1)
at Array.l (p-2fe6417d.js:1)
at _ (p-2fe6417d.js:1)
at v (p-2fe6417d.js:1)

(via inspector)

**Comment by ricardopoppi** [comment]
odeio ser portador de más notícias kkkk

mas tem alguma coisa chamando a API em http e impedindo de carregar. Conferi e não é nos snipets. Inspector:

Mixed Content: The page at 'https://cidadedemocratica.org.br/ej/' was loaded over HTTPS, but requested an insecure resource 'http://ejplatform.pencillabs.com.br/api/v1/clusterizations/57/clusters'. This request has been blocked; the content must be served over HTTPS

**Comment by davidCarlos** [comment]
Rola de me passar acesso nesse wp? Eu não tenho como debugar o componente sem ter acesso pra ir alterando as versões.

**Comment by davidCarlos** [comment]
Issue resolvida. Falta apenas fazer ajustes de css para que o componente não quebre no site do cidades. Abrirei uma nova issue de bug na nova sprint.
