### ISSUE TITLE
Corrigir bugs da aba de grupos no site do cidades

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#198]
Bugs inseridos pela US #190.

**Tarefas**

- [x] Extrair footer do componente, para um componente a parte. Hoje o footer é implementado direto no componente de comentários;
- [x] Footer do site está cobrindo a aba de comentários;
- [x] ícones na aba de grupos não estão aparecendo;

**Comment by MarthaDs** [comment]
@davidCarlos Onde fica essa parte que ta cobrindo a aba dos comentários no site?
p.s.: Já implementei a extração do footer para um componente a parte nessa branch [aqui](https://gitlab.com/pencillabs/ej/conversation-component/-/tree/fix-bugs-issue198)

**Comment by davidCarlos** [comment]
> @davidCarlos Onde fica essa parte que ta cobrindo a aba dos comentários no site?
> p.s.: Já implementei a extração do footer para um componente a parte nessa branch [aqui](https://gitlab.com/pencillabs/ej/conversation-component/-/tree/fix-bugs-issue198)

Melhor você fazer tudo em uma branch só, vai facilitar minha revisão.
Os bugs no site você pode ver aqui https://instituto.cidadedemocratica.org.br/ej/. Você pode alterar o css direto na pagina, e conforme for corrigindo, vai jogando pro código no repo. O componente é inserido no site direto via npm, então pra correção ir pra lá de fato, vamos precisar lançar uma nova versão.

**Comment by MarthaDs** [comment]
O site está fora do ar então por hora essa issue está parada

**Comment by ricardopoppi** [comment]
@MarthaDs reativei o site, acredito que possa retomar essa issue :-)

**Comment by ricardopoppi** [comment]
@davidCarlos @MarthaDs gente, sobre essa página, tem umas diferenças que me parecem não ter relação com o site do instituto. Algumas são mais visuais que acho que pode ser o wp interferindo no componente (pegamos esse caso no site da UCC) mas outras talvez de faltar alguns elementos. A mais crítica, que acaba interferindo na ux, e a falta dos botões de expandir os comentários, vejam print:

Versão na EJ:
![screenshot-ejplatform pencillabs com br-2021 01 22-10_18_40](https://user-images.githubusercontent.com/1162183/105496174-e2d18400-5c9b-11eb-95aa-530ca19a32a9.png)

Versão no componente:
![screenshot-cidadedemocratica org br-2021 01 22-10_18_56](https://user-images.githubusercontent.com/1162183/105496205-efee7300-5c9b-11eb-9353-c15a30e96b24.png)

**Comment by davidCarlos** [comment]
O comportamento no componente nesse caso é igual na EJ. O ícone aparece quando há comentários pra apresentar. Isso está implementado. O ícone não está aparecendo por um problema no processo de publicar o componente. Me parece que os ícones não estão indo para o diretório `dist`, que é o diretório final que vai pro npm quando o componente é publicado. Essa história técnica já tem uma tarefa prevista pra isso.

> ícones na aba de grupos não estão aparecendo;

**Comment by ricardopoppi** [comment]
Entendido. Se já está mapeado maravilha :-)

**Comment by MarthaDs** [comment]
@ricardopoppi o footer ja voltou a aparecer ? Sem ele nao tem problema , aparentemente, no componente.

![Screenshot from 2021-01-25 14-41-39](https://user-images.githubusercontent.com/12221656/105744222-91372c80-5f1b-11eb-8b87-206ae51d4c54.png)

**Comment by MarthaDs** [comment]
> O comportamento no componente nesse caso é igual na EJ. O ícone aparece quando há comentários pra apresentar. Isso está implementado. O ícone não está aparecendo por um problema no processo de publicar o componente. Me parece que os ícones não estão indo para o diretório `dist`, que é o diretório final que vai pro npm quando o componente é publicado. Essa história técnica já tem uma tarefa prevista pra isso.
> 
> > ícones na aba de grupos não estão aparecendo;

@davidCarlos o segundo critério de aceitação dessa issue foi para outra issue então ?

**Comment by ricardopoppi** [comment]
> @ricardopoppi o footer ja voltou a aparecer ? Sem ele nao tem problema , aparentemente, no componente.
> 
> ![Screenshot from 2021-01-25 14-41-39](https://user-images.githubusercontent.com/12221656/105744222-91372c80-5f1b-11eb-8b87-206ae51d4c54.png)

@MarthaDs sim, acho que podemos deixar sem o footer mesmo. o bug mais crítico pra entrega agora é aparecer o "+" pra expandir as duas listas de comentários

**Comment by davidCarlos** [comment]
> > @ricardopoppi o footer ja voltou a aparecer ? Sem ele nao tem problema , aparentemente, no componente.
> > ![Screenshot from 2021-01-25 14-41-39](https://user-images.githubusercontent.com/12221656/105744222-91372c80-5f1b-11eb-8b87-206ae51d4c54.png)
> 
> @MarthaDs sim, acho que podemos deixar sem o footer mesmo. o bug mais crítico pra entrega agora é aparecer o "+" pra expandir as duas listas de comentários

Eu devo arrumar isso até quarta-feira.

**Comment by davidCarlos** [comment]
@MarthaDs eu já corrigi o carregamento dos ícones. Pode abrir o MR dessa TS apenas com a extração do footer.

**Comment by MarthaDs** [comment]
> @MarthaDs eu já corrigi o carregamento dos ícones. Pode abrir o MR dessa TS apenas com a extração do footer.

MR criado -> [MERGE](https://gitlab.com/pencillabs/ej/conversation-component/-/merge_requests/6)

**Comment by MarthaDs** [comment]
@davidCarlos Correção feita no MR
