### ISSUE TITLE
Erro na primeira carga do componente para novos usuários

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#201]
Na primeira carga do componente para novos usuários (aba anonima) a página fica sem conteúdo e o inspector exibe um erro (ver print). Ao fazer o refresh da página, o componente carrega normalmente.

p-r0s8lthj.entry.js:1 Uncaught (in promise) Error: could not authenticate user
    at c.authenticate (p-r0s8lthj.entry.js:1)
    at h.componentWillLoad (p-r0s8lthj.entry.js:1)
    at J (p-2fe6417d.js:1)
    at V (p-2fe6417d.js:1)
    at r (p-2fe6417d.js:1)
    at p-2fe6417d.js:1

![Captura de tela de 2021-01-28 08-15-40](https://user-images.githubusercontent.com/1162183/106131434-70e8b700-6141-11eb-9357-a0496f7a8a57.png)

**Comment by davidCarlos** [comment]
@fabiolamfleury consegue dar uma olhada nesse bug aqui? 
Site do cidades: https://cidadedemocratica.org.br/ej/

Eu acho que esse bug foi inserido depois que a gente passou a bloquear o cadastro do usuário enquanto ele não aceita os termos da LGPD. Se você começar a investigar pelo componente principal (`main.tsx`), vai ver como tá essa implementação.
Deve ter relação com a US #193

**Comment by fabiolamfleury** [comment]
Vou dar uma olhada!

**Comment by fabiolamfleury** [comment]
Vendo no site do ICD, o que aparenta ocorrer é ele tentar acessar o cookie antes dele estar preenchido, o que aconteceu localmente também

![Captura de tela de 2021-01-28 16-47-19](https://user-images.githubusercontent.com/20935369/106190612-aa90e080-6188-11eb-86cc-a6f6da2d3ca1.png)


Fiz algumas alterações no código e funcionou no incognito do chrome mas do mozilla não, pelo que pude pesquisar, por conta da forma dos dois armazenarem cookies.

No mozilla apresenta o seguite erro:

- O conteúdo “https://www.google-analytics.com/analytics.js” foi bloqueado porque o bloqueio de conteúdo está ativo localhost:3333
- Falha no carregamento do <script> com a fonte “http://mautic.local/mtc.js”. localhost:3333


Tentando quebrar um pouco mais a cabeça pra ver se uma solução mais permanente sai

**Comment by ricardopoppi** [comment]
Se pudermos colocar em produção o fix do chrome seria bom, considerando que vamos fazer a entrega dessa página https://cidadedemocratica.org.br/ej2/ hoje a tarde

**Comment by fabiolamfleury** [comment]
@ricardopoppi o merge request ta aqui, pendendo uma revisão ainda - subi ele só no sábado: https://gitlab.com/pencillabs/ej/conversation-component/-/merge_requests/7 resolve no firefox também (mas a pessoa tem q ter desabilitado o script de segurança dele).

**Comment by davidCarlos** [comment]
> @ricardopoppi o merge request ta aqui, pendendo uma revisão ainda - subi ele só no sábado: https://gitlab.com/pencillabs/ej/conversation-component/-/merge_requests/7 resolve no firefox também (mas a pessoa tem q ter desabilitado o script de segurança dele).

No FF não tem muito o que fazer, já que a gestão de cookies dele é bem mais rígida do que no Chrome. Acho que a solução de desabilitar o script é a nossa única opção mesmo.

Vou priorizar aqui a review desse MR

**Comment by davidCarlos** [comment]
Talvez vale avaliar, se não é o caso de implementar um aviso no componente, pra quando o usuário estiver no FF.

**Comment by ricardopoppi** [comment]
Sim, de acordo, no ff vai ter essa questão mesmo. Dessa forma nos atende bem, minimiza (ou até elimina) os riscos do cliente clicar e aparecer uma página vazia.

**Comment by ricardopoppi** [comment]
> Talvez vale avaliar se não é o caso de implementar um aviso no componente, pra quando o usuário estiver no FF.

Se achar que é viável pra agora tudo bem, senão acho que o melhor é subir o fix como está e manter essa do aviso pra uma melhoria pós entrega.

**Comment by davidCarlos** [comment]
Isso não está previsto pra essa sprint. O fluxo é jogar pro product backlog e em algum momento a gente prioriza. @ricardopoppi Por favor, cria uma issue pra gente com o label `technical story`, e joga pra coluna `Product Backlog`, no demo.eco fase 1.

**Comment by ricardopoppi** [comment]
> Isso não está previsto pra essa sprint. O fluxo é jogar pro product backlog e em algum momento a gente prioriza. @ricardopoppi Por favor, cria uma issue pra gente com o label `user story`, e joga pra coluna `Product Backlog`, no demo.eco fase 1.

combinado

**Comment by davidCarlos** [comment]
Nova versão publicada. `1.7.15-beta1`. @ricardopoppi valida pra gente se vai tudo funcionar bem

**Comment by ricardopoppi** [comment]
Fiz o bump e funcionou de prima! Valeu pela agilidade :-D

**Comment by davidCarlos** [comment]
qualquer demanda no componente, marque a @fabiolamfleury, kkk
