### ISSUE TITLE
Evoluir página de integrações da EJ,  para que cada integração seja apresentada no formato de plugin.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#202]
Existe uma pagina da EJ, que foi criada para documentar as configurações necessárias para integrar a EJ com outras ferramentas. Essa pagina fica na rota /integrations. O objetivo dessa história técnica é evoluir essa pagina, para uma melhor apresentação dessas integrações.
![pagina_integrations_ej](https://user-images.githubusercontent.com/2847027/106458124-adccea80-646e-11eb-8464-fc3892b55539.png)

Um exemplo que podemos utilizar de base é a pagina de plugins do WP
![image](https://user-images.githubusercontent.com/2847027/106458604-672bc000-646f-11eb-956d-90ed5a1ece37.png)

**Tarefas**

- [x] Refatorar estrutura da pagina para apresentar cada plugin em um formato de card;
- [x] Criar pagina interna para cada plugin. Por exemplo, para a integração com o mautic: **/integrations/mautic**;
- [x] Mover configurações existentes para páginas internas de cada plugin;

**Critérios de aceitação**

- [x] Ao clicar em um plugin, o usuário deve ser redirecionado para a respectiva pagina de configuração;

**Comment by davidCarlos** [comment]
Buscando outras referências de plataformas que são integradas com outros sistemas, acho que a página do Gitlab é mais próximo das integrações que temos hoje com a EJ.

![image](https://user-images.githubusercontent.com/2847027/106766949-240d5080-6619-11eb-8597-56bf1cd9b33b.png)

Estou mais enclinado a seguir esse formato, ao invés do formato de Plugins do WP.

**Comment by davidCarlos** [comment]
![localhost_8000_conversations_53_ucc_](https://user-images.githubusercontent.com/2847027/107280190-c2911b80-6a36-11eb-9dc1-69e28f28ff80.png)

![localhost_8000_conversations_53_ucc_tools](https://user-images.githubusercontent.com/2847027/107279878-63330b80-6a36-11eb-9c62-ddfeb847bcef.png)

![localhost_8000_conversations_53_ucc_tools_mailing](https://user-images.githubusercontent.com/2847027/107279874-61694800-6a36-11eb-9d71-c448c62e48ec.png)

![localhost_8000_conversations_53_ucc_tools_component](https://user-images.githubusercontent.com/2847027/107279858-5ca49400-6a36-11eb-986c-d805be379a1f.png)



@ricardopoppi o que acha? As paginas internas de cada ferramenta serão evoluídas  na próxima sprint.

**Comment by ricardopoppi** [comment]
> @ricardopoppi o que acha? As paginas internas de cada ferramenta serão evoluídas na próxima sprint.

Achei fera demais, o exemplo do gitlab é o mais adequado mesmo. Importante que na coluna integração o nome da ferramenta apareça com o estilo clicável (imagino que já tá previsto isso mas como não tá assim no mock então reforcei ;-))

**Comment by davidCarlos** [comment]
Isso eu fiz um pouco diferente do gitlab. A linha inteira da tabela é clicável, não só a coluna integração.

**Comment by ricardopoppi** [comment]
acho um ganho a tabela toda ser clicável, mas acredito que eliminar o estilo de link pode ser uma perda de ux. Será que vai ser óbvio para o usuário que esse texto é clicável? Digo isso porque olhando o estilo, parece mais uma tabela informativa do que um elemento com ação.

O que acha?

**Comment by davidCarlos** [comment]
> acho um ganho a tabela toda ser clicável, mas acredito que eliminar o estilo de link pode ser uma perda de ux. Será que vai ser óbvio para o usuário que esse texto é clicável? Digo isso porque olhando o estilo, parece mais uma tabela informativa do que um elemento com ação.
> 
> O que acha?

![image](https://user-images.githubusercontent.com/2847027/107712119-9a5c2380-6ca7-11eb-9b68-b435f3d37d87.png)

mantive o estilo de link na coluna "Integração"
