### ISSUE TITLE
Criar domínio simplificado para o assistente.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#204]
Essa história técnica será o primeiro estudo envolvendo o Rasa que faremos para o projeto. A ideia aqui é pensar um modelo simples, que envolva as estruturas básicas que serão necessárias para que o bot converse com o usuário. A ideia, nesse primeiro momento, é simular o voto em uma conversa pré-definida no rasa. Trocar algumas frases com o usuário, e deixar a estrutura para envio do voto para a EJ pronta. Note que essa TS não cobre enviar o voto para a EJ ainda, pois precisamos estudar como faremos o processo de autenticação;

**Tarefas**

- [x] Criação das intents;
- [x] Criação das entities;
- [x] Criação dos responses;
- [x] Criação de testes;

**Comment by fabiolamfleury** [comment]
A solução foi colocada no MR: https://gitlab.com/pencillabs/ej/ej-bot/-/merge_requests/2 (por problemas técnicos n consegui linkar pra fechar diretamente aqui)
