### ISSUE TITLE
Criar stack no swarm para subir rasa X

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#205]

**Comment by fabiolamfleury** [comment]
Abri o PR no repositório da infra, acredito estar funcionando ok, testei uma conversa usando a interface do rasa x e foi tranquilo, o que ainda não consegui configurar, é que o bot precisa apontar para uma instância do EJ pra conseguir recuperar os comentários de uma conversa.

**Comment by davidCarlos** [comment]
Acho que vale tentar fazer deploy da stack da EJ no cluster local, e apontar o rasa para o serviço da ej `ej_local_server`. A Lorrany está por dentro do deploy da ej, vale trocar figurinha com ela.
