### ISSUE TITLE
Subir rasa opensource via docker-compose

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#207]
Permitir que o desenvolvedor suba o rasa opensource em seu ambiente de desenvolvimento. O processo deve ser automatizado via Makefile (sugestão: `make run`), disponibilizando um único comando que faça os passos necessários para subir o ambiente.

**Comment by fabiolamfleury** [comment]
Já está disponível no nosso repositório do gitlab uma versão do docker, com uma documentação no readme e também no Makefile. Testei localmente, limpando todo meu ambiente pra certificar, mas é bom ver se tá ok em outras máquinas também :)

Os comandos do rasa demoram um bocado pra rodar (principalmente o build e o train)

Tive um problema quanto a configurar o .gitlabci que pelo que entendi precisa de configuração de um runner específico para conseguir rodar comandos docker - nunca mexi com o docker no gitlabci, vou ver o que outros repositórios implementaram pra tentar entender.

Dito isso, também tem uma implementação estrutura bem simples pra já usarmos de base pro bot conversar com a pessoa.

**Comment by fabiolamfleury** [comment]
Com a ajuda da @MarthaDs conseguimos corrigir alguns problemas que estavam ocorrendo ao subir o ambiente. 

Existe uma questão, ao utilizar esse ambiente docker para subir no gitlab ci, uma build está demorando 10minutos, mesmo sem ter nada muito complexo implementado no bot, talvez algo pra avaliar no futuro

**Comment by davidCarlos** [comment]
O CI está rodando em um runner compartilhado ou dedicado?

**Comment by fabiolamfleury** [comment]
Compartilhado

**Comment by davidCarlos** [comment]
Pode ser esse o motivo da demora. Podemos marcar uma call pra rodar essas builds no nosso runner na AWS.

**Comment by davidCarlos** [comment]
O Ideal mesmo era subir um pipeline de CI/CD só para o rasa, porquê isso pode impactar o pipeline de outros projetos (já que o rasa tem um consumo alto de recursos).

**Comment by fabiolamfleury** [comment]
Seria legal uma call, não tenho muita experiência com essa parte

**Comment by MarthaDs** [comment]
Acredito que com aceitaçao desse [MR](https://gitlab.com/pencillabs/ej/ej-bot/-/merge_requests/3) essa issue já pode ser finalizada.
