### ISSUE TITLE
Avaliar de que forma podemos implementar o fluxo de autenticação do usuário que irá participar de uma coleta via ejBot

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#208]

**Comment by fabiolamfleury** [comment]
Pensando no que o @davidCarlos levantou e o que tem na documentação do rasa, sugiro usarmos o JWT para fazermos uma autenticação similar ao que já ocorre no componente de conversa. Existe por exemplo o módulo python PyJWT, capaz de gerar um token, e esse token seria compatível com o sistema de autenticação do rasa, caso em algum momento precisarmos gravar a sessão do usuário no lado do bot também.


Essa implementação é possível por meio de uma custom action, que pode realizar a autenticação antes mesmo do usuário iniciar a conversa ou depois que ele concordar com a LGPD, ai vai depender de como montarmos a story.

Trecho da [documentação do rasa](https://rasa.com/docs/rasa/http-api/#jwt-based-auth): 

# JWT Based Auth

Enable JWT based authentication using --jwt-secret thisismysecret. Requests to the server need to contain a valid JWT token in the Authorization header that is signed using this secret and the HS256 algorithm.

The token's payload must contain an object under the user key, which in turn must contain the username and role attributes. If the role is admin, all endpoints are accessible. If the role is user, endpoints with a sender_id parameter are only accessible if the sender_id matches the payload's username property.
```
rasa run \
    -m models \
    --enable-api \
    --log-file out.log \
    --jwt-secret thisismysecret
Your requests should have set a proper JWT header:
```

```
"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ"
                 "zdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIi"
                 "wiaWF0IjoxNTE2MjM5MDIyfQ.qdrr2_a7Sd80gmCWjnDomO"
                 "Gl8eZFVfKXA6jhncgRn-I"
```
The following is an example payload for a JWT token:
```
{
    "user": {
        "username": "<sender_id>",
        "role": "user"
    }
}
```

**Comment by MarthaDs** [comment]
@davidCarlos em relação a autenticação do usuário no rasa, a gnt deve seguir aquele mesmo fluxo do componente de so autenticar se o usuário permitir? Se sim:
E em relação a forma de autenticação acreditamos que pode ser feita da mesma forma que no componente de conversa. Assim que a conversa for iniciada com usuário cria se os cookies de autenticação mas so manda eles para ej se o usuário der permissão.  E em relação a autenticação via registro seria extraindo keywords das mensagem do usuário

**Comment by davidCarlos** [comment]
Por enquanto não vamos incluir nada de LGPD no fluxo do Rasa. Acho que isso vai aumentar demais o escopo dessa implementação. Também não vamos fazer autenticação via registro, pois também vai aumentar o escopo. Ao meu ver, podemos partir de uma solução simples via JWT. Um possível fluxo seria:

1. Usuário conectado ao ejBot;
2. ejBot gera o token JWT e monta o objeto User (igual é no componente);
3. ejBot registra/autentica o objeto User na api da EJ;
4. API responde o token de autenticação;
4. ejBot requisita nos endpoints de conversa/comentário utilizando o token que a EJ respondeu;

Uma questão que precisamos discutir, mas não precisa ser agora, é qual política de sessão vamos utilizar para manter o usuário conectado. É bem provável que a forma como fazemos no componente, salvando o token via localstorage, vai precisar ser repensada para o Rasa.

**Comment by davidCarlos** [comment]
Se o Rocket.chat (ou o Rasa) gerar um fingerprint (ou algo do tipo) por usuário, e a gente conseguir correlacionar o tokent JWT com esse usuário, ai a gente pode simplesmente refazer o fluxo, recuperando o token JWT do usuário e enviando o objeto User pra EJ. Sem isso, para um mesmo usuário, vamos ter que gerar n tokens JWT, o que não é uma opção viável.

**Comment by davidCarlos** [comment]
Lembrando que essa issue é de avaliação, assim que encontrarmos um caminho viável para iniciar essa implementação, uma nova história técnica deve ser criada na sprint (ou jogar pro backlog e a gente prioriza para a próxima).

**Comment by fabiolamfleury** [comment]
Fuçando aqui, nas actions do rasa, você pode pegar a sessão do usuário (que ele guarda pra ter informações de onde tá na conversa com aquele usuário, bem como o que tem armazenado nos slots) por meio do Tracker.

Como a gente já vai lidar com a autenticação pelas actions, acho que no final das contas vai ser uma coisa bem tranquila, com esse código aqui:


```
class ActionSessionId(Action):
    def name(self):
        return "action_session_id"

    def run(self, dispatcher, tracker, domain):
        session_id=tracker.sender_id
        dispatcher.utter_message("The session id is {}".format(session_id))
        return []

```

Ele já retorna a sessão do usuário, fiz um teste pelo terminal:

```
The session id is 49a80b250ccf468db4599c4f850b3626

```

**Comment by fabiolamfleury** [comment]
Usuário criado no EJ por meio das actions do rasa:
![image](https://user-images.githubusercontent.com/20935369/107679974-ff018900-6c7b-11eb-8cd9-e73c16b52ddf.png)
Por enquanto apenas criando o usuário mesmo, mas como ele retorna o token em breve vou testá-lo em outras rotas :sorriso_pequeno:

Tem q ver também um pouco melhor a questão da duração da sessão, qual seria ideal. Acredito que acabando a sessão do bot do rasa, não é possível 'recuperar' aquele user, pensando aqui se um sistema de autenticação no próprio rasa seria necessário

**Comment by davidCarlos** [comment]
> Usuário criado no EJ por meio das actions do rasa:
> ![image](https://user-images.githubusercontent.com/20935369/107679974-ff018900-6c7b-11eb-8cd9-e73c16b52ddf.png)
> Por enquanto apenas criando o usuário mesmo, mas como ele retorna o token em breve vou testá-lo em outras rotas :sorriso_pequeno:
> 
> Tem q ver também um pouco melhor a questão da duração da sessão, qual seria ideal. Acredito que acabando a sessão do bot do rasa, não é possível 'recuperar' aquele user, pensando aqui se um sistema de autenticação no próprio rasa seria necessário

Mandaram bem demais

**Comment by davidCarlos** [comment]
Em relação a sessão, vamos precisar pensar nisso mesmo, porquê não podemos recriar um usuário que já participou da conversa. Acho que uma gambiarra seria colocar um tempo de sessão longo (próximo ao tempo que vamos deixar a coleta rodando).

Uma solução mais robusta seria sempre solicitar uma info do usuário, como email. Faz algumas perguntas genéricas, e antes de autenticar ele na EJ a gente pergunta o email, como forma de identificar ele na base. Caso ele não queira informar, ai a gente gera um usuário novo.

**Comment by davidCarlos** [comment]
@fabiolamfleury pelo que eu estou avaliando do andamento, essa issue aqui está pronta, já que vocês já até conseguiram criar um usuário na EJ via Rasa. No nosso planning podemos pegar a experiência dessa issue e criar outras histórias técnicas que aprofundem na solução.
