### ISSUE TITLE
Erro ao carregar dados da conversa

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#209]
Em algumas tentativas, a carga de dados da conversa (EJ API) tem falhado com erro na parte do "random comment". 

Esse erro apareceu algumas vezes, durante a carga da conversa numa aba anonima. Ao recarregar a página, a carga ocorre normalmente.

Erro e print:

p-fcuk4i2s.entry.js:1 Uncaught (in promise) TypeError: Cannot read property 'random-comment' of undefined
    at c.getRandomCommentUrl (p-fcuk4i2s.entry.js:1)
    at c.getConversationNextComment (p-fcuk4i2s.entry.js:1)
    at d.prepareToLoad (p-fcuk4i2s.entry.js:1)
    at d.componentWillLoad (p-fcuk4i2s.entry.js:1)
    at J (p-2fe6417d.js:1)
    at V (p-2fe6417d.js:1)
    at r (p-2fe6417d.js:1)
    at p-2fe6417d.js:1
    at p-2fe6417d.js:1

![Captura de tela de 2021-02-01 11-54-27](https://user-images.githubusercontent.com/1162183/106475339-9862bb00-6484-11eb-8456-59920cf1484b.png)

**Comment by ricardopoppi** [comment]
Nesse caso, meu usuário já tinha votado em todos os comentários, essa pode ser uma hipótese de investigação

**Comment by fabiolamfleury** [comment]
recebo esse erro quando tento acessar uma conversa que não existe mas por enquanto não consigo reproduzir ele no caso de ter votado em todos

**Comment by fabiolamfleury** [comment]
> @fabiolamfleury você conseguiu reproduzir esse bug sem ser quando a conversa não existe?

Não consegui

**Comment by davidCarlos** [comment]
Não consegui reproduzir esse bug. Pode ter sido algum problema de comunicação com o servidor. De qualquer forma, o componente tem que tratar esse tipo de problema. A issue #245 deve cobrir este caso.
