### ISSUE TITLE
Implementar uma mensagem sobre uso de cookies no FF para a carga correta do componente

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#210]
Como a gestão do cookies no FF é mais rígida a solução é implementar uma mensagem que avise o usuário para desabilitar os bloqueios para ter uma experiência completa

**Comment by davidCarlos** [comment]
Fechando essa issue. Implementar isso pode gerar grande impacto na usabilidade do componente. O usuário já precisa interagir com os boards antes de cair na conversa, ter ainda que desabilitar os cookies, vai diminuir nossa taxa de aquisição. Com as ultimas implementações no componente, um usuário que chegue via firefox vai conseguir participar da coleta normalmente, pois mesmo que não haja nenhum cookie setado, o componente vai apresentar a tela de registro.
