### ISSUE TITLE
Extrair do componente ej-comments tudo que for relacionado a voto, e criar um novo componente chamado ej-votes

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#211]
O componente ej-comments gerencia tanto o fluxo de voto, quanto o fluxo de adicionar comentários. Ter duas responsabilidades dificulta a manutenção e evolução de cada um dos fluxos. A ideia é que essa issue extraia para um novo componente tudo que for relacionado ao fluxo de voto.

**Tarefas**

- [x] extrair do comments.tsx toda implementação relacionada ao fluxo de voto;
- [x] criar novo componente chamado votes.tsx (ej-votes)
- [x] Extrair componente ej-footer para a main.tsx
- [x] Fazer as formulações necessárias no arquivo comments.tsx para que esse componente possa ser usado no votes.tsx

**Critérios de aceitação**

- [x] Quando o usuário clicar em `CRIAR COMENTÀRIO`, o componente ej-comments deve ser carregado;

**Comment by davidCarlos** [comment]
@MarthaDs @lorryaze a ideia dessa issue é vocês trabalharem juntas nela. A @MarthaDs já trabalhou no componente e pode ir guiando o pareamento, qualquer duvida podem acionar ou a @fabiolamfleury ou eu.

**Comment by MarthaDs** [comment]
@davidCarlos e incluir uma tarefa nessa issue de refatoração para abranger uma atividade que julguei necessária para manter a solução existente no componente de conversa.

**Comment by davidCarlos** [comment]
qual tarefa?

**Comment by davidCarlos** [comment]
beleza

**Comment by MarthaDs** [comment]
O MR dessa issue pode ser encontrado [aqui](https://gitlab.com/pencillabs/ej/conversation-component/-/merge_requests/8)
