### ISSUE TITLE
 Como usuário, gostaria de interagir com conversas do EJ pelo assistente, para expressar minhas opiniões

### ISSUE THREAD

**Issue by fabiolamfleury** [cidadedemocratica/ej-server#219]
Enviar para a EJ, respostas dadas pelo usuário para o assistente.

O ej-bot deve ser capaz de receber respostas de voto e comentários do usuário e enviá-las, identificando-o, para o EJ. 

**Tarefas**

- [x] Processar o valor de um voto do usuário e enviá-lo, pro respectivo comentário com o token do usuário, para o EJ.
- [x] Processar se a intent do usuário foi valor de um voto ou um novo comentário
- [x] Caso o usuário envie um novo comentário, esse deve ser salvo no ej (e caso exista moderação, deve ficar com o status de 'pending')
- [x]  O usuário deve receber feedback a cada ação realizada (se o voto foi computado ou o comentário registrado

**Critérios de aceitação**
- [x] A exibição dos comentários deve ser realizada, até que o usuário peça pra parar ou tenha votado em todos comentários

**Comment by davidCarlos** [comment]
@fabiolamfleury acho que vale escrever essa história no formato de `user story`, conforme documentado na nossa [wiki de planejamento](https://gitlab.com/pencillabs/pencilabs/-/wikis/Gest%C3%A3o-de-projetos).

**Comment by fabiolamfleury** [comment]
> @fabiolamfleury acho que vale escrever essa história no formato de `user story`, já que essa issue vai interagir diretamente como o usuário que estará participando da coleta via ejBot. Acho que o mesmo vale para a issue #220. [Wiki para gestão dos projetos](https://gitlab.com/pencillabs/pencilabs/-/wikis/Gest%C3%A3o-de-projetos).

Opa, acabei me desatentando, atualizada!
