### ISSUE TITLE
Avaliar no assistente uma forma de requisitar dados de uma conversa específica

### ISSUE THREAD

**Issue by fabiolamfleury** [cidadedemocratica/ej-server#221]
A depender do contexto do bot (landing page, telegram, whatsapp) a conversa que será puxada do EJ será diferente.

**Tarefas**

- [ ] Definir a implementação no rasa para definição de conversas
- [ ] Definir formas de puxar do ej conversas e atualizar endpoints da API caso necessário (boards e tags)

**Comment by fabiolamfleury** [comment]
Dei uma lida na documentação do rasa e achei algumas possibilidades:

- Engatilhar intents, utilizando alguma outra plataforma, enviando para o bot:
https://rasa.com/docs/rasa/reaching-out-to-user#1-trigger-an-intent
- Detecção de qual canal está (slack, telegram, rocket.chat, twilio...) para tentar prever algo, conseguimos isso por meio do tracker, então da pra fazer manipulações nas actions:
```
tracker.get_latest_input_channel
```

Não sei se são os melhores caminhos, então vou continuar a investigação

**Comment by fabiolamfleury** [comment]
Um mesmo canal pode ser distribuído de diferentes formas, por exemplo o rocket.chat que é utilizado para integração em landing pages. Depois de uma longa lida na documentação do rasa, acredito que a melhor forma de fazer essa implementação é colocar no EJ a parte de seleção de conversas de um contexto do bot.

Estava pensando em colocar na página de integrações, na opção com rasa, a seleção de conversas que seriam usadas para a integração e onde seria feito essa integração (o endereço do site em q o rasa estaria rodando, o canal, algo nesse sentido). E aí seria armazenado no EJ esses dados, para que quando o rasa enviasse a requisição pro EJ, passaria esses dados para que pudesse puxar as conversas corretamente.

**Comment by davidCarlos** [comment]
Acho que esse é um ótimo caminho. Ainda temos algumas coisas que precisamos definir com o time de marketing digital, como por exemplo:

1. Na pagina oficial do projeto, teremos o ejBot integrado? E se sim, quais conversas apresentaremos? Se for mais de uma, talvez a gente tenha que atrelar o site a um board na EJ, e dentro do board ter conversas tageadas por assunto. Aqui entra aquele história no rasa, em que o usuário seleciona sobre qual assunto ele quer participar. Acho que isso é algo pra fase 2, mas precisamos alinhar com o time de mkt digital essa estratégia.
2. Nas Landing temáticas (vacina por exemplo) vai fazer sentido ter mais de uma conversa na EJ sobre um mesmo tema? No sentido de ser o mesmo tema, mas ter conversas com perguntas chave diferentes.

De qualquer forma, já podemos começar fazendo a relação um site -> uma conversa. Na pagina de integração o usuário cadastra o domínio, e qual conversa vai estar atrelada. O ejBot manda o domínio, e a EJ retorna a conversa.
