### ISSUE TITLE
Como usuário, quero me sentir acolhido para interagir com o assistente

### ISSUE THREAD

**Issue by fabiolamfleury** [cidadedemocratica/ej-server#222]
Implementar acolhimento  na primeira interação do usuário com o ejBot. A forma como o ejBot deve interagir com o usuário, deve ter relação com a personalidade pensada pela Gabi e Valéssio.

**Critérios de aceitação**
- [x] O bot deve receber uma requisição do tipo post com a intent do usuário
- [x] A primeira intent deve disparar um rule de boas vindas, fazendo A Duda(bot) enviar a primeira mensagem da conversa
- [x] A partir da primeira resposta do usuário a conversa deve seguir o fluxo já criado da conversa
- [x] A mensagem deve ser convidativa e coerente com a personalidade da Duda

**Comment by MarthaDs** [comment]
Criei um doc com modelo de conversa para o acolhimento que pode ser encontrado [aqui](https://docs.google.com/document/d/1XXzpzB6ZQNdAS7HlvySUL_od6iYx6DD84abGMA3QCDY/edit)

**Comment by MarthaDs** [comment]
Acho que melhor opção é usar um evento(usuário entrar no chat) como trigger para o bot iniciar. 
[Resposta achada no forum do rasa](https://forum.rasa.com/t/how-to-let-bot-start-the-conversation/20866/5)

**Comment by fabiolamfleury** [comment]
> Criei um doc com modelo de conversa para o acolhimento que pode ser encontrado [aqui](https://docs.google.com/document/d/1XXzpzB6ZQNdAS7HlvySUL_od6iYx6DD84abGMA3QCDY/edit)

Uma dica pra inserir emojis (caso queira) é copiar do https://emojipedia.org/. São reconhecidos como caracteres e com uma pesquisa rapida aqui parece que não costuma dar problema em canais diferentes (telegram, rocketchat etc)

**Comment by MarthaDs** [comment]
A solução que eu encontrei precisa exportar bot como api para conseguir mandar uma requisição que injeta uma intent do usuário , mas a api está dado erro 500 e recusando minha requisição, minha suspeita é que estou mandando o token errado

**Comment by davidCarlos** [comment]
Manda o body da requisição que você tá enviando pra api. Lembrando que o token é um campo que vai no Header `Authorization`. 

Uma forma mais simples de você testar essas requisições na api da EJ, é usar ferramentas como postman ou httpie.

**Comment by davidCarlos** [comment]
@fabiolamfleury não dá pra @MarthaDs reusar a implementação da api que você fez? Já que já conseguimos votar e puxar comentários.

**Comment by MarthaDs** [comment]
> Manda o body da requisição que você tá enviando pra api. Lembrando que o token é um campo que vai no Header `Authorization`.
> 
> Uma forma mais simples de você testar essas requisições na api da EJ, é usar ferramentas como postman ou httpie.

`HEADERS = {
    "Content-Type": "application/json",
    "Authorization": "JWT_SECRET"
}
BOT_URL = "http://localhost:5006/webhooks/rest/webhook"


class ActionWelcomeUser(Action):
    def name(self):
        return "action_welcome_user"
    
    def run(self, dispatcher, tracker, domain):
        data = {
            "sender": tracker.sender_id,
            "message": "Oi! Muito prazer, eu sou a Duda"
        }
        response = requests.post(
            url=BOT_URL,
            headers=HEADERS,
            data=data
        )
        return response
`

**Comment by MarthaDs** [comment]
> @fabiolamfleury não dá pra @MarthaDs reusar a implementação da api que você fez? Já que já conseguimos votar e puxar comentários.

Eu usuei isso como exemplo pra criar uma actions que faz a requisição

**Comment by davidCarlos** [comment]
Essa requisição que vc está mandando, é pra criar um usuário a partir do email informado no acolhimento? Tô meio perdido no fluxo

**Comment by davidCarlos** [comment]
Acho que faltou vocês consolidaram na issue como vai ser o fluxo de acolhimento. Essa consolidação é o critério de aceitação pra dizer se a issue tá feita ou não. Transformar o doc com a proposta de acolhimento, em tarefas aqui na issue.

**Comment by MarthaDs** [comment]
Eu atualizei os critérios de aceitação para descrever melhor o fluxo da issue. E achei algumas informações que podem ser indicativo que o rasa x talvez não de suporte para `trigger_intent` no domínio dele([AQUI](https://forum.rasa.com/t/trigger-intent-with-http-api-not-work-on-rasa-x/30302/2)). Mas talvez seja possível utilizar algo semelhante ao `trigger_intent`

**Comment by MarthaDs** [comment]
> Eu atualizei os critérios de aceitação para descrever melhor o fluxo da issue. E achei algumas informações que podem ser indicativo que o rasa x talvez não de suporte para `trigger_intent` no domínio dele([AQUI](https://forum.rasa.com/t/trigger-intent-with-http-api-not-work-on-rasa-x/30302/2)). Mas talvez seja possível utilizar algo semelhante ao `trigger_intent`

Confirmado o rasa x não da suporte. A opção seria usar chatroom ou  widget 
https://forum.rasa.com/t/reaching-out-to-the-user-how-to-set-it-up-with-rasa-x/39483/5

**Comment by davidCarlos** [comment]
Algumas considerações sobre o processo de acolhimento do ejBot e quais possibilidades de implementação nós temos. A ideia deste comentário é detalhar o porquê que o rasa X não suporta o `trigger_intent`, conforme a @MarthaDs  já tinha pontuado no comentário anterior.

Eu estou desde ontem estudando a documentação do rasa open source e do rasa x, e cheguei a algumas conclusões:

1. Conversas criadas pelo rasa x não são compartilhadas no rasa open source. É possível comprovar isso requisitando uma lista de conversas no rasa x e no rasa open source, o retorno de cada api não será igual. Ou seja, são APIs diferentes e me parece que bancos de dados diferentes também.
2. O trigger_intent está na documentação do rasa open source, logo, ele só vai funcionar em ferramentas que se conectem via socket ou api no rasa open, e não no rasa x.

Dados os pontos listados, algumas considerações sobre como desenvolver essa issue:

1. Para fazer o acolhimento, a opção mais *rasa-like* é ter um conector que mande para o rasa um payload em t0 (logo que a sessão do usuário é criada). Isso permite executar uma rule que inicie a conversa.  O Rasa X e o cmdline (canal que interage com o bot via terminal) não possuem essa opção, o que impede testar o acolhimento nesses canais.
2. Precisamos ter certeza que o Rocket.chat permite que a gente envie esse upload inicial, pois se não, a solução que proponho aqui terá que ser repensada.
3. É possível que exista uma forma alternativa de fazer isso, customizando a Action `session_start`. Essa action é chamada toda vez que uma conversa é iniciada, e talvez a gente consiga por ela, fazer o acolhimento, mas julgo que essa opção deve ser um plano B.
4. Tem uma outra possibilidade que seria ao invés de utilizar uma rule para disparar a utter de acolhimento, utilizar uma historia. Isso permitiria testar o acolhimento pelo Rasa X.

Eu estou subindo na branch um commit que permite subir um webchat via nginx. No webchat o acolhimento já funciona, pois é enviado um payload inicial para o rasa, que identifica como t0 e inicia a conversa com o texto de acolhimento. A @MarthaDs pode usar essa implementação para seguir com a issue, e no paralelo eu devo avaliar se o rocket.chat permite que a gente envie esse payload inicial. 

Minha ideia é que a gente teste o acolhimento inicialmente via webchat/rocket.chat, e em uma próxima issue a gente avalia essa troca de uma rule por uma história, para o acolhimento funcionar também no rasa x.

![image](https://user-images.githubusercontent.com/2847027/109840843-41890680-7c27-11eb-943c-0002d942e9e7.png)

**Comment by fabiolamfleury** [comment]
> Criei um doc com modelo de conversa para o acolhimento que pode ser encontrado [aqui](https://docs.google.com/document/d/1XXzpzB6ZQNdAS7HlvySUL_od6iYx6DD84abGMA3QCDY/edit)

Eu não consigo criar comentário no documento, mas testando a implementação que já está disponível até então, achei uma possível melhoria. 

Na parte de pergunta do email tem a pergunta:

'Você se importa de me passar seu email?'

Acho estranho a pessoa ter que responder com uma negativa caso ela queira utilizar o email, e quando eu respondi que não ele se perdeu na conversa. acho que como tava antes, 'Você gostaria de se identificar pelo seu email? se sim já pode enviar' ou algo nesse sentido (que também deixa tudo em uma só etapa) acho q fica mais fácil de entender.

**Comment by davidCarlos** [comment]
Correções locais a partir da branch **reaching-user-issue-222**

- A api do rasa não recarrega as models automaticamente, ou seja, se rodar um `make train`, é necessário parar o container da api, e subi-lo novamente via `make run-api`.
- Havia dois textos de resposta para a utter `welcome`, não entendi porquê, então removi, dixando apenas um text
- Nem o comando `make run-x` nem `make run-api`, subiam o serviço do duckling, necessário para extrair informações durante a conversa com o usuário.;
- O comando `docker-compose run`, ignora a regra `container_name`, definida no yml. Tive que alterar todos os comandos no Makefile, e incluir a flag `--name`. Me parece que o comando `docker-compose up` preserva a regra.
- Variável de ambiente que aponta qual o servidor do duckling não estava definida no container do bot;
- Me parece que quando executamos o comando `docker-compose run`, o docker ignora a regra `env_file`, isso quebrava o serviço de actions, que não conseguia se conectar na EJ.
- Apontei as custom_actions para uma conversa em homologação, para não dependermos da EJ rodando local;
- **Eu comentei todas as histórias e mantive apenas uma história, com o caminho feliz (acolhimento + form + PARAR + mensagem de agradecimento)**

![image](https://user-images.githubusercontent.com/2847027/111231915-d47f5480-85c8-11eb-92f3-33a5733f3d50.png)
![image](https://user-images.githubusercontent.com/2847027/111231943-de08bc80-85c8-11eb-847a-d6fa5e5fc305.png)
![image](https://user-images.githubusercontent.com/2847027/111231955-e52fca80-85c8-11eb-8d8d-77f0470330f4.png)
![image](https://user-images.githubusercontent.com/2847027/111231968-ebbe4200-85c8-11eb-86fa-282b62a22341.png)

Com o caminho feliz, temos uma base mais sólida para derivar os outros cenários envolvendo acolhimento. Eu não cheguei a testar nada envolvendo o Rasa X.

**Pendencias**

- [ ]  documentar que o usuário precisa editar o arquivo **env/auth.env** para apontar para uma instância válida da EJ.
- [ ] Rever Makefile. Se formos usar `docker-compose run`, vamos precisar mover todas as variáveis de ambiente para dentro do docker-compose.yml. Pela olhada que eu dei me parece ser este o comportamento padrão do docker (ignorar o env_file), se for (vale tentar replicar esse comportamento), vamos ter que mexer no Makefile (ou no docker-compose.yml);
- [ ] Um outro problema do `docker-compose run`, é que ele ignora a regra `container_name`.

**Comment by MarthaDs** [comment]
> Correções locais a partir da branch **reaching-user-issue-222**
> 
> * A api do rasa não recarrega as models automaticamente, ou seja, se rodar um `make train`, é necessário parar o container da api, e subi-lo novamente via `make run-api`.
> * Havia dois textos de resposta para a utter `welcome`, não entendi porquê, então removi, dixando apenas um text
> * Nem o comando `make run-x` nem `make run-api`, subiam o serviço do duckling, necessário para extrair informações durante a conversa com o usuário.;
> * O comando `docker-compose run`, ignora a regra `container_name`, definida no yml. Tive que alterar todos os comandos no Makefile, e incluir a flag `--name`. Me parece que o comando `docker-compose up` preserva a regra.
> * Variável de ambiente que aponta qual o servidor do duckling não estava definida no container do bot;
> * Me parece que quando executamos o comando `docker-compose run`, o docker ignora a regra `env_file`, isso quebrava o serviço de actions, que não conseguia se conectar na EJ.
> * Apontei as custom_actions para uma conversa em homologação, para não dependermos da EJ rodando local;
> * **Eu comentei todas as histórias e mantive apenas uma história, com o caminho feliz (acolhimento + form + PARAR + mensagem de agradecimento)**
> 
> ![image](https://user-images.githubusercontent.com/2847027/111231915-d47f5480-85c8-11eb-92f3-33a5733f3d50.png)
> ![image](https://user-images.githubusercontent.com/2847027/111231943-de08bc80-85c8-11eb-847a-d6fa5e5fc305.png)
> ![image](https://user-images.githubusercontent.com/2847027/111231955-e52fca80-85c8-11eb-8d8d-77f0470330f4.png)
> ![image](https://user-images.githubusercontent.com/2847027/111231968-ebbe4200-85c8-11eb-86fa-282b62a22341.png)
> 
> Com o caminho feliz, temos uma base mais sólida para derivar os outros cenários envolvendo acolhimento. Eu não cheguei a testar nada envolvendo o Rasa X.
> 
> **Pendencias**
> 
> * [ ]   documentar que o usuário precisa editar o arquivo **env/auth.env** para apontar para uma instância válida da EJ.
> * [ ]  Rever Makefile. Se formos usar `docker-compose run`, vamos precisar mover todas as variáveis de ambiente para dentro do docker-compose.yml. Pela olhada que eu dei me parece ser este o comportamento padrão do docker (ignorar o env_file), se for (vale tentar replicar esse comportamento), vamos ter que mexer no Makefile (ou no docker-compose.yml);
> * [ ]  Um outro problema do `docker-compose run`, é que ele ignora a regra `container_name`.
> 
> @fabiolamfleury @MarthaDs

Havia dois textos para tornar a Duda menos repetitiva, então ela pode ter varias msg de "olá"

Sobre comando `docker-compose run` vc fala de usar ele para subir o que exatamente?

**Comment by davidCarlos** [comment]
Da uma olhada no Makefile.  A maioria dos comandos utiiza `docker-compose run`

**Comment by MarthaDs** [comment]
> Da uma olhada no Makefile. A maioria dos comandos utiiza `docker-compose run`

@fabiolamfleury vc acha que se modificar esse comando a gnt consegue rodar a Duda sem precisar rodar as actions e duckling num terminal a parte ?

**Comment by davidCarlos** [comment]
Isso já não é necessário @MarthaDs. O `make run-api`  já sobe o duckling e as actions.

**Comment by fabiolamfleury** [comment]
@davidCarlos dei uma olhada na branch e tentei subir aqui, mas não tá dando mt certo. O bot qnd chega na parte que pergunta o email para, acho q não ta conseguindo fazer a requisição pro ej. Como a actions não tá dando pra ver o terminal, fica um pouco mais dificil de debugar

**Comment by davidCarlos** [comment]
Da pra ver o log da action, basta ver o log do container `docker logs -f actions`

Quanto a não estar funcionando, recomendo matar todos os serviços e subir do zero, esse erro normalmente acontece pq a variável de ambiente EJ_HOST não foi setada no container.

**Comment by fabiolamfleury** [comment]
> Da pra ver o log da action pelo log do container `docker logs -f actions`
> 
> Quanto a não estar funcionando, recomendo matar todos os serviços e subir do zero, esse erro normalmente acontece pq a variável de ambiente EJ_HOST não foi setada no container actions

Opa, na realidade tá parecendo que o bot não tá se comunicando com as actions, elas não tão recebendo nenhuma requisição. Eu dei um clean geral na minha máquina, limpei todos volumes, imagens, redes etc, mas o problema tá rolando

**Comment by davidCarlos** [comment]
vou rodar do zero aqui do meu lado também.

**Comment by davidCarlos** [comment]
@fabiolamfleury removi todos os containers aqui e subi de novo. Os passos que eu fiz:

1. docker-compose stop
2. docker-compose rm
3. make train
4. make run-api
5. make run-webchat

O container do ej-bot está com as seguintes variáveis de ambiente:
![image](https://user-images.githubusercontent.com/2847027/111331345-9416e980-864f-11eb-8dba-2fb0cefd653a.png)

O container do actions está com as seguintes variáveis de ambiente:
![image](https://user-images.githubusercontent.com/2847027/111331490-b4df3f00-864f-11eb-8d64-9e705c9d27da.png)

**Comment by davidCarlos** [comment]
**story: Activate vote form with user email**

![image](https://user-images.githubusercontent.com/2847027/112165778-cedbcd00-8bcd-11eb-89dc-20776049e01d.png)

**Primeiro problema**: Notem que depois da `utter_send_email`, tem uma intent `agree` e só depois a `email`. Ou seja, o usuário tem que responder sim, e depois mandar o email. Isso pra um desavisado vai quebrar o fluxo. Subi uma correção pra isso.

![image](https://user-images.githubusercontent.com/2847027/112177183-7a3d4f80-8bd7-11eb-823f-41e4a89aeb08.png)

**Segundo problema**: Em algum momento o bot começou a enviar mensagens repetidas. Não consegui reproduzir depois que remove a utter de agree.

@fabiolamfleury tenta rodar o meu ultimo commit por favor, e testa o fluxo da historia desse comentário. Vamos tentar validar história por história.

**Comment by fabiolamfleury** [comment]
@davidCarlos rodei aqui e testei todos os fluxos, parece estar tudo ok, testei tanto com o parar quanto sem.

**Comment by davidCarlos** [comment]
Perfeito. @fabiolamfleury pode mergrir esse MR então, e aí testamos direto lá no ambiente de homologação. Qualquer problema podemos abrir outras issues de correção.
