### ISSUE TITLE
Verificar possível bug na autenticação via mautic no componente de coleta

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#223]
mesmo com a autenticação via mautic ativada e o plugin configurado,  o componente segue caindo na autenticação por registro.

**Comment by ricardopoppi** [comment]
@davidCarlos qual a última versão do componente que está valendo?

**Comment by davidCarlos** [comment]
A ultima versão publicada do componente você vai encontrar na área de ferramentas de uma conversa, clicando na ferramenta `Componente de coleta`. Lá dentro vai aparecer a ultima versão do componente publicada no npm.
A ultima versão publicada é a `1.7.15`

**Comment by ricardopoppi** [comment]
> A ultima versão publicada do componente você vai encontrar na área de ferramentas de uma conversa (na ej), clicando na ferramenta `Componente de coleta`. Lá dentro vai aparecer a ultima versão do componente publicada no npm.
> A ultima versão publicada é a `1.7.15`

Uau! Muito bom, sensacional que lá já atualiza direto. Obrigado!

**Comment by davidCarlos** [comment]
Tá previsto nessa sprint evoluir essa pagina, mas a ideia é que essas infos/instruções apareçam sempre lá.

**Comment by ricardopoppi** [comment]
Teste No site do ICD:
================

Header do site:

```
<!-- EJ Platform -->
		<script src='https://unpkg.com/ej-conversations@1.7.15/dist/conversations.js'></script>
		<style>
		/* https://github.com/ionic-team/stencil/issues/2072 */
@font-face {
  font-family: Folio;
  font-style: normal;
  font-weight: 400;
  font-display: auto;
  src: url(https://unpkg.com/ej-conversations@1.7.15/dist/conversations/assets/fonts/folio_bold_condensed.ttf);
}

@font-face {
  font-family: Helvetica;
  font-style: normal;
  font-weight: 400;
  font-display: auto;
	src: url('https://unpkg.com/ej-conversations@1.7.15/dist/conversations/assets/fonts/helvetica_neue_lts_roman.otf');
}

@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 400;
  font-display: auto;
	src: url('https://unpkg.com/ej-conversations@1.7.15/dist/conversations/assets/fonts/fa-regular-400.ttf');
}

@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 400;
  font-display: auto;
	src: url('https://unpkg.com/ej-conversations@1.7.15/dist/conversations/assets/fonts/fa-brands-400.ttf');
}

@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 400;
  font-display: auto;
	src: url('https://unpkg.com/ej-conversations@1.7.15/dist/conversations/assets/fonts/fa-solid-900.ttf');
}

</style>
<!-- End of EJ Platform -->
```

Conversa apontada em prod:
`<ej-conversation host=https://www.ejparticipe.org cid="66" theme="icd" authenticate-with="mautic"></ej-conversation>`


Teste na página: https://cidadedemocratica.org.br/ej2/ modo de autenticação mautic, plugin do wordpress apontado para o https://contatos.ejparticipe.org/

Resultado:

Board ok

![Captura de tela de 2021-03-03 21-09-56](https://user-images.githubusercontent.com/1162183/109889925-13c2b280-7c65-11eb-86af-a6421f5e5f05.png)


Após o board, fallback no registro EJ.

Script do mautic carrega (mtc.js)
ESTRANHO a carga de uma logo num domínio em homologação: ejplatform.pencillabs.com.br
Mesmo tentando fazer o registro manualmente, o botão "Participar" não funciona. Console do inspector apresenta o seguinte erro:
```
4p-josoyxcj.entry.js:1 Uncaught (in promise) Error: could not authenticate user
    at h.authenticate (p-josoyxcj.entry.js:1)
    at l.registerHandler (p-josoyxcj.entry.js:1)
    at HTMLElement.onUserRegisteredOnEJ (p-josoyxcj.entry.js:1)
    at Object.emit (p-dadc9583.js:1)
    at v.registerUser (p-josoyxcj.entry.js:1)
```

![Captura de tela de 2021-03-03 21-10-49](https://user-images.githubusercontent.com/1162183/109890231-b11de680-7c65-11eb-961c-3705d45477d4.png)
![Captura de tela de 2021-03-03 21-16-12](https://user-images.githubusercontent.com/1162183/109890240-b67b3100-7c65-11eb-8a69-531cea3dfb3b.png)

**Comment by ricardopoppi** [comment]
Teste no site do Agentes da Cidadania
=============================

Header do site:

```
		<script src='https://unpkg.com/ej-conversations@1.7.15/dist/conversations.js'></script>
		<style>
		/* https://github.com/ionic-team/stencil/issues/2072 */
		@font-face {
  			font-family: Folio;
  			font-style: normal;
  			font-weight: 400;
  			src: url('https://unpkg.com/ej-conversations@1.7.15/dist/conversations/assets/fonts/folio_bold_condensed.ttf');
		}

		@font-face {
  			font-family: Helvetica;
  			font-style: normal;
  			font-weight: 400;
  			src: url('https://unpkg.com/ej-conversations@1.7.15/dist/conversations/assets/fonts/helvetica_neue_lts_roman.otf');
		}
		</style>
```

Conversa apontada em prod:
`<ej-conversation host=https://www.ejparticipe.org cid="66" theme="icd" authenticate-with="mautic"></ej-conversation>`

Teste na página: https://agentesdacidadania.org.br/frutos-do-esporte/ modo de autenticação mautic, plugin do mautic no wordpress apontado para o https://contatos.ejparticipe.org/

Resultado:

Componente nem carrega e inspector apresenta o erro:

```
p-josoyxcj.entry.js:1 Uncaught (in promise) Error: could not authenticate user
    at h.authenticate (p-josoyxcj.entry.js:1)
    at l.componentWillLoad (p-josoyxcj.entry.js:1)
    at J (p-dadc9583.js:1)
    at V (p-dadc9583.js:1)
    at r (p-dadc9583.js:1)
    at p-dadc9583.js:1
```

![Captura de tela de 2021-03-03 21-25-59](https://user-images.githubusercontent.com/1162183/109891009-11615800-7c67-11eb-85f8-602f5b3aa77d.png)

**Comment by ricardopoppi** [comment]
Teste No site do ICD (agora com modo auth analytics):

Mesmo header

Mesma conversa em prod: 
`<ej-conversation host=https://www.ejparticipe.org cid="66" theme="icd" authenticate-with="analytics"></ej-conversation>`

Resultado:

**Comment by ricardopoppi** [comment]
Teste no site do agentes (agora com modo auth analytics):
============================================

Conversa apontada em prod:
<ej-conversation host=https://www.ejparticipe.org cid="66" theme="icd" authenticate-with="analytics"></ej-conversation>

Teste na página: https://agentesdacidadania.org.br/frutos-do-esporte/

Resultado:

Autenticou sem necessidade do fallback:

![Captura de tela de 2021-03-03 23-00-37](https://user-images.githubusercontent.com/1162183/109899366-838c6980-7c74-11eb-90b8-0dd61783cfe1.png)

**Comment by ricardopoppi** [comment]
Resumo:

- Autenticação via mautic não funcionou em nenhum dos dois sites;
- Autenticação via analytics funcionou apenas no site do agentes.

**Comment by davidCarlos** [comment]
Avaliação que fiz aqui do bug de autenticação.

## Correções no Mautic

Algumas correções no ambiente foram feitas:

- Alteração nas configurações do sistema. Alterei o nome do site de http://contato para https://contato
- Desabilitei a restrição de domínios (cors)
- Habilitei a opção `track_private_ip_ranges` (limitação com o swarm).

Com essas alterações o script de tracking do mautic conseguiu gerar o cookie no browser.

## Testes no Firefox

- Autenticação com o mautic no firefox **não está funcionando**. Por algum motivo o script do mautic não consegue criar um usuário.
![image](https://user-images.githubusercontent.com/2847027/110036584-01578000-7d1c-11eb-9797-041550447707.png)
![image](https://user-images.githubusercontent.com/2847027/110036635-13392300-7d1c-11eb-9280-561294b5641a.png)

Isso gerava um outro problema, que era a não ativação do fallback para login via registro. Isso foi corrigido, e agora caso o cookie não exista no browser, o componente trata o erro e apresenta a tela de registro.

- Autenticação com o analytics funcionando corretamente.
- Autenticação via registro funcionando corretamente.

## Testes no Chrome

- Autenticação com o mautic no chrome funciona corretamente. Usuário está sendo criado no mautic e o `mtc_id` está sendo registrado no browser.
![image](https://user-images.githubusercontent.com/2847027/110037533-4d56f480-7d1d-11eb-8cfd-1ef069473ed7.png)
![image](https://user-images.githubusercontent.com/2847027/110037563-5d6ed400-7d1d-11eb-819f-b8c847f5af9c.png)
![image](https://user-images.githubusercontent.com/2847027/110037631-71b2d100-7d1d-11eb-8140-43c4cc0fd681.png)

Todos os testes foram feitos em ambiente local, em uma pagina html limpa, apenas com o componente incluído.

Publiquei uma nova versão (`1.7.16-beta1`) do componente com algumas correções. Vale refazer os testes tando no site do agentes quanto do cidades.

Um ponto que vale colocar aqui, é que no firefox nenhum cookie está sendo criado nas paginas.
![image](https://user-images.githubusercontent.com/2847027/110040003-d9b6e680-7d20-11eb-9b96-56359d241ef9.png)
