### ISSUE TITLE
Como usuário, eu gostaria de acessar a pagina de configuração do componente de coleta, para ter instruções de como adicioná-lo ao meu site.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#224]
Na página interna do componente de coleta, na área de ferramentas, o usuário deve ser capaz de gerar o script para incluir o componente em seu site.

**Tarefas**

- [x] Fazer wireframe da tela para discutir com o time;
- [x] Adicionar formulário para gerar script do componente, permitindo configurar as opções de autenticação e tema.
- [x] Implementar estrutura da pagina a partir do wireframe construído;
- [x] Adicionar instruções para configuração das fontes, e aonde o script deve ser incluído;
- [x] Incluir botão que copie o snippet do código gerado para a área de transferência;
- [x] Incluir tooltip que avise ao usuário que o código foi copiado.
- [x] Incluir paleta de cores de cada tema, da mesma forma que aparece na tela de cadastro de board;
- [x] Apresentar opções de autenticação lado a lado;
- [x] Adicionar ícone de "?" ao lado de cada opção de autenticação, e no hover (ou click), mostrar texto de como a autenticação funciona;

**Critérios de aceitação**

- [x] O Script gerado pela EJ, deve permitir que o usuário inclua com sucesso o componente em seu site;

Wireframe: https://pencillabs.invisionapp.com/freehand/Tela-interna-de-integra--o-do-EJ-com-a-Duda-prI1elRkh

**Comment by davidCarlos** [comment]
Construção dos wireframes pode ser feita no https://projects.invisionapp.com

**Comment by fabiolamfleury** [comment]
Algumas dúvidas/confirmações de implementação,

Na **autenticação** as opções são:
- mautic
- analytics
- por registro

No **tema** as opções são?


São só essas duas coisas que devem ser colocadas pra gerar o script? Eles são passados pro componente da mesma forma que o cid, via prop?

Como o @davidCarlos sugeriu, utilizei a estrutura do wireframe da issue #228 gerando o seguinte resultado:

![Tela interna de integração do EJ com a Duda](https://user-images.githubusercontent.com/20935369/110155332-3c14f300-7dc4-11eb-97b3-d2ad7ab7f07b.png)

**Comment by davidCarlos** [comment]
> Algumas dúvidas/confirmações de implementação,
> 
> Na **autenticação** as opções são:
> 
>     * mautic
> 
>     * analytics
> 
>     * por registro
> 
> 
> No **tema** as opções são?

se eu não me engano as opções de tema são icd, votorantim e vazio (tema padrão)
> 
> São só essas duas coisas que devem ser colocadas pra gerar o script? Eles são passados pro componente da mesma forma que o cid, via prop?
> 
Isso, tudo via prop.

> Como o @davidCarlos sugeriu, utilizei a estrutura do wireframe da issue #228 gerando o seguinte resultado:
> 
> ![Tela interna da ferramenta de componente de coleta](https://user-images.githubusercontent.com/20935369/110156152-5e5b4080-7dc5-11eb-8b86-7bf696fbbf6f.png)

Vale incluir no snippet os font-faces, para o correto carregamento das fontes que o componente depende.
```

<style>
		/* https://github.com/ionic-team/stencil/issues/2072 */
@font-face {
  font-family: Folio;
  font-style: normal;
  font-weight: 400;
  font-display: auto;
  src: url(https://unpkg.com/ej-conversations@1.7.15/dist/conversations/assets/fonts/folio_bold_condensed.ttf);
}

@font-face {
  font-family: Helvetica;
  font-style: normal;
  font-weight: 400;
  font-display: auto;
	src: url('https://unpkg.com/ej-conversations@1.7.15/dist/conversations/assets/fonts/helvetica_neue_lts_roman.otf');
}

@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 400;
  font-display: auto;
	src: url('https://unpkg.com/ej-conversations@1.7.15/dist/conversations/assets/fonts/fa-regular-400.ttf');
}

@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 400;
  font-display: auto;
	src: url('https://unpkg.com/ej-conversations@1.7.15/dist/conversations/assets/fonts/fa-brands-400.ttf');
}

@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 400;
  font-display: auto;
	src: url('https://unpkg.com/ej-conversations@1.7.15/dist/conversations/assets/fonts/fa-solid-900.ttf');
}

</style>
```
Pra facilitar a usabilidade, vale também colocar um botão que copie o conteúdo do snippet automaticamente para a área de transferência. (Adicionei uma tarefa pra isso).

**Comment by fabiolamfleury** [comment]
- Fiz um form do django pra lidar com a geração do snippet com as props corretas, e com isso precisa de enviar uma requisição POST pra atualizar o código (mesmo estando na mesma página) acho que talvez comprometa um pouco a interação.

- Atualizei com os botões para copiar o código o wireframe (um botão pra o header e outro pro body) e acabou que com o trecho do fontfaces a página ficou com uma barra de rolagem extensa

![image](https://user-images.githubusercontent.com/20935369/110395113-5b25b600-804c-11eb-9a56-ac376bcdcc20.png)

**Comment by fabiolamfleury** [comment]
Pra ficar mais parecido com o wireframe e melhorar um pouco em questão de interação, fiz mudanças na interface que agora se encontra assim:

![image](https://user-images.githubusercontent.com/20935369/110518962-90351580-80eb-11eb-87b9-3891796d7b7c.png)

**Comment by fabiolamfleury** [comment]
@davidCarlos quais são as cores dos temas? eu só to familiarizada com o default, peguei ai pelo wireframe e queria validar (padrão, votorantim e icd respectivamente)
![Sem título](https://user-images.githubusercontent.com/20935369/110648239-4c97e580-8197-11eb-8620-111bfc9e082f.png)

**Comment by davidCarlos** [comment]
Votorantim
![image](https://user-images.githubusercontent.com/2847027/110665281-f632a300-81a6-11eb-8b90-ce150b220842.png)
![image](https://user-images.githubusercontent.com/2847027/110665209-e2873c80-81a6-11eb-9ca9-66c2a0bcc5e4.png)

Padrão
![image](https://user-images.githubusercontent.com/2847027/110665448-267a4180-81a7-11eb-9e05-f58fd074b1fe.png)
![image](https://user-images.githubusercontent.com/2847027/110665402-18c4bc00-81a7-11eb-92c0-383ec6fefb76.png)

ICD
![image](https://user-images.githubusercontent.com/2847027/110665753-6e00cd80-81a7-11eb-970a-4b3128027efc.png)
![image](https://user-images.githubusercontent.com/2847027/110665694-5cb7c100-81a7-11eb-90a9-9234b623cffc.png)

**Comment by fabiolamfleury** [comment]
Abri o MR: https://gitlab.com/pencillabs/ej/ej-server/-/merge_requests/21

Conversei com o @davidCarlos e faltou só testar a questão do aparecimento das paletas, que acredito que não tá rolando no meu pc por questões de cache, de qualquer forma eu vou mapear esse problema pra uma nova issue
