### ISSUE TITLE
Como administrador, quero configurar a integração do ej-bot com o ej, para puxar corretamente as conversas para os usuários participarem

### ISSUE THREAD

**Issue by fabiolamfleury** [cidadedemocratica/ej-server#228]
Na página de integrações do ej, deve aparecer o rasa, e devem haver configurações internas para seleção de conversas de acordo com a instância do rasa.

**Tarefas**

- [x] Fazer wireframe da tela interna da integração rasa - ej para discutir com o time;
- [x] Criar no EJ model para persistir os dados (url do bot e id da conversa);
- [x] Adicionar formulário para entrada do endereço (url) e a conversa que vai ser disponibilizada nele.
- [x] Implementar estrutura da pagina a partir do wireframe construído;

**Critérios de aceitação**

- [x] É possível adicionar uma integração, de uma única conversa para um único endereço de bot;

**Comment by fabiolamfleury** [comment]
O wireframe pode ser acessado pelo time em: https://pencillabs.invisionapp.com/freehand/Tela-interna-de-integra--o-do-EJ-com-a-Duda-prI1elRkh

**Comment by fabiolamfleury** [comment]
Eu tinha ficado um pouco confusa realmente de como seria a área de ferramentas nessas diferentes abstrações, mas parece que a solução de existir essa área para o board facilitaria, a depender do contexto.

Deixei suas anotações no invision para rastreamento/evolução, mas já atualizei de acordo com elas:

![Tela interna de integração do EJ com a Duda](https://user-images.githubusercontent.com/20935369/110034147-e3d4e700-7d18-11eb-8c63-e0b7a7e53d04.png)

**Comment by ricardopoppi** [comment]
Massa gente.

Sobre essa discussão board x conversas, com a entrada do componente, que é o nosso carro-chefe web da EJ, o board serve para os administradores organizarem conversas.

Minha sugestão é avaliarem dois cenários:

Cenário 1: Ferramentas é recurso do board. Nesse caso, o snipet teria que permitir a escolha da conversa específica ou por default de qq conversa do board, elegida de forma aleatória, a princípio.

Cenário 2: Board apenas organiza para o administrador. Nesse caso, o board não tem rota de ferramentas. E o agrupamento de conversas aconteceria através das tags.

Eu acho o cenário 2 ruim, pois o administrador não consegue prever qdo uma conversa será criada por outro usuário admin da EJ usando a mesma tag, já que isso é possível. Eu prefiro o cenário 1.

Podemos pensar o cenário 1 em fases. Na primeira fase o board não tem rotas, e aí qdo implementarmos a possibilidade do pool de conversas, fazemos isso através do board e não das tags. Eu acho que esse plano seria mais apropriado considerando a forma com a EJ foi apropriada na prática ;-)

**Comment by davidCarlos** [comment]
A princípio vamos trabalhar com uma área de ferramentas por conversa, até porquê a experiência muda bastante pro cenário do board, por exemplo, como vamos fazer pra configurar um componente para cada conversa do board? É outra experiência de usuário que a gente ainda não parou pra pensar como funcionaria.

Concordo com o Cenário 1, mas acho podemos amadurecer esse UX a partir do feedback do time fazendo uso da área de ferramentas nas conversas.
