### ISSUE TITLE
Eu como membro do time de marketing digital do demo.eco quero ter acesso ao kit campanha fase 1 para homologar

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#229]
- [x] Configurar multisite no WP
- [x] Adicionar plugin do Divi para criação das landing pages
- [ ] Configuração do SMTP do mautic
- [x] Correções no componente de coleta para correta integração com landings do WP

**Comment by davidCarlos** [comment]
@ricardopoppi não esquece de registrar aqui a lista de tarefas que vão compor o `kit campanha fase 1`

**Comment by ricardopoppi** [comment]
@davidCarlos validei aqui além do SMTP que é o que falta mesmo em termos de configuração o resto é montagem da operação (criação do focus, análise da aquisição dos leads no mautic, ativação do push etc) que não cabe nessa issue senão ela vai ficar presa no limbo.

**Comment by ricardopoppi** [comment]
então acho que podemos focar agora nesse final de sprint apenas no smtp

**Comment by davidCarlos** [comment]
Beleza. Você puxa isso?

**Comment by ricardopoppi** [comment]
Sim, essa tá comigo

**Comment by davidCarlos** [comment]
@ricardopoppi podemos fechar essa issue?

**Comment by davidCarlos** [comment]
Fechando essa issue devido ao fim da sprint. Caso necessário, podemos abrir uma nova issue específica para a configuração do SMTP.
