### ISSUE TITLE
Eu como usuário quero acessar um componente onde eu consiga ler os conteúdos nitidamente

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#230]
Nessa issue vou elencar pequenos bugs de CSS no componente:

- [x] Título da aba "COMENTÁRIOS" sobrepondo o título "GRUPOS" na versão responsiva (teste na página https://wp.ejparticipe.org/)

![photo_2021-03-04_12-00-24](https://user-images.githubusercontent.com/1162183/109983531-aa34b980-7ce1-11eb-84c4-2822157e8ad5.jpg)

**Comment by davidCarlos** [comment]
![image](https://user-images.githubusercontent.com/2847027/110661933-cd5cde80-81a3-11eb-8194-f785c2749d64.png)

Além do bug reportado, fiz algumas outras correções de responsividade:

- Nome dos clusters estava quebrando dentro da navbar
- Botão "Participar" ficava muito pequeno no mobile
- Botão "Participar" não alterar estilo do cursor quando o mouse estava por cima
- Footer da pagina não respeitava espaços destinado à apresentar os comentários dos clusters
- Melhorias visuais no componente de registro
![image](https://user-images.githubusercontent.com/2847027/110662270-1a40b500-81a4-11eb-8757-27d727d6fe39.png)

@ricardopoppi como hoje já é quarta-feira, peço que revise as correções (o componente já está atualizado tanto no https://wp.ejparticipe.org/ quanto no agentesdacidadania.org.br/). Vou fechar essa issue por hora, mas novos bugs críticos de UI/responsividade podem ser incluídos aqui até amanhã (sexta nossa sprint encerra).

**Comment by ricardopoppi** [comment]
@davidCarlos ficou muito bom com as novas melhorias. 

Para poder chavear o componente em wp.ejparticipe.org de volta para prod, preciso esperar o pipeline rodar em prod (se teve algum ajuste de api etc) ou já posso fazer isso?

**Comment by davidCarlos** [comment]
1. Na hora de editar o componente tinha ficado um erro de escrita (typo). Bom sempre dar uma revisada nisso;
2. Habilitando autenticação com o mautic/analytics funcionou corretamente no chrome (apontei para prod https://www.ejparticipe.org).
4. No Firefox o cookie do analytics não está sendo setado (fallback pro registro aparecendo como esperado);

**Comment by ricardopoppi** [comment]
eita obrigado!
