### ISSUE TITLE
ejBot não trata problema de comunicação com a API da EJ, e retorna uma mensagem para usuário como se ele tivesse votado em algum comentário (o que não é o caso).

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#233]
Quando a custom_action de comunicação com a EJ falha, a implementação não prevê esse caso de uso, e retorna uma mensagem incorreta pro usuário.

![image](https://user-images.githubusercontent.com/2847027/110382402-9ec2f480-8039-11eb-8407-aa2641fb437e.png)
![image](https://user-images.githubusercontent.com/2847027/110382432-ac787a00-8039-11eb-809b-28f653b11dd7.png)

**Informações adicionais**

- custom_actions apontando para EJ de produção (https://ejplatform.org)
- Rasa rodando via `pencilctl deploy rasa`, a partir de uma imagem construída da branch `master`

**Tarefas**

- [x] Tratar erro de comunicação com a EJ
- [x] Adicionar response que avise ao usuário houve um problema técnico, e não foi possível apresentar o que está sendo discutido na conversa.

**Comment by fabiolamfleury** [comment]
Vi que esse problema tava afetando o andamento da issue #222 e puxei pra fazer essa agora, falta só escrever os testes e abrir um MR

**Comment by davidCarlos** [comment]
@fabiolamfleury como tá o andamento dessa issue aqui? Lembro que você tinha dito que já tava +- pronta né?

**Comment by fabiolamfleury** [comment]
Oi David, ela ta pronta, só que eu criei a branch a partir da branch da Martha do acolhimento, então tava esperando abrir o MR dela pra depois ser dessa, já que também já ta pronto
