### ISSUE TITLE
Como desenvolvedor, eu gostaria de acessar a documentação sobre como integrar o componente de coleta ao meu site

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#236]
**Tarefas**

- [x] Adicionar aviso na área da ferramenta, informando que pode ser necessário fazer algumas correções no css do site em que o componente será incluído, para que os elementos visuais fiquem corretamente alinhados;
- [x] Adiciona pagina no /docs da EJ, que documente detalhes de uso do componente, com prints de tela e instruções de css.

**Comment by davidCarlos** [comment]
Nota pra review: Adicionar pagina na documentação da EJ para listar possíveis correções do lado do site em que o componente será incluído. Referenciar essa documentação na tela da ferramenta.

**Comment by fabiolamfleury** [comment]
Resolvido em: https://gitlab.com/pencillabs/ej/ej-server/-/merge_requests/25
