### ISSUE TITLE
Testar se opção "Gatilhos de Livechat", na área administrativa do omnichannel (rocketchat),  permitem disparar o fluxo acolhimento no Rasa.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#238]
Já sabemos como disparar o acolhimento via webchat criado com o projeto rasa-webchat. Agora precisamos verificar se o webchat do Rocket.chat também permite esse disparo. 

![image](https://user-images.githubusercontent.com/2847027/110812860-b9c67c00-8266-11eb-9b47-3880c2aef056.png)

Tarefas

- [x] Avaliar se cadastrando um gatilho, é possível disparar o acolhimento

depende da issue #222

**Comment by MarthaDs** [comment]
A respeito dessa issue algumas questões devem ser pontuadas.

**Comment by MarthaDs** [comment]
## Teste realizados hj :
  
- TriggerTeste - Ele faz envia uma mensagem de welcome via rocketchat para chat como um agente personalizado, ou seja sem bot:

![Screenshot from 2021-03-25 20-56-51](https://user-images.githubusercontent.com/12221656/112558078-b37ae880-8dac-11eb-9874-834c41e150ec.png)
![Screenshot from 2021-03-25 20-59-51](https://user-images.githubusercontent.com/12221656/112558253-140a2580-8dad-11eb-88a7-f4cd20478e72.png)

- Trigger com o bot como agente - Nesse caso tentamos colocar apenas o bot como agente na fila  o que em teoria faria ele responder o usuário, mas não ocorreu:

![Screenshot from 2021-03-25 21-03-47](https://user-images.githubusercontent.com/12221656/112558525-ba562b00-8dad-11eb-9478-14fb248401cb.png)
![Screenshot from 2021-03-25 21-04-31](https://user-images.githubusercontent.com/12221656/112558531-bfb37580-8dad-11eb-9724-a83eb60fa86e.png)

obs: Nesse teste foi usado o caminho encontrado no script criado pelo proprío rocketchat para utilização de livechat.

-  Foi testado também se a criação de um livechat trigger seria enviado alguma msg no canal `rasa_talks` e em um canal privado apenas com o bot. Ambos não resultaram em nenhuma mudança no comportamento atual do bot. 

Nosso entendimento atual é de que: 

1. livechat trigger não resultam em mudanças no canal criado
2. livechat trigger enviam mensagens para o usuário e não para agentes(o bot eh um agente)
3. A integração feita com o ejBot talvez não tenha coberto livechats 
4. Segundo a resposta nessa [issue](https://github.com/RocketChat/Rocket.Chat/issues/19362) talvez seja preciso a utlização dessa [ferramenta auxiliar](https://github.com/RocketChat/Apps.Rasa) para que o bot possa responder em livechats. 
5. O fluxo seguido no rocketchat é de inserir bot e usuário na conversa então talvez seja possível ativar o fluxo de acolhimento do bot  através do metodo documentado [aqui](https://docs.rocket.chat/api/rest-api/methods/chat/sendmessage)
obs.: O link do rocketchat api está fora do ar mas de tarde funcionava então pode ser algo temporário. No pior dos casos é uma funcionalidade descontinuada, descartando essa solução.

**Comment by MarthaDs** [comment]
Eu esqueci de mencionar que a priori do jeito que está agora o bot vai responder quando chamado apenas. (Existe um espaço na configuração dele para colocar palavras que fazem ele iniciar)
-> Palavra de Gatilho
![image](https://user-images.githubusercontent.com/12221656/112560364-cfcd5400-8db1-11eb-9853-357e6067098e.png)

**Comment by davidCarlos** [comment]
Consegui fazer o livechat funcionar. Seguindo as investigações que vocês fizeram, alterei alguns detalhes e consegui conversar com a Duda pelo livechat do Rocket.

1. Mudei a opção do trigger para "Tempo do visitante na pagina", ao invés de "Url da pagina de visitante".Dessa forma a mensagem de acolhimento definida no trigger foi enviada;

![image](https://user-images.githubusercontent.com/2847027/112654966-b3bbc800-8e2e-11eb-9482-52dd6a42907d.png)

2. O livechat não gera um canal novo, ele gera um "bate papo". Mas assim como nos canais, um bate papo também pode ter um webhook configurado, e foi isso que eu fiz. Configurei um webhook para que toda vez que um visitante mandar uma mensagem no livechat, o rocket envie a mensagem para o rasa.

![image](https://user-images.githubusercontent.com/2847027/112657166-e5359300-8e30-11eb-96ab-2c5e7d8a8e5e.png)
![image](https://user-images.githubusercontent.com/2847027/112657203-f2528200-8e30-11eb-8c7c-f804e1f10f67.png)

**Comment by davidCarlos** [comment]
Uma questão que temos que incluir nas mensagens de acolhimento. No livechat, não aparecem os botões para voto, então o usuário não sabe o que fazer logo após receber um comentário. Essa é uma boa oportunidade pra gente evoluir o modelo, e o usuário pode responder outras coisas além de "concordar", "discordar", e "pular". 

![image](https://user-images.githubusercontent.com/2847027/112658283-077be080-8e32-11eb-9900-1153e31d2b65.png)

**Comment by davidCarlos** [comment]
Uma simples mudança na resposta, já confunde o bot. Acho que aqui ele entendeu que "eu discordo", significa "pular".

![image](https://user-images.githubusercontent.com/2847027/112659421-1f079900-8e33-11eb-8902-d7b9e24205a4.png)

**Comment by fabiolamfleury** [comment]
> ele entendeu que "eu discordo"

Atualmente na validação do voto ele está vendo se o voto foi: 'Concordar', 'Discordar', 'Pular' ou 'PARAR', acho que realmente é o momento de fazermos a evolução pra ele avaliar de fato intents. Existe também a possibilidade de fazer 'botões' por meio de números, já vi quando utilizei bots no telegram e no whatsapp, do tipo 1- Concordo 2- Discordo 3- Pular. Mas dessa forma ainda ficaria muito engessado mesmo

**Comment by davidCarlos** [comment]
Eu acho que a opção de ter os botões resolve o problema, e podemos iniciar por esse caminho. Em paralelo podemos ir evoluindo o modelo pra ter um formato mais aberto de resposta. Meu feeling é que isso vai ser bem trabalhoso, porquê a gente vai ter que traduzir uma resposta mais aberta para o que a EJ entende (1, -1, 0).

**Comment by fabiolamfleury** [comment]
Como a issue #247 foi aberta, acredito que podemos colocar essa discussão lá, e essa issue pode ser fechada, dei uma revisada no que o @davidCarlos fez e tá tudo funcionando ok. Vi pelo MR da issue #242 que já tem instruções de como conectar o rasa ao rocket, mas não ao livechat, talvez seria legal adicionar essas prints e instruções lá na documentação, pra não 'perdermos' essa informação ficando só nessa issue, posso fazer isso inclusive, ou mapear pra outra issue.
