### ISSUE TITLE
Revisar fluxo das histórias via RasaX. Revisar processo de treinamento das models.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#240]
**Tarefas**

- [x] Verificar a geração de models via rasa x, se atualiza o bot (de preferencia limpar todas as models e depois treinar via Rasa X)
- [x] Passar no fluxo de cada história, para verificar se o funcionamento está compatível com o visto em outras plataformas
- [x] Tentar realizar alterações de fluxos para ver se elas são realmente persistidas ao gerar uma nova model, e se elas aparecem no arquivo stories.yml

**Comment by MarthaDs** [comment]
### Inconsistencias encontradas 

1. Ao rodar o train via rasaX interface ele cria duas models
2. A existência de mais de uma model faz o resultado de predição ficar inconsistente. Onde cada uma das models existente gera um resultado diferente mesmo sendo models criadas sobre mesmo codigo. 
3. Apesar do rasaX criar duas models apenas uma aparece na interface 

![Screenshot from 2021-03-26 15-21-52](https://user-images.githubusercontent.com/12221656/112684686-238f7a00-8e52-11eb-89aa-3ca9daaf29c5.png)

4.  Quando há apenas uma model independente se criada via rasaX ou via comando `make train` o resultado apresentado é o mesmo.
Resultado: Emails validos são considerados validos, mas a priori o usuário parece ser criado sem email. O comando PARAR resulta na saída do forms e em seguida default_callback que resulta em bot ouvir em vez de dar tchau. 

![Screenshot from 2021-03-26 15-00-57](https://user-images.githubusercontent.com/12221656/112685777-d0b6c200-8e53-11eb-9d39-fc82b3fa2504.png)

![Screenshot from 2021-03-26 15-01-28](https://user-images.githubusercontent.com/12221656/112685051-c1834480-8e52-11eb-9e9b-53ebbf6020c8.png)

5. Para que uma model criada pelo comando `make train` seja mostrada no rasaX interface é necessário subir novamente ele.
6.  Como o rasaX cria duas models ao subir novamente o rasaX aparece duas model.
 
![Screenshot from 2021-03-26 15-02-31](https://user-images.githubusercontent.com/12221656/112685902-f93ebc00-8e53-11eb-8227-3ffc2837a219.png)

7. Também foram encontradas outras inconsistências no ambiente da @fabiolamfleury.
Resultado: Independente da forma utilizada para criar a model e a existência de apenas uma model não foi apresentado em nenhuma conversa o forms de votação.
![image (1)](https://user-images.githubusercontent.com/12221656/112686001-1a9fa800-8e54-11eb-91d8-9b40f691fcd5.png)

Posterior aos testes a @fabiolamfleury relatou ter conseguido fazer o forms aparecer mas o comando PARAR ainda apresentou problemas.

Todos os testes foram realizados em uma [branch](https://gitlab.com/pencillabs/ej/ej-bot/-/tree/review-rasa-x-issue-240) a parte criado hj a partir da master.

**Comment by MarthaDs** [comment]
Como foram encontradas muitas inconsistências julguei que a investigação de novos fluxos não acrescentaria a issue e por isso esse critério não foi feito.

**Comment by fabiolamfleury** [comment]
Inicialmente também tive problemas para rodar aqui, depois de umas limpezas de ambiente (algumas vezes) e uma reinicialização pq meu pc tava travando bastante, consegui executar todos os fluxos previstos atualmente na Duda. Antes disso, ele executava a action_setup_conversation e dizia que não previa nenhuma outra ação depois, mesmo as histórias prevendo ir para o vote_form. Não sei o que pode ter causado isso.

Percebi uma possível melhoria nas histórias, colocando a action de restart após a despedida do bot, então abri o MR 
https://gitlab.com/pencillabs/ej/ej-bot/-/merge_requests/11


Aqui pela interface do rasa x a model é persistida no diretório do projeto, e só uma model está sendo criada por vez. Alterei uma história pra testar se ela seria atualizada no arquivo stories.yml, foi o q aconteceu:

![image](https://user-images.githubusercontent.com/20935369/112691375-f8aa2380-8e5b-11eb-8867-3ec7a676a521.png)
