### ISSUE TITLE
Como desenvolvedor, eu gostaria de acessar a documentação sobre como integrar o ejBot com canais como Rocket.chat

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#242]
As ferramentas que estamos integrando com a EJ possuem particularidades que precisam ser documentadas em algum lugar. A ideia é adicionar uma área no /docs da EJ pra isso.

**Tarefas**

- [x] Corrigir erro de rota no /docs
- [x] Adicionar sessão para as Ferramentas;
- [x] Adicionar documentação sobre como integrar o ejBot com uma instância do rocket.chat;
- [x] Adicionar documentação sobre como integrar o ejBot com um webchat generico;

**Comment by fabiolamfleury** [comment]
Resolvido em: https://gitlab.com/pencillabs/ej/ej-server/-/merge_requests/25
