### ISSUE TITLE
Enviar domínio em que o bot está inserido, para que a EJ saiba qual conversa deve ser retornada

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#250]
Atualizar no ej-bot a forma de requisitar a conversa no EJ

**Tarefas**

- [x] Enviar requisição para a EJ, com o domínio em que o BOT está e o ID da conversa que deve ser utilizada por esse bot;
- [x] Popular o slot de ID da conversa a partir da requisição para EJ com o domínio do bot.
- [x] Criar caminho de exceção, caso tente acessar o EJ e não ache nenhuma conversa naquele domínio, voltando pro valor default

**Observação**

Seria importante pensar como será inserida essa informação do ID da conversa e o domínio, para facilitar para administradores de landing page;

**Comment by davidCarlos** [comment]
Essa issue vai ser mais complexa do que imaginávamos. Depois de uma certa investigação, cheguei a conclusão de que não tem uma forma simples de saber em qual domínio o bot está integrado. Nenhum header da requisição enviada do webchat/livechat pro rasa é repassado para o servidor de actions. Isso emplica que, no actions, não tem como saber o `HTTP_HOST` do webchat. Como não sabemos o domínio em que o chat está integrado, não temos como enviá-lo pra EJ, e ai pagina de configuração do Rasa na EJ fica inútil. 

Avaliando nossas opções, proponho a seguinte solução:

1. Não usaremos o livechat do Rocket.chat nas landing pages. Usaremos o rocket.chat apenas para uma futura integração do bot nos grupos de telegram / whatsapp. O livechat não tem a opção de enviar uma menságem para o Rasa logo que a conversa inicia, e isso quebra a solução que proponho;
2. Para o bot nas landing pages, utilizaremos o rasa-webchat.
3. Do lado do Rasa, a intent de welcome terá todas as landingpages com o rasa-webchat integrado. 
4. No momento que o rasa-webchat for carregado na pagina, enviaremos para o rasa o domínio, via `initPayload`.
5. A rule de welcome terá uma custom action, que irá setar como um slot o texto da intent (que será a url enviada pelo `initPayload`);
6. A action que conecta na EJ e puxa a conversa, irá primeiro procurar o slot com a url. Se o slot for válido, ele envia a url para a EJ, e recebe a respectiva conversa;

Essa solução permite um certo nível de escala, pois precisariamos apenas retreinar uma nova model, para cada nova landing page integrada (e a implementação do lado da EJ se mantêm). A solução de subir uma instância por domínio (alguns usuários fazem isso), não é uma opção pra gente.

@fabiolamfleury o que acha? Se ficou confuso, podemos fazer uma call pra eu te explicar o raciocínio.

**Comment by fabiolamfleury** [comment]
@davidCarlos os domínios seriam uma lista então, armazenada no bot? Pq nesse caso, se forem os desenvolvedores responsáveis por atualizar essa lista, não precisa nem retreinar a model, essa informação pode ficar nas actions, e aí teria apenas que executar de novo esse serviço. Caso a gnt queira que seja algo que possa ser acrescentado via rasa x por exemplo aí entendo ir por esse caminho da intent.

A parte que setta o initpayload é realizada via javascript certo? Ai pelo javascript podemos ter acesso ao host e não precisaria 'settar na mão' essa parte também? 

Acredito que é uma boa saída esse caminho!

**Comment by davidCarlos** [comment]
Eu pensei na intent porque primeiro precisamos identificar que o texto que vem é um domínio, e ai teríamos uma lista de domínios como exemplos da intent de welcome. Caindo nessa intent, podemos executar a action que salva o domínio em um slot. Se ficar direto na action, como o rasa vai saber qual action chamar?

Quando ao initPayload, dá pra fazer via js sim. Só pegar o `document.domain`.

**Comment by fabiolamfleury** [comment]
Poderíamos fazer uma action de welcome, que veria qual é o ambiente que o rasa está rodando, e no caso de ser webchat (sei que essa verificação é possível, acho que já foi até discutida em outra issue) a primeira informação será extraída para um slot que será o domínio. Dessa forma, da para configurar esse slot para que ele receba 'qualquer texto' do usuário, e a validação seria realizada via actions. 

É mais ou menos assim que ocorre o voto hoje. Qualquer entrada que o usuário faça naquele momento da história, vai ser interpretado como um voto, e cabe a função de validação na actions ver se aquilo é de fato um voto ou não.

**Comment by fabiolamfleury** [comment]
Mas talvez esse seu caminho faça mais sentido mesmo @davidCarlos . E também da pra ver se o Duckling consegue extrair endereços de domínio, que também já facilitaria essa parte de treinar para entender domínios.

**Comment by davidCarlos** [comment]
Mas o voto é uma action dentro de uma história. O welcome é uma rule. Funciona do mesmo jeito?

Minha ideia é manter essa estrutura
![image](https://user-images.githubusercontent.com/2847027/112861881-36d55c00-9083-11eb-8344-e40119095209.png)

Mas a action seria uma custom_action, que receberia o campo `text` da intent, e salveria em um slot.

![image](https://user-images.githubusercontent.com/2847027/112862001-54a2c100-9083-11eb-89df-c7b782623db8.png)
Aqui ao invés de termos `novo usuário conectado`, teríamos todos os domínios com o rasa-webchat. O `initPayload` mandaria um dos domínios da lista, o Rasa acionaria a Regra, e chamaria a action pra salvar o slot.

Faz sentido?

**Comment by fabiolamfleury** [comment]
Faz sentido! Pra manter como rule acho que é melhor assim mesmo.

**Comment by davidCarlos** [comment]
Beleza, vou seguir nessa linha, e a gente discute mais a fundo quando eu abrir o MR. Eu assinei essa issue pra mim porque já tem muita coisa pra você.
