### ISSUE TITLE
Implementar comandos no bot para permitir que o usuário gerencie uma coleta de opinião em grupos do telegram.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#251]
**Tarefas**

- [x] Procurar no rasa, alguma informação sobre o bot se localizar quanto a estar em um grupo ou conversa individual;
- [x] Se possível, ter uma saudação aos usuários no plural (conforme os slides do Valessio e da Gabi apresentam), caso detecte que o bot está em um grupo;
- [x] Configurar a integração rasa/telegram
- [x] Fazer a coleta de opinião começar, de acordo com a conversa fornecida pelo usuário que esteja gerenciando a conversa;
- [x] Ver como é possível criar IDs para diferentes usuários em uma conversa em grupo;
~~- [ ] Implementar fluxo de autenticação em grupos do telegram~~
~~- [ ] Adicionar um segundo domain.yml, que será específico para as interações em grupos de conversa;~~

**Comment by davidCarlos** [comment]
Vamos focar inicialmente apenas no telegram

**Comment by davidCarlos** [comment]
Sugestões:

1. Conectar nossa instância do Rasa no telegram -> https://rasa.com/docs/rasa/connectors/telegram
2. Implementar ativação do bot via `/ejbot`;
3. Implementar fluxo de autenticação via `/ejbot iniciar` (ou algo do tipo);
4. Puxar uma conversa via `ejbot participar <id-conversa>`
5. Votar em uma conversa via `ejbot votar <id-conversa> <voto>` (isso aqui não é necessário se o participar já vier com os botões de voto).

Acho que esses 5 pontos podem ser o escopo dessa história. Não vamos nos preocupar com Mapeo Social agora. Vamos trabalhar em uma solução genérica para o telegram, e depois vemos como integrar com o sistema da Mapeo.

**Comment by davidCarlos** [comment]
Muito bom @fabiolamfleury. Dei uma testada aqui, tá funcionando bem.

![image](https://user-images.githubusercontent.com/2847027/113068958-5a84c900-918d-11eb-9c6a-8b4948c4e4df.png)

Nesse rítmo a gente consegue incluir nessa sprint ainda um fluxo mais padrão de interação com bots no Telegram, por exemplo, o usuário iniciando a coleta informando qual conversa ele quer utilizar.

**Comment by fabiolamfleury** [comment]
Quanto ao registro de votos de pessoas em um grupo:

O telegram mantem a sessão de chat, independente de ser em grupo ou individual. Pesquisando mais sobre o comportamento do rasa, ele é feito mais pra uso com usuários individualmente. 

Para realizar a autenticação de usuários na EJ usando o rasa conectado ao telegram, imaginei pegarmos o ID do usuário no telegram (já que username nem todos usuários tem).

Dessa forma, por mais que exista apenas um sender_id para o chat em grupo, cada pessoa tem seu id, que seria utilizado para autenticações. Isso faz com que tenhamos uma alteração, pois atualmente temos um slot chamado` ej_user_token` que armazena o token de autenticação de um usuário. Em um grupo, não teríamos como settar uma variável logo de cara, até pq os IDs dos usuários são enviados conforme eles interagem com o bot. Daí, tem 2 opções:

- Autenticar o usuário em cada interação com o ej, a partir do ID do telegram dele;
- Criar um dicionário com IDs e tokens dos usuários em um grupo, quando um ID for enviado, verificar nesse dicionário se ele já tem um token salvo no rasa, do contrário, criar um usuário novo.

**Comment by fabiolamfleury** [comment]
Tinha colocado o fluxo de autenticação aqui nessa issue, mas acredito que ficaria muito extensa e fugiria do escopo, então criei um card no nosso board pra gente fazer como evolução a ela.
