### ISSUE TITLE
Incluir na documentação da EJ,  instruções para configurar o ejBot com o livechat do Rasa

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#255]
**Tarefas**

- [x] Utilizar as informações já contidas em https://github.com/cidadedemocratica/ej-server/issues/238#issuecomment-808321968 para documentar a configuração

**Comment by MarthaDs** [comment]
MR pode ser encontrado [aqui](https://gitlab.com/pencillabs/ej/ej-bot/-/merge_requests/15)

**Comment by davidCarlos** [comment]
@MarthaDs houve uma confusão aqui. Essa issue trata de incluir na documentação da EJ, ou seja, no /docs da EJ, que pode ser acessado pela área de ferramentas, dentro de uma conversa. Você documentou no readme do repositório do bot.

**Comment by MarthaDs** [comment]
MR pode ser encontrado [aqui](https://gitlab.com/pencillabs/ej/ej-server/-/merge_requests/30)
