### ISSUE TITLE
Botões de voto não aparecem no rasa bot a depender do ambiente (exemplo: livechat do rocket)

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#257]
Como já há a tarefa #247 para que haja um entendimento mais conversacional dos votos do usuário, essa tarefa deve prover uma opção para que ambientes que não ofereçam renderização de botões para que possam mostrar as opções de voto para o usuário

**Tarefas**

- [x] Estudar a possibilidade de verificar se no ambiente atual é possível ou não renderizar botões
- [x] Caso não seja possível renderizar botões, exibir algo do tipo (Digite 1 para concordar, 2 para discordar e 3 para pular)

**Comment by fabiolamfleury** [comment]
Vendo coisas da issue #251 , vi que tem como configurar utters de acordo com o channel. Podemos trocar o payload da utter de voto quando estiver no rocketchat, para exibir um substituto aos botões. 

Algumas implicações que tem que ser avaliadas, acredito que no rasa não existe diferenciação entre estar no rocketchat e no livechat, e ai o botão que aparece no rocketchat pararia de aparecer. E também caso utilizemos o rocket pra fazer o deploy pro whatsapp também, vai implicar na mesma coisa

**Comment by fabiolamfleury** [comment]
Quando o ambiente é o rocket chat, da pra fazer a diferenciação do livechat para um canal do rocket por meio das chaves que sao retornadas nos metadados. Acho que isso é um caminho viável para fazer o substituto dos botões e só impactar o livechat

**Comment by fabiolamfleury** [comment]
Fiz testes locais, acho q talvez tenha ficado um pouco estranho a forma que ficou. @davidCarlos vc teria sugestões?
LIVECHAT:

![image](https://user-images.githubusercontent.com/20935369/113764453-5c044300-96f1-11eb-819f-2e883cd5f657.png)


CHAT DO ROCKETCHAT(não foi alterado):

![image](https://user-images.githubusercontent.com/20935369/113764566-83f3a680-96f1-11eb-8306-f9644fcb0511.png)

**Comment by davidCarlos** [comment]
A gente consegue mudar o acolhimento dependendo do canal? Porquê se der, eu acho que o ideal seria informar as três opções de voto antes. Algo tipo "Para concordar com um comentário, digite 1, para discordar de um comentário, digite -1. Caso queira pular um comentário, digite 0". Desta forma o comentário viria apenas com o texto.

**Comment by davidCarlos** [comment]
Na verdade, eu acho que vale que a duda envie uma mensagem explicando como funciona a votação, independente de canal. E ai fica uma solução genérica para todos os casos. Algo tipo "Para concordar com um comentário, digite 1 ou clique no botão Concordar, para discordar de um comentário, digite -1 ou clique no botão Discordar. Caso queira pular um comentário, digite 0 ou clique no botão Pular". Desta forma o comentário viria apenas com o texto.

**Comment by davidCarlos** [comment]
Um outro ponto, que trago pra discussão, é a gente reduzir o número de mensagens do acolhimento. Dizer, por exemplo, que não vamos usar os dados pra Span, não faz muito sentido (já que a gente pode dizer que não vai usar e ainda assim usar). Isso tem que tá coberto na LGPD (que a gente ainda não discutiu como vai ser). Acho que vale um acolhimento mais direto, saudando o usuário, se apresentando (a duda em nenhum momento diz quem ela é), e informando o processo de participação. Dai em diante a conversa começa.

**Comment by davidCarlos** [comment]
> Um outro ponto, que trago pra discussão, é a gente reduzir o número de mensagens do acolhimento. Dizer, por exemplo, que não vamos usar os dados pra Span, não faz muito sentido (já que a gente pode dizer que não vai usar e ainda assim usar). Isso tem que tá coberto na LGPD (que a gente ainda não discutiu como vai ser). Acho que vale um acolhimento mais direto, saudando o usuário, se apresentando (a duda em nenhum momento diz quem ela é), e informando o processo de participação. Dai em diante a conversa começa.

Vou abrir uma issue separada pra isso, para a próxima sprint

**Comment by fabiolamfleury** [comment]
> A gente consegue mudar o acolhimento dependendo do canal? Porquê se der, eu acho que o ideal seria informar as três opções de voto antes. Algo tipo "Para concordar com um comentário, digite 1, para discordar de um comentário, digite -1. Caso queira pular um comentário, digite 0". Desta forma o comentário viria apenas com o texto.

Conseguimos, ótima ideia!
