### ISSUE TITLE
Como usuário, eu gostaria que as cores do template de email sigam o tema selecionado previamente

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#261]
Atualmente, as opções de tema não alteram o visual do template.

Issue de melhoria, relacionada à US #241 
**Tarefas**

- [x] Repercutir o tema selecionado no html do template;
- [x] Manter opções que o usuário selecionou após o reload da página;

**Comment by MarthaDs** [comment]
MR pode ser encontrado [aqui](https://gitlab.com/pencillabs/ej/ej-server/-/merge_requests/33)
