### ISSUE TITLE
Melhorar conteúdo das mensagens enviadas na etapa de acolhimento.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#265]
Precisamos refinar o conteúdo das mensagens enviadas na etapa de acolhimento. Hoje, não explicamos o que é a duda, pra que ela serve, e como o usuário pode participar de uma conversa da EJ por meio dela. Temos algumas mensagens que precisam ser revistas, como o uso de "kkkk", "rs" e etc. A Duda foi desenhada pra ter uma identidade mais jovial, mas o nosso público não será apenas de jovens, então precisamos encontrar um equilibrio no uso de termos abreviados, girias e outras expressões típicas de comunicação por chat.

**Tarefas**

- [x] Adicionar intent que explique o que é a Duda, e o que é a EJ;
- [x] Adicionar intent que explique como o usuário pode participar de uma coleta;
- [x] Remover intents com girias e abreviações;

**Comment by MarthaDs** [comment]
MR com a solução pode ser encontrado [aqui](https://gitlab.com/pencillabs/ej/ej-bot/-/merge_requests/23)
