### ISSUE TITLE
Documentar arquitetura do componente de coleta

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#267]
O componente de coleta cresceu bastante, e como os webcomponents interagem entre si não é uma questão óbvia. O objetivo desta tarefa é documentar a arquitetura do componente de forma resumida (sem entrar em detalhes de implementação), listando os webcomponents, suas responsabilidades, e de que forma eles interagem com a API da EJ.

**Tarefas**

- [x] Adicionar arquivo ARCHITECTURE.md, responsável por centralizar a documentação da arquitetura;
- [x] Documentar cada componente interno, e suas responsabilidades;
- [x] Documentar o processo de autenticação na API da EJ;

**Comment by lorryaze** [comment]
Criei uma primeira versão do documento e abri o merge request, talvez seja preciso algumas melhorias porém fico aguardando feedback.

Eu também não sei se tive uma compreensão muito clara quanto a autenticaçã via api.
