### ISSUE TITLE
Documentação para desenvolvimento na EJ. Arquitetura, models, views, sass e etc.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#269]
# Tarefas

- [x] Atualizar o read-me da EJ linkando o proprio /docs para mais informações de desenvolvimento
- [x] Criar as categorias necessárias no /docs (o @davidCarlos já criou uma parte de documentação de desenvolvimento
- [x] Criar um diagrama para explicação da arquitetura com django boogie
- [x] Escrever explicação sobre a arquitetura do django boogie
- [x] Criar a documentação do sass
- [x] Documentar as traduções
- [x] Criar diagrama de visualização de tudo que compõe o ecossistema EJ (componente de conversa, bot, ej-server

**Comment by fabiolamfleury** [comment]
@davidCarlos acho que seria legal ter seu input nesse diagrama aqui (que seguiu o [modelo C4](https://c4model.com/)) sobre o ecossistema EJ.

Não entendo muito bem como se realiza a conexão da EJ com o mautic e com o google analytics, e também não sei se há alguma coisa que ficou do lado de fora
![image](https://user-images.githubusercontent.com/20935369/114746927-a3f51c80-9d26-11eb-84cd-313c5456bd4f.png)

**Comment by davidCarlos** [comment]
A EJ não conversa diretamente com o mautic e o analytics, quem faz isso é o airflow. Via api, o airflow puxa dados da EJ, mautic e analytics, trata esses dados, cruza as três fontes a partir dos cookies do analyics e do mautic, e consolida o resultado  em uma estrutura de dados única. Esses dados consolidados, serão visualizados dentro da EJ, por meio da nova área de dataviz que estou puxando na issue #273.

**Comment by davidCarlos** [comment]
Quanto ao diagrama, gostei bastante da estrutura, só moveria as conexões da EJ com o analytics e mautic para o airflow.
