### ISSUE TITLE
Realizar rodada de testes com a ultima versão do Bot. Testar uma conversa no telegram, uma conversa via webchat genérico, uma conversa via livechat.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#271]
Já temos bastante coisa desenvolvida no ejBot, e precisamos fazer uma rodada de QA para verificar se tudo que foi desenvolvido está funcionando bem.

**Tarefas**

- [x] Testar ejBot integrado à um canal do rocket.chat;
- [x] Testar ejBot integrado à um webchat generico;
- [x] Testar ejBot integrado ao livechat do rocket.chat;
- [x] Testar ejBot no telegram; 
- [x] Revisar documentações para configurar ejBot nos diversos canais;
- [x] Revisar testes automatizados;

**Comment by MarthaDs** [comment]
Algumas considerações:

**Comment by MarthaDs** [comment]
## Algumas achados
A @fabiolamfleury  me informou que agora existe uma verificação para identificar em qual site o bot está os canais webchat, canal rocket.chat e rocket.chat livechat retornam sempre a mesma mensagem não sendo possível testar uma conversa de fato.

### Webchat generico 

![Screenshot from 2021-04-21 17-11-27](https://user-images.githubusercontent.com/12221656/115618052-8a287c00-a2c8-11eb-8907-6c5aa7e76811.png)

### Rocket.chat Canal
![Screenshot from 2021-04-21 17-31-17](https://user-images.githubusercontent.com/12221656/115618347-f3a88a80-a2c8-11eb-9cca-06a841833454.png)



### Rocket.chat Livechat

![Screenshot from 2021-04-21 17-29-50](https://user-images.githubusercontent.com/12221656/115618212-c5c34600-a2c8-11eb-9a9b-1afd9e944a75.png)

### Telegram
O bot não me deu nenhum feedback.

![Screenshot from 2021-04-21 17-55-47](https://user-images.githubusercontent.com/12221656/115619926-e7253180-a2ca-11eb-82ea-7cabf4195370.png)

Não foi possível adicionar a Duda em grupos.

![Screenshot from 2021-04-21 17-47-16](https://user-images.githubusercontent.com/12221656/115619180-f657af80-a2c9-11eb-8985-bfa9464e43ba.png)

**Comment by fabiolamfleury** [comment]
Essa mensagem de administrador era só pra aparecer no webchat, e não em outros canais, isso ai pode ser mapeado pra uma issue

Não era pra ser possível adicionar a Duda em grupos mesmo

**Comment by MarthaDs** [comment]
### Mais achados

**Comment by MarthaDs** [comment]
## Mais achados

### Local

Ao integrar localmente (http://localhost:8000/) a ej com o webchat generico consegui votar. Entretanto o bot demonstrou algumas incosistencias:

-  Conversa com happy_path que quando interrompida com PARAR não manda msgs de goodbye;
-  conversa com sad_path que continuar para votação mesmo usuário negando participar( Vale lembrar que isso aconteceu em todos os ambientes);
-  O retorno do problema do domain=None apos uma rodada de votação do mesmo usuário(imagem abaixo);

![Screenshot from 2021-04-22 18-09-42](https://user-images.githubusercontent.com/12221656/115785547-fd4bf400-a395-11eb-9eba-caaa64bd8a50.png)

![Screenshot from 2021-04-22 18-09-08](https://user-images.githubusercontent.com/12221656/115785658-22406700-a396-11eb-81d9-2c0775a67ce8.png)

### Homologação
Ao integrar o ambiente de [homologação](https://chat.cidadedemocratica.org.br/) ele ainda não me permitiu votar e ainda demonstrou incosistencia no sad_path :

![Screenshot from 2021-04-22 18-03-52](https://user-images.githubusercontent.com/12221656/115784962-33d53f00-a395-11eb-8a96-ea29627b0682.png)

![Screenshot from 2021-04-22 17-57-52](https://user-images.githubusercontent.com/12221656/115785024-4ea7b380-a395-11eb-82b3-157ad0979673.png)

**Comment by MarthaDs** [comment]
## Fluxos Testados

As informações abaixo que tem como motivo do não funcionamento do bot reference a respostas inesperadas dentro do fluxo testado, tais como as mencionadas no comentário acima.

### Local

|                       PATH      |       FUNCIONOU ? |  MOTIVO  |
| ------------------------------ | -------------------------- | --------------  |
| happy_path sem email | SIM * | Houve uma repetição da msg: Muito obrigada pela sua participação |
| happy_path com email errado | NÃO | BOT |
| happy_path com email votando todos os comentarios | SIM * | Houve uma repetição da msg: Muito obrigada pela sua participação |
| happy_path com email e PARAR | SIM | - |
| sad_path | NÃO | BOT |

Obs. 1: O itens com asterisco funcionaram mas demonstração um pequeno erro reportado na coluna motivo.
Obs. 2: O bot demonstrou resultados diferentes quando utilizado os botões no webchat e quando usado valores. Os resultados acima são apenas de quando usado valores e não os botões por conta disso. 

### Homologação

#### Canal


|                       PATH      |       FUNCIONOU ? |  MOTIVO  |
| ------------------------------ | -------------------------- | --------------  |
| happy_path com email | NÃO  |  INTEGRAÇÃO COM EJ |
| happy_path sem email | NÃO  |  INTEGRAÇÃO COM EJ |
| happy_path com email errado | NÃO | BOT |
| sad_path | NÃO | BOT |

#### Livechat

|                       PATH      |       FUNCIONOU ? |  MOTIVO  |
| ------------------------------ | -------------------------- | --------------  |
| happy_path com email | NÃO  |  INTEGRAÇÃO COM EJ |
| happy_path sem email | NÃO  |  INTEGRAÇÃO COM EJ |
| happy_path com email errado | NÃO | BOT |
| sad_path | NÃO | BOT |

Obs.: Os caminhos não testados em homologação foi por conta do problema de integraçao com o EJ

**Comment by MarthaDs** [comment]
## Sobre a Documentação

A documentação tanto no Ejplataforma como no git ej-bot não informa como testar o bot com EJ local.  Não é explicito que o código atual do bot está configurado para o ambiente de homologação e caso queria testar com conversas de um ej-server local tem que mudar as configurações no docker-compose.yml -> environment para endereço do server local.  Também não é mencionado que é preciso mudar  no codigo do bot o id da conversa que se deseja testar. E acredito que seria importante uma issue para que isso deixe de ser "hard code". 
A documentação do ej-bot também não menciona o modo make run-api que é o utilizado de fato para testar o bot local. Acredito que os gaps existentes são bem mais da documentaçõ do ej-bot do que do ej-server(Ejplataforma) em si. 
Lembrando que também não foi documentado a necessidade de incluir a url de onde se encontra o bot no ej-server.  A respeito disso sinto que falta uma forma mais explicita de onde encontrar a pagina de ferramentas. Tanto na documentação da sonda como do componente eu senti falta de um link ou um direcionamento mais explicito de one achar as configurações descritas na documentação. 

### Bot 

- Documentar comandos do makefile melhor. Ex.: make run-api;
- Documentar como proceder para rodar localmente ou com ej-server de homologação. Ex.: Mudanças no docker-compose.yml, necessidade de recriar containers quando alterado. 

### EjPlataforma

- Documentar que a url onde foi inserido o bot deve ser incluida na parte de ferramentas da conversa;
- Documentar caminho para achar configurações de estilo;

Obs.: Algumas das coisas mencionadas aqui já estão em MR para serem aceitos, pelo que entendi de conversas com a @fabiolamfleury

**Comment by MarthaDs** [comment]
## Sobre os Testes Automatizados
 Todos os testes passaram sem nenhum erro entretanto nossa accuracy ta meio baixa. (Eh o unico indicador que eu sei interpretar de IA):

![Screenshot from 2021-04-23 16-20-41](https://user-images.githubusercontent.com/12221656/115920515-ad7e3300-a450-11eb-8fbf-a46912a31e46.png)

Fora isso acredito que os testes estão ok

**Comment by MarthaDs** [comment]
## Sobre testes no Telegram com Bot e Ej locais

|                       PATH      |       FUNCIONOU ? |  MOTIVO  |
| ------------------------------ | -------------------------- | --------------  |
| happy_path sem email | SIM | - |
| happy_path com email errado | NÃO | BOT, finalizou a conversa |
| happy_path com email votando todos os comentarios | SIM | - |
| happy_path com email e PARAR | SIM | - |
| sad_path | NÃO | BOT  continuou a conversa.|

Obs.: No telegram enviar valores não funcionou como voto. Os testes acima se referem a utilização de botões.

**Comment by fabiolamfleury** [comment]
Acho que seria interessante a gnt debater esses achados pra já levantarmos issues pra resolução;

Uma observação pra gente manter em mente (eu já tinha esquecido e fui caçar em outra issue):

Foi decidido que:

Não usaremos o livechat do Rocket.chat nas landing pages. Usaremos o rocket.chat apenas para uma futura integração do bot nos grupos de telegram / whatsapp. O livechat não tem a opção de enviar uma menságem para o Rasa logo que a conversa inicia, e isso quebra a solução que proponho;

**Comment by davidCarlos** [comment]
> Acho que seria interessante a gnt debater esses achados pra já levantarmos issues pra resolução;
> 
> Uma observação pra gente manter em mente (eu já tinha esquecido e fui caçar em outra issue):
> 
> Foi decidido que:
> 
> Não usaremos o livechat do Rocket.chat nas landing pages. Usaremos o rocket.chat apenas para uma futura integração do bot nos grupos de telegram / whatsapp. O livechat não tem a opção de enviar uma menságem para o Rasa logo que a conversa inicia, e isso quebra a solução que proponho;

Além disso, vamos focar na estabilidade do bot para o canal do telegram.
