### ISSUE TITLE
Implementar no nlu, história que permita configurar o bot no privado.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#275]
Essa tarefa busca implementar um fluxo viável de uso do ejBot em grupos do telegram. A ideia é que a coleta inicialmente seja sempre feita no privado, mas o link para o bot seja compartilhado nos grupos.

**Tarefas**
- [x] Adicionar no botfather as instruções de configuração do bot;
- [x] Implementar action no rasa que gere o link no telegram, incluíndo o id da conversa. Esse link, ao ser clicado, deve levar para o chat privado com o bot;
- [x] Implementar comando /selecionarconversa, que gere o link do telegram com a conversa selecionada;
- [x] Mandar pro Rasa o ID da conversa que estará na url do telegram;
- [x] Manter o fluxo de coleta como funcionava anteriormente no bot, utilizando os dados coletados

**Comment by fabiolamfleury** [comment]
Como a interação está sendo realizada só no privado agora, desativei a possibilidade de adicionar o bot em grupos do telegram.
