### ISSUE TITLE
Consolidar documentação do bot a partir do levantamento feito pela Martha na issue #271. Um dos comentários finais que ela fez, indica possíveis issues de documentação para o bot.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#280]
Essa tarefa busca continuar a construção da documentação do ejBot. Na sprint passada a @MarthaDs fez uma série de levantamentos, na issue #271. O objetivo desta issue é reproduzir esse levantamento feito por ela, mas focando nos grupos do telegram, que será o primeiro canal em que utilizaremos o bot.

**Tarefas**

- [x] Reproduzir achados levantados pela Martha, mas focando apenas no canal do telegram;
- [x] Documentar fluxo de uso do bot no telegram;
- [x] Criar issues de correção (caso existam), para que o bot funcione como esperado;

**Comment by fabiolamfleury** [comment]
Como faz parte dessa issue a documentação do fluxo de uso do bot no telegram, sugiro testar o fluxo no MR que está aberto, e também criei o seguinte fluxograma, que pode auxiliar:

![fluxograma-bot](https://user-images.githubusercontent.com/20935369/116283432-415a4280-a762-11eb-8fbb-2a8d1f8f8420.png)

**Comment by davidCarlos** [comment]
> Como faz parte dessa issue a documentação do fluxo de uso do bot no telegram, sugiro testar o fluxo no MR que está aberto, e também criei o seguinte fluxograma, que pode auxiliar:
> 
> ![fluxograma-bot](https://user-images.githubusercontent.com/20935369/116283432-415a4280-a762-11eb-8fbb-2a8d1f8f8420.png)

muito bom

**Comment by davidCarlos** [comment]
### Revisão do fluxo votando pelo webchat (issue #271)

> Local
>
> Ao integrar localmente (http://localhost:8000/) a ej com o webchat generico consegui votar. Entretanto o bot demonstrou algumas incosistencias:
> 
>     Conversa com happy_path que quando interrompida com PARAR não manda msgs de goodbye;
>     conversa com sad_path que continuar para votação mesmo usuário negando participar( Vale lembrar que isso aconteceu em todos os ambientes);
>     O retorno do problema do domain=None apos uma rodada de votação do mesmo usuário(imagem abaixo);

O problema de integração local era de comunicação com o duckling. Já corrigido no MR https://gitlab.com/pencillabs/ej/ej-bot/-/merge_requests/20

> Homologação
>
> Ao integrar o ambiente de homologação ele ainda não me permitiu votar e ainda demonstrou incosistencia no sad_path

Em homologação eu consegui testar o bot a partir de um site integrado (o site utilizado foi o https://wp.ejparticipe.org/test-rasa-webchat/).
![image](https://user-images.githubusercontent.com/2847027/116317784-31eeef80-a78a-11eb-995f-0c91561b8269.png)
![image](https://user-images.githubusercontent.com/2847027/116317904-5e0a7080-a78a-11eb-8918-cfacdc6b664a.png)
![image](https://user-images.githubusercontent.com/2847027/116317643-fd7b3380-a789-11eb-9151-e5f6c8d4420f.png)

Uma observação pertinente aqui, é que ainda estamos utilizando o ID hardcoded da conversa. Com a implementação de envio do domínio e recebimento da conversa, já podemos evoluir essa implementação e remover o ID hardcoded (issue #285).
