### ISSUE TITLE
processo de treinamento nlu está gerando modelos obsoletas em produção, o que está ocupando um espaço em disco crítico.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#282]
Toda vez que o bot passa por uma build, ele faz o treinamento e gera uma nova model, não excluindo as que foram geradas anteriormente.

**Tarefas**

- [x] Criar um cron que exclua as models que tenham mais de uma semana (verificar primeiramente caso tenha apenas uma model)

**Comment by fabiolamfleury** [comment]
Fiz dois MR, um que altera o dockerfile do ambiente de produção da infra pra ele conseguir rodar o job cron e outro com o script no ej bot
