### ISSUE TITLE
Utilizar integração via domínio entre rasa e EJ, para remover dados hardcoded das conversas 

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#285]
Atualmente, existem algumas custom actions que ainda tem código hardcoded da EJ (id da conversa, por exemplo). Como já existe uma integração entre Rasa e EJ, em que o rasa manda o domínio da aplicação, e a EJ retorna a conversa relacionada, já podemos utilizar essa integração e remover referências hardcoded.

**Tarefas**

- [x] Unificar actions que puxam qual conversa deve ser apresentada ao usuário. Atualmente existem duas, ActionGetConversationId e ActionGetConversationTitle.
- [x] Setar os slots necessários para que a as histórias do Rasa funcionem corretamente;
- [x] Adequar as histórias do telegram para que o usuário possa participar corretamente

**Comment by fabiolamfleury** [comment]
@davidCarlos a action do jeito que tá atualmente, pega a url do webchat, e aí consegue recuperar a conversa. Pra funcionar também no telegram, pensei em deixar essa action com duas possibilidades. Manter como for, caso seja no webchat. Porém, se tiver no telegram:

- Ou a pessoa primeiro usa /selecionarconversa [ID] pra depois usar o /participar
- Ou ela clica no link que outra pessoa gerou.

Ai pra essas implementações teria que alterar algumas coisas no fluxo do telegram, dependendo do MR que tá aberto

**Comment by davidCarlos** [comment]
Acho uma boa abordagem @fabiolamfleury, vou aprovar o MR de grupos, e fazemos essa evolução nessa issue aqui. Pode ser?

**Comment by fabiolamfleury** [comment]
beleza

**Comment by fabiolamfleury** [comment]
Um achado durante a execução dessa issue:

Após o final de um fluxo de conversa com o bot é utilizada a `action_restart` para que os passos passados não sejam levados em consideração a partir daquele momento, inclusive resetando os slots. O problema é que durante a execução no webchat, isso faz com que percamos a URL dele, que fica em slot

**Comment by fabiolamfleury** [comment]
Vou fechar essa issue já que o MR foi aceito
