### ISSUE TITLE
Verificar diferença entre acolhimento no ambiente local e em homologação

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#286]

**Comment by davidCarlos** [comment]
Teste em homologação (https://wp.ejparticipe.org/test-rasa-webchat/)
![image](https://user-images.githubusercontent.com/2847027/117172004-c4eae380-ada1-11eb-8d3a-7304cada44a9.png)

Teste local (http://localhost:8001/)
![image](https://user-images.githubusercontent.com/2847027/117172092-db913a80-ada1-11eb-9f85-2d4fd49cfee7.png)

**Comment by MarthaDs** [comment]
Assinei a issue pra mim e vou começar a mexer nela ok?!

**Comment by MarthaDs** [comment]
Eu consegui reproduzir o erro na minha máquina e resolvi comparar os logs da api local com a de homologação do rasa. E eles estão iguais o que pode acredito que indica que o problema não está nas stories ou nas models criadas.  

![Screenshot from 2021-05-05 17-36-14](https://user-images.githubusercontent.com/12221656/117206150-dbf0fc00-adc8-11eb-8f03-ef4c867eef9a.png)

**Comment by fabiolamfleury** [comment]
testei no ambiente de homologação e local e já não deu mais o problema que foi reportado. Talvez tenha sido pelo MR que subiu hoje, de qlqr forma seria legal mais testes

**Comment by MarthaDs** [comment]
Testei novamente e o problema persiste o bot em homologação sempre omite a primeira mensagem depois da utter_welcome. Como o log do rasa diz que que a ação foi feita acredito que possa ser algum problema na conexão entre o rasa e o webchat. @davidCarlos onde eu posso investigar esse erro de conexão com socket que  apareceu no bot de homologação.

- Imagem do erro de conexão:

![Screenshot from 2021-05-06 16-53-14](https://user-images.githubusercontent.com/12221656/117358299-5cc4fc00-ae8c-11eb-866a-0da25c9fd429.png)

- Imagem do log do rasa no swarmpit :

![Screenshot from 2021-05-06 16-43-30](https://user-images.githubusercontent.com/12221656/117358766-e96fba00-ae8c-11eb-84ec-2a922f1ef40b.png)

**Comment by davidCarlos** [comment]
Consegui resolver. Fica aqui um aprendizado pra gente. O webchat do rasa conecta no rasa via uma conexão persistente (websocket). Tudo que chega na nossa infra, chega primeiro no nginx da ponta, que serve os certificados e redireciona a requisição para os serviços do swarm. Por padrão, o nginx responde conexões http, mas um websocket não é uma conexão http, porque um websocket é bidirecional (o server pode mandar infos pro cliente sem que o cliente requisite). Pro nginx entender uma conexão via socket, é preciso um location específico pra isso:


```
  location /socket.io/ {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_http_version 1.1;
    proxy_pass http://rasa_dev_server:5006;
  }

```

![image](https://user-images.githubusercontent.com/2847027/117505438-67e65d80-af5a-11eb-83dd-b9bc59e1a5be.png)

ps: notei uma melhora significativa na responsividade do webchat, com a nova conf.
