### ISSUE TITLE
Bot não funciona direito no telegram conversando no privado.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#288]
Criei um bot via BotFather, e fiz as configurações pra apontá-lo para o ambiente local. Não consegui participar de uma coleta.

![image](https://user-images.githubusercontent.com/2847027/117174283-f2389100-ada3-11eb-9059-3bcd53dd426c.png)

![image](https://user-images.githubusercontent.com/2847027/117174547-34fa6900-ada4-11eb-8faf-70d37440542b.png)

![image](https://user-images.githubusercontent.com/2847027/117174666-58bdaf00-ada4-11eb-94d1-78b114ac7ff6.png)
![image](https://user-images.githubusercontent.com/2847027/117174730-696e2500-ada4-11eb-99c4-c27a864b88a4.png)

**Comment by davidCarlos** [comment]
@fabiolamfleury prioriza dar uma olhada nessa issue aqui, por favor. Gostaria de testar o bot em um canal do telegram ainda hoje.

**Comment by fabiolamfleury** [comment]
@davidCarlos essas mensagens do bot estão bem desatualizadas, será que seria uma boa ideia vc tentar testar o bot na branch: https://gitlab.com/pencillabs/ej/ej-bot/-/merge_requests/24 ? Eu tinha testado tanto os fluxos do webchat quanto do telegram e tinham funcionado, de qualquer forma vou ver o que tá acontecendo na master

**Comment by davidCarlos** [comment]
Eu vou aprovar logo esse MR então, e fazer mais uma rodada de testes.

**Comment by fabiolamfleury** [comment]
fiz testes aqui com a master atualizada, já não cai nesses problemas, tava sem carregar o título da conversa, subi essa correção

**Comment by davidCarlos** [comment]
Rodei mais um teste aqui. Está disparando alguns erros no log
![image](https://user-images.githubusercontent.com/2847027/117209984-7f441000-adcd-11eb-97ed-ed1bd6a65b18.png)
![image](https://user-images.githubusercontent.com/2847027/117210061-95ea6700-adcd-11eb-9ff9-b747a0b34d13.png)

**Comment by fabiolamfleury** [comment]
@davidCarlos não consegui reproduzir os erros, seguindo os mesmos passos, mas usando dois dispositivos diferentes (na mesma instância do bot, a conversa prosseguiu de duas formas diferentes:

![image](https://user-images.githubusercontent.com/20935369/117336380-853ffc80-ae72-11eb-87a6-80ef5035efc8.png)

![image](https://user-images.githubusercontent.com/20935369/117336522-ab659c80-ae72-11eb-824e-182114244d27.png)


Vou prosseguir os testes fazendo algumas alterações nas histórias pra tentar mapear o pq dos comportamentos

**Comment by fabiolamfleury** [comment]
Fiz algumas alterações e testei os fluxos:

- Usuário não quer participar
- Usuário quer participar com email
- Usuário quer participar, mas dá um email invalido
- Usuário quer participar sem email
- Usuário interrompe a participação

Todos esses fluxos funcionaram no telegram, @davidCarlos eu crio uma branch com as alterações ou sobe um fix na master?

**Comment by davidCarlos** [comment]
Pode subir na master. De qualquer forma, eu testei aqui local, e consegui participar, informando o email e parando no meio da coleta. Acho que já podemos fechar essa issue.

**Comment by davidCarlos** [comment]
@fabiolamfleury vamos fechar essa issue?

**Comment by fabiolamfleury** [comment]
vou fechar aqui :)
