### ISSUE TITLE
Correções visuais no componente de opinião

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#290]
**Tarefas**

- [x] Botões da modal que aparece logo que o componente carrega pela primeira vez, não possuem o foco para click;
- [x] Adicionar loading na área de registro, enquanto o componente se comunica com a API;
- [x] Abas "Comentários" e "Grupos", estão com a fonte muito pequena no mobile;
- [x] Texto de aviso na aba de grupos pode ocupar mais espaço no mobile;
- [x] ícone triangular que aparece abaixo das estatísticas da conversa está com um pequeno erro de posicionamento;
- [x] Spinner na aba de grupos não desaparece, caso não existam votos suficientes na conversa;

**Comment by MarthaDs** [comment]
@davidCarlos quando vc fala "ícone triangular" ta se referindo a que icone ?

**Comment by MarthaDs** [comment]
@davidCarlos  Incluir nas correções para esse problema aqui :

![Screenshot from 2021-06-14 23-12-19 (1)](https://user-images.githubusercontent.com/12221656/121982866-c0352a00-cd66-11eb-96a2-52480b1876c2.png)

**Comment by MarthaDs** [comment]
MR pode ser encontrado [aqui](https://gitlab.com/pencillabs/ej/conversation-component/-/merge_requests/12)
