### ISSUE TITLE
erro 404 com o componente no site do ICD

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#293]
Snipet do componente:

<ej-conversation host="https://www.ejparticipe.org" cid="68" theme="icd" authenticate-with="mautic"></ej-conversation>

Página do site: https://cidadedemocratica.org.br/opine

Erro: 

Failed to load resource: the server responded with a status of 404 ()

![Captura de tela de 2021-05-19 15-53-26](https://user-images.githubusercontent.com/1162183/118868412-87ff1080-b8ba-11eb-9f98-60255037e473.png)

**Comment by davidCarlos** [comment]
Componente carregando corretamente agora
