### ISSUE TITLE
Criar roteiro de respostas da Duda, para que o time de marketing digital possa adapta-las ao contexto do projeto.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#306]
As respostas que a Duda envia para o usuário foram definidas pelo time de desenvolvimento, durante as sprints da primeira fase. Agora que temos uma versão inicial para ser utilizada em produção, precisamos adaptar as respostas para o contexto do boca de lobo (demo.eco).

## Roteiro
A estrutura do roteiro deve agrupar as respostas da Duda em três partes: acolhimento, participação e finalização.
Para cada mensagem enviada pelo usuário, o roteiro deve apresentar a respectiva resposta.
O Roteiro também deve prever por qual canal o usuário está se comunicando
 
### Exemplo

- Canal: Telegram
- Etapa: Acolhimento

Olá, muito prazer, eu sou a Duda! Eu sou a assistente virtual da plataforma EJ. A Empurrando Juntos, ou Platforma Ej, é uma plataforma de consultas de opinião com foco em Estado e Organizações. Os seguintes comandos estão disponíveis:
/selecionarconversa [id]: Utilize esse comando para gerarmos uma nova coleta. [id] é o identificador da conversa na EJ;
/participar: Utilize esse comando para participar de uma coleta pré-selecionada;

Conteúdos que venham da EJ como comentários, e título da conversa não precisam ser documentados.

**Tarefas**
- [ ] Montar roteiro para coleta via telegram;
- [ ] Montar roteiro para coleta via webchat;

**Comment by CristianeNaves** [comment]
[Roteiro.pdf](https://github.com/cidadedemocratica/ej-server/files/6651458/Roteiro.pdf)
