### ISSUE TITLE
Número de comentários restantes para participação não atualiza no primeiro voto dado, apenas no segundo.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#309]
Se o usuário acessa o componente, e vota, o número de comentários restantes para participação não é atualizado. Apenas no segundo voto e o contador incrementa, mas incrementa errado, já que o primeiro voto não é computado.

![image](https://user-images.githubusercontent.com/2847027/120908368-017b5a80-c640-11eb-8275-5eb50facfd3c.png)

**Comment by MarthaDs** [comment]
@davidCarlos Eu não consegui reproduzir esse bug. 

![Screenshot from 2021-06-17 19-50-27](https://user-images.githubusercontent.com/12221656/122481602-56569380-cfa5-11eb-89d8-0722bc008257.png)

![Screenshot from 2021-06-17 19-49-50](https://user-images.githubusercontent.com/12221656/122481606-58205700-cfa5-11eb-9472-e5e4eb3a8e79.png)

**Comment by MarthaDs** [comment]
Testado no ambiente de homologação ele so atualiza o numero quando eu concordo, quando discordo ele tb não atualiza.

**Comment by davidCarlos** [comment]
Eu acabei de reproduzir ele em homologação. Basta acessar via aba anonima, se registrar, e concordar no comentário. O contador não é incrementado. Quando eu testei local também não funcionou

**Comment by davidCarlos** [comment]
https://wp.ejparticipe.org/

**Comment by MarthaDs** [comment]
Sim em homologação não funciona por isso eu apontei para ambiente de homologação aqui local e aqui funciona. Acabei de testar numa aba anonima local apontando `<ej-conversation host="https://www.ejparticipe.org" cid="67" theme="icd" authenticate-with="analytics"></ej-conversation>
` e funcionou. 

![Screencast-from-17-06-2021-20_00_59](https://user-images.githubusercontent.com/12221656/122482558-2c9e6c00-cfa7-11eb-82ea-23ab1602f5b4.gif)

**Comment by MarthaDs** [comment]
Não sei o que pode ta causando a diferença no log dele mas no de homologação ele ta dando erro ao tentar forçar um update que eh justamente onde ocorre o incremento.

**Comment by davidCarlos** [comment]
Bug será resolvido em na issue # de refatoração #327
