### ISSUE TITLE
Desenhar pipeline de dados incluíndo o ariflow, EJ e mautic.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#312]

**Comment by davidCarlos** [comment]
Seguindo o modelo c4 para representar arquitetura de software, defini o seguinte diagrama:
![ej_system_context drawio(1)](https://user-images.githubusercontent.com/2847027/121217323-1cc0b280-c858-11eb-9b45-fcc1c693331b.png)

**Comment by davidCarlos** [comment]
Reduzindo o nível de abstração, e dando uma visão mais detalhada da relação EJ / Airflow
![ej_container_context drawio](https://user-images.githubusercontent.com/2847027/121225194-aa53d080-c85f-11eb-9e68-87acd8639689.png)

**Comment by ricardopoppi** [comment]
Ficou ótimo e bem didático. Dá pra ver bem a função e o valor de cada solução no arranjo como um todo
