### ISSUE TITLE
Refatorar classe TemplateGenerator, para que ela receba um form do Django como um dos argumentos

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#314]
Estamos passando para a classe TemplateGenerator os argumentos template_type e theme, além de custom_title e custom_comment. Todos esses campos pertencem ao Form, logo, o ideal é passar o form diretamente para a classe, reduzindo o número de argumentos necessários.

**Tarefas**
- [x] Refatorar construtor da classe TemplateGenerator, para que ela receba um form como argumento, no lugar dos campos template_type e theme;
- [x] Adaptar implementações para os novos argumentos;
- [x] Chamar método `set_custom_values` internamente na classe;
- [x] Implementar testes;
- [x] Arrumar erro na geração de template de uma conversa (Quando não seleciona o tipo de template e clica no botão de pré-visualização, ocorre um erro de TemplateNotFound.);

**Comment by CristianeNaves** [comment]
Foi encontrado o seguinte bug ao realizar a refatoração: quando não é selecionado o tipo de template e clico no botão de pré-visualização, ocorre um erro de TemplateNotFound. Para resolver isso, adicionei uma nova issue #336.
