### ISSUE TITLE
Duda está exibindo "none" no lugar do título/pergunta-mote da conversa

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#323]
Link para testar: http://t.me/DudaEjBot?start=69

![photo_2021-06-14_12-31-49](https://user-images.githubusercontent.com/1162183/121918592-93542900-cd0c-11eb-8dbf-6ff846a45226.jpg)

**Comment by davidCarlos** [comment]
No meu caso a Duda está puxando uma conversa direrente do id informado no link. Provavelmente a raiz do problema é que o slot do id da conversa não está sendo recuperado corretamente.

**Comment by davidCarlos** [comment]
@shayanealcantara dá uma olhada nesse bug? Se precisar de ajuda me avisa que a gente olha junto.

**Comment by davidCarlos** [comment]
Pra auxiliar na investigação. 
![image](https://user-images.githubusercontent.com/2847027/121925694-90106b80-cd13-11eb-9179-80b0718f9fa6.png)

1. Iniciei a conversa com o bot;
2. Selecionei a conversa: /selecionarconversa 69
3. cliquei no link que a duda gerou
4. Ela conseguiu puxar o título da conversa

O bug pode estar quando um usuário qualquer acessa o link sem nunca ter conversado com o bot antes. Quando eu cliquei no link pela primeira vez, o bot me retornou a conversa de ID 56, que era a conversa que eu estava testando quando fui implementar a alteração no título da conversa (issue #291)

**Comment by ricardopoppi** [comment]
Pra agregar: eu já tinha interagido com a Duda antes pelo meu telegram e quando eu tentei ir pelo caminho de digitar o comando "/selecionarconversa 69" ela exibiu o mesmo comportamento exibindo "none" (print):

![photo_2021-06-14_13-41-58](https://user-images.githubusercontent.com/1162183/121928206-4d9c5e00-cd16-11eb-8475-7eded502585d.jpg)

**Comment by shayanealcantara** [comment]
> @shayanealcantara dá uma olhada nesse bug? Se precisar de ajuda me avisa que a gente olha junto.

Vou olhar agora mesmo!
