### ISSUE TITLE
Atualizar domain.bocadelobo.yml com textos do time de mkt digital

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#328]
A Jasmine está preparando os textos que irão no novo domain.bocadelobo.yml. Assim que ela enviar, precisamos passar os textos para o domain.

**Tarefas**

- [x] Atualizar domain.bocadelobo.yml com os novos textos;
- [x] Corrigir os testes que quebrarem

**Comment by davidCarlos** [comment]
Link com os novos textos do domain.bocadelobo.yml -> https://docs.google.com/document/d/1dGzi5NkTneSyTCE4wyG0uCVYuD1zOrrt9BThuoRU5O0/edit?usp=drive_web&ouid=114186603655244159033

**Comment by CristianeNaves** [comment]
![Screenshot from 2021-07-06 15-59-49](https://user-images.githubusercontent.com/11787002/124655724-a1faaf80-de76-11eb-8d85-cf779dcaec76.png)

Erro que ocorre quando inclui telefone (era para ter mostrado outra mensagem dizendo que não reconheceu o telefone).
