### ISSUE TITLE
Mautic não está criando usuario pelo tracking

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#33]
Para replicar:

1) Ativar e configurar o wp-mautic plugin no wordpress
Parametros:
https://mautic.pencillabs.com.br
Embedded within the `wp_footer` action.
Activate it when JavaScript is disabled ?

2) Acessar o wordpress em aba anonima e verificar o cookie criado para o dominio do mautic. Isso é feito pelo script mtc.js

3) Verificar na tela de contatos do mautic ou no dashboard se um novo usuário anonimo foi criado. Além do log do apache, o log de prod do mautic tb pode trazer insights ([mautic_root]/app/logs/mautic_prod-YYYY-mm-dd.php)

Referencia: Issue sobre problema parecido: https://github.com/mautic/mautic/issues/7890

Hipótese: mautic está rejeitando pq wp está na mesma rede em prod e pode exigir uma configuração específica para isso

**Comment by davidCarlos** [comment]
Algumas considerações sobre essa issue:

### Configurações feitas a nível de painel administrativo
- Configurações > Configurações de Rastreamento > Identificar visitantes pela impressão digital do dispositivo: marcar como sim.

### Configurações feitas a nível de php
Incluir opção `track_private_ip_ranges => true` no arquivo **app/config/local.php**
Referência: https://www.mautic.org/docs/en/contacts/contact_monitoring.html

### Observação a respeito do usuário criado via plugin de integração do wp

Devido à uma limitação do docker swarm, todos os contatos anônimos estão sendo apresentados com um mesmo ip (10.255.0.2). No backend o mautic não usa esse ip pra identificar o usuário, e sim o cookie único (mautic_device_id) que ele seta no navegador.  Esse ip é só pra ter alguma informação pra apresentar na listagem dos contatos, já que ele é anônimo. Como o ip do usuário não vai ser utilizado a princípio, não vejo isso com impeditivo pra gente. Essa limitação é um problema relativamente sério do swarm, pq depois que a requisição entra no cluster, o ip publico de quem mandou a requisição é substituido pelo ip interno do cluster. Tem uma issue de 2016 que até hj tá aberta (https://github.com/moby/moby/issues/25526).
