### ISSUE TITLE
Corrigir exibição de autoria do comentário feito via componente

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#37]
Testando via componente v2, ou seja, com a modal que pede nome e email, o EJ está usando a informação do email para indicar a autoria do comentário (ver print). O correto seria o nome.

Para o caso do componente usado via cookie do mautic, será necessário exibir um texto padrão na autoria, pois não teremos nenhuma informação do usuário (eventualmente um texto padrão: "Participante anônimo" ou algo do tipo)

![Captura de tela de 2020-02-18 17-27-39](https://user-images.githubusercontent.com/1162183/74775236-0b732180-5274-11ea-981f-cd6bf20138ae.png)

**Comment by davidCarlos** [comment]
@LeoSilvaGomes, com a README do [repositório](https://gitlab.com/pencillabs/ej/conversation-component) do componente já dá pra você subir o projeto e testar a integração com a EJ. Essa issue vai ficar pra  você mesmo, porquê eu não vou ter perna pra puxar isso. Qualquer coisa a gente faz uma call, caso vc fique travado em algo.

**Comment by LeoSilvaGomes** [comment]
@ricardopoppi A lógico de exibir "Participante anônimo" deve ser apenas para os usuários que se cadastraram via mautic?

![image](https://user-images.githubusercontent.com/61520601/80130167-902d3500-856e-11ea-8ea8-8088851d05ba.png)

Até o momento eu coloquei para todos os comentários via mautic serem renderizados com o nome "Participante anônimo", isso procede?

**Comment by ricardopoppi** [comment]
Testado aqui, para os usuários que tinham nome, apareceu corretamente
