### ISSUE TITLE
Os links "save and..." da tela de edição de conversas não funcionam

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#38]
Os links no final da tela de criação/edição da conversa não levam para o comportamento correto. Eles estão com o mesmo efeito da opção de salvar a conversa.

O comportamento esperado é que o link "Save and manage stereotypes" levasse para a tela de edição de personas e o link "Save and moderate comments" levasse para a tela de moderação.

![screencapture-ejplatform-pencillabs-br-conversations-51-desafiosvotorantim-edit-2020-02-18-17_30_19](https://user-images.githubusercontent.com/1162183/74775555-b4ba1780-5274-11ea-997a-9c2cfc128982.png)

**Comment by LeoSilvaGomes** [comment]
Os dois links redirecionam para as páginas solicitadas.

### Como foi resolvido:

- O erro estava na forma como os links estavam redirecionando...
  Foi ajustado a função ```reverse``` para ```conversation.url```, que redireciona normalmente para a página desejada

**Comment by ricardopoppi** [comment]
Issue testada em homolog, tudo ok
