### ISSUE TITLE
Erro nas rotas de edição de grupos e personas nas conversas criadas em boards

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#39]
Para replicar:

1) Crie um board qualquer em /profile/boards
2) Crie uma conversa qualquer nesse board (opção no menu lateral)
3) Tente editar os grupos dessa conversa (opção no menu lateral)
4) Tela de erro (print)
5) [SE VC ESTA AUTENTICADO COMO ADMIN E A CONVERSA TIVER SIDO PROMOVIDA NA CRIAÇÃO OU DEPOIS] Vá na rota da conversa (removendo o nome do quadro da url)
6) Tente editar grupos e veja que funcionou

![Captura de tela de 2020-02-18 22-28-24](https://user-images.githubusercontent.com/1162183/74793105-25295e80-529e-11ea-90bf-ff410922398a.png)

**Comment by LeoSilvaGomes** [comment]
O erro estava na hora de construir a página, ele estava redirecionando para ```stereotype-votes``` que corresponde ao link Manage personas, dessa forma no arquivo ```cluster-edit.jinja2``` na pasta jinja do ej_boards, foi modificado o extendes de ```stereotypes-votes``` para ```edit```

**Comment by ricardopoppi** [comment]
Issue testada em homolog, tudo ok
