### ISSUE TITLE
Erro na exibição do nome do quadro

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#40]
O quadro está exibindo o título "Public conversations" em vez do nome do quadro (ver print). O comportamento esperado era exibir o nome do quadro definido em "title" (ver print)

![Captura de tela de 2020-02-18 19-07-46](https://user-images.githubusercontent.com/1162183/74782347-05843d00-5282-11ea-8e92-8e89b84d75c8.png)
![Captura de tela de 2020-02-18 19-07-09](https://user-images.githubusercontent.com/1162183/74782354-0917c400-5282-11ea-8df6-2171d4d709c6.png)

**Comment by LeoSilvaGomes** [comment]
O conversation board usa a rota da public conversations para gerar as informações necessárias para criar a página, ou seja, retornando ao template sempre o title "Public conversations", dessa forma eu criei um novo parametro que tem como valor padrão "Public convesations", mas que pode ser alterado passando o parametro board.title na rota do board.

![image](https://user-images.githubusercontent.com/61520601/77567157-84821c00-6ea5-11ea-8cc6-ecf34520c127.png)

**Comment by ricardopoppi** [comment]
Issue testada em homolog, tudo ok
