### ISSUE TITLE
Incluir no CI step para publicar novo componente, caso os testes passem.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#49]
**Tarefas**
- [x] criar documentação que exemplifica a estrutura que deve ser seguida para atualização da versão do código (version semantic)
- [x] autentica no npm via npmrc
- [x] npm publish

**Comment by LeoSilvaGomes** [comment]
Para resolução da issue, foram utilizadas a documentação do npm sobre token e .npmrc

https://docs.npmjs.com/configuring-npm/npmrc.html
https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow#create-a-new-authentication-token

**Comment by LeoSilvaGomes** [comment]
Foi decidido fazer o documento de versionamento de codigo, diretamente no readme para haver a informação no npm também.

O documento exemplifica a documentação o [semantic versioning](https://semver.org/), com um adendo no final para as major releases, pois sente-se necessidade de adapitação para o contexto do ej-conversations.
