### ISSUE TITLE
Implementar mecanismo na EJ para recuperar ultima tag publicada no npm.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#50]
A tag do componente que aparece no integrations de uma conversa está hardcoded. Encontrar uma forma de recuperar essa tag do repositório no npm.
https://www.npmjs.com/package/ej-conversations

**Comment by LeoSilvaGomes** [comment]
Foi utilizado o https://registry.npmjs.org/-/package/ej-conversations/dist-tags para retornar a informações sobre a ultima tag publicada.
