### ISSUE TITLE
Erros nas rotas da página de edição da conversa

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#60]
1) Na tela de edição da conversa dentro do board ex: https://www.ejparticipe.org/opiniaoucc/conversations/54/fortaleceucc/edit/ ) a opção "Save and manage stereotypes" não está direcionando o usuário para a rota https://www.ejparticipe.org/opiniaoucc/conversations/54/fortaleceucc/stereotypes/ como seria o esperado

2) Na tela de edição de uma conversa dentro do board (ex: https://www.ejparticipe.org/opiniaoucc/conversations/54/fortaleceucc/edit/ ) a opção "Save and moderate comments" no final da tela está quebrando. Ela deveria direcionar o usuário para a rota https://www.ejparticipe.org/opiniaoucc/conversations/54/fortaleceucc/moderate/

**Comment by LeoSilvaGomes** [comment]
Essa issue já foi resolvida na issue #38

**Comment by ricardopoppi** [comment]
Issue testada em homolog, tudo ok
