### ISSUE TITLE
Nuvem de pontos fica carregando infinamente e não exibe o gráfico

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#67]
Ao clicar na opção "Nuvem de pontos" o gráfico não carrega

![Captura de tela de 2020-04-03 11-10-36](https://user-images.githubusercontent.com/1162183/78369811-27205600-759c-11ea-9ad0-3668b7dc1c27.png)

**Comment by LeoSilvaGomes** [comment]
A lista das opiniões estava sendo duplicada, por isso não estava sendo enviada corretamente para gerar o gráfico, entretanto há um erro que ainda persiste:

![image](https://user-images.githubusercontent.com/61520601/79395165-77f65e00-7f4f-11ea-8303-b7de7e8d531e.png)

Essa é a tabela gerada pelo dataframe, para renderizar o gráfico, como pode ser percebido não existe nenhum cluster associado a nenhum usuário, ou seja, na exibição do gráfico todos os usuários não são associados a nenhum cluster:

![image](https://user-images.githubusercontent.com/61520601/79395365-d58aaa80-7f4f-11ea-8a12-12c610bb88f5.png)

Perguntas @ricardopoppi :
- Como funciona essa associação do usuário com o cluster?

**Comment by ricardopoppi** [comment]
Oi @LeoSilvaGomes no gráfico de nuvem de pontos essa associação não existe mesmo, fica subentendida apenas visualmente pela proximidade dos pontos dos marcadores de cluster (que imagino serem essas bolinhas cinzas). O tipo de gráfico que exibe explicitamente os clusters é o anterior o "Grupos de opinião".

Então acredito que esse gráfico já atenda o requisito. Posso avaliar melhor em homologação e te dou um feedback.

**Comment by ricardopoppi** [comment]
@LeoSilvaGomes revisando em homolog, o gráfico de pontos funcionou pra uma conversa com poucos votos, mas uma com mais votos, ficou carregando infinitamente

conversa com poucos votos que funcionou legal: https://ejplatform.pencillabs.com.br/conversations/51/desafiosvotorantim/scatter/

conversa com muitos votos que ficou carregando infinitamente: https://ejplatform.pencillabs.com.br/conversations/51/desafiosvotorantim/scatter/

também notei uma questão de privacidade sobre a exposição do email dos usuários, criei a issue #83 sobre isso

**Comment by ricardopoppi** [comment]
Testado, aparentemente funcionando para conversas com qq quantidade de votos, ainda que não tenha sido possível testar com muitos milhares
