### ISSUE TITLE
Incluir a opção de murais, que hoje está escondida

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#73]
- [x] Na rota /profile/ aba "Contribuições" criar uma seção para "Boards" (boards em inglês, murais na tradução em português), no mesmo padrão do ítem "Conversas" só que linkando pra rota /profile/boards/

- [x] No menu lateral/hamburguer do usuário (página inicial, rota /conversations) incluir um ítem "Boards"(murais na tradução em ptbr) linkando pra rota /profile/boards/ (ver imagem)

![Captura de tela de 2020-04-07 18-56-05](https://user-images.githubusercontent.com/1162183/78723254-80bcb380-7901-11ea-9651-33dee8ba3c2c.png)

**Comment by LeoSilvaGomes** [comment]
Na aba de conversas no perfil, sentia a necessidade de decidir um icone para o board, então depois da decisão entre os membros, ficou definido como icone para o board o ```chipboard-list``` do font awesome

![image](https://user-images.githubusercontent.com/61520601/78827848-2b90a880-79ba-11ea-8eea-7ec5ab50699d.png)

**Comment by ricardopoppi** [comment]
@LeoSilvaGomes ficaram ótimos os ítens de menu. Uma única questão pra gente pensar como resolver é que para os usuários recem criados sem permissão para criar murais talvez seja o caso de escondê-los pois nesses casos está levando para uma tela de erro 500. Vejo duas opções:

1) Esconder o ítem de menu e o ítem de murais em "Contribuiçõe" qdo o usuário não tiver a permissão definida ou
2) Continuar exibindo e permitir que o usuário acesse a página de gestão mas sem a capacidade de criar um mural novo. Esse já é o comportamento do ítem "Conversas" por exemplo, que atualmente redireciona o usuário para uma página das suas conversas, mas sem a opção de criar uma nova. 

O ideal seria a gente padronizar esse comportamento. A princípio me parece mais coerente ocultar os ítens "Conversas" e "Murais" em "Contribuições" e os ítens de menu correspondentes quando o usuário não tiver permissão. O item de menu "Nova conversa" já tem esse comportamento, já que só aparece quando o usuário tem mural criado e está acessando o mural. Fora dessa situação e contexto ele já é ocultado pelo EJ.

**Comment by ricardopoppi** [comment]
@LeoSilvaGomes testei em homolog e não exibiu a opção de mural no menu, mesmo para um usuário com permissão (ricabras+homolog no grupo editores)

**Comment by LeoSilvaGomes** [comment]
> @LeoSilvaGomes testei em homolog e não exibiu a opção de mural no menu, mesmo para um usuário com permissão (ricabras+homolog no grupo editores)

Em ambiente de desenvolvimento isso não está ocorrendo, preciso de mais detalhe para o que está ocorrendo (para isso penso em ter algum usuário de admin no ambiente de homolog). Entre com as restrições citadas no segundo comentário.

**Comment by ricardopoppi** [comment]
Ah ok, vou te mandar em pvt no slack uma credencial de superadministrador
