### ISSUE TITLE
Limitar a exposição do email dos usuários no gráfico de pontos

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#83]
No gráfico de pontos, o mouse over expõe o email do usuário. O ideal seria expor o "Nome do usuário" e quando não houver essa informação usar um texto de marcação tipo "Anônimo"

Ver print:
![Captura de tela de 2020-04-16 17-18-46](https://user-images.githubusercontent.com/1162183/79502742-6a4fdf80-8006-11ea-9db7-8944a53e9d67.png)

**Comment by ricardopoppi** [comment]
Testei aqui e o email do usuário continua aparecendo no gráfico

![Captura de tela de 2020-05-13 22-30-14](https://user-images.githubusercontent.com/1162183/81882542-62ce1880-9569-11ea-83e3-f1bf4f58c5e1.png)

**Comment by LeoSilvaGomes** [comment]
Essa atualização possibilitou a correção na criação de novos usuários, para não aparecerem errados no gráfico, ou seja, os usuários que já foram criados no banco de dados com as informações erradas, deverão ser substituidos por "Participantes anónimos", essa atualização deverá ser feita **nessa issue**
