### ISSUE TITLE
Implementar identidade visual do componente de acordo com o site da TI.

### ISSUE THREAD

**Issue by davidCarlos** [cidadedemocratica/ej-server#9]
Imagens provisórias abaixo. Esses foram os pedidos de ajustes:

1. Acrescentar marca d'agua ou outra solução visual para incluir a logo da ej em algum canto do componente
2. Nas telas criar-comentario tanto versão mobile quanto desktop, substituir o texto para "ENVIAR COMENTÁRIO"
3. O botão que aparece para clicar (telas de coleta em texto) exibir o texto "Dê sua opinião" em vez de "Participar da discussão"

![5-mobile-onboarding](https://user-images.githubusercontent.com/1162183/75563670-7fa68580-5a29-11ea-94fb-337e2f6bcc92.jpg)
![5-desktop-onboarding](https://user-images.githubusercontent.com/1162183/75563689-846b3980-5a29-11ea-9c1b-031f2ddf29f3.jpg)
![2-coleta-desktop-em-textos-parte2](https://user-images.githubusercontent.com/1162183/75563708-8cc37480-5a29-11ea-9494-ff230e58e960.jpg)
![3-mobile-criar-comentario](https://user-images.githubusercontent.com/1162183/75563722-94831900-5a29-11ea-9e4f-37c221ed93e3.jpg)
![4-desktop-criar-comentario](https://user-images.githubusercontent.com/1162183/75563729-9816a000-5a29-11ea-9e94-ca2fbef65493.jpg)
![2-coleta-desktop-em-textos](https://user-images.githubusercontent.com/1162183/75563764-a664bc00-5a29-11ea-9d5a-fbd5271c1130.jpg)
![2-coleta-desktop](https://user-images.githubusercontent.com/1162183/75563806-b9778c00-5a29-11ea-8a15-5c9fb53e3d61.jpg)
![1-coleta-mobile-em-textos](https://user-images.githubusercontent.com/1162183/75563836-c4cab780-5a29-11ea-9801-e254222f2595.jpg)
![1-coleta-mobile-em-textos-parte2](https://user-images.githubusercontent.com/1162183/75563874-d57b2d80-5a29-11ea-8c5f-79efb1bc54fc.jpg)
![1-coleta-mobile](https://user-images.githubusercontent.com/1162183/75563880-d7dd8780-5a29-11ea-8c7f-b7d9387fca9a.jpg)

**Comment by ricardopoppi** [comment]
Fechando essa issue pois ela foi desdobrada nas issues #43 #44 #45
