### ISSUE TITLE
Rejeição de comentário causa erro 500

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#95]
Para replicar:

- Crie uma conversa
- Faça comentários com outro usuário
- Volte como criador da conversa e tente rejeitar os comentários
- A primeira ação de rejeição dá erro 500
- Recarregue a página e perceba que o comentário foi de fato rejeitado

Então ele aceita a rejeição mas mesmo assim dá erro 500 pro usuário

**Comment by ricardopoppi** [comment]
@LeoSilvaGomes fiz o procedimento indicado na issue (inseri comentário por um usuário qualquer e posteriormente tentei rejeitar com o usuário criador da conversa) e obtive o erro 500

**Comment by LeoSilvaGomes** [comment]
> @LeoSilvaGomes fiz o procedimento indicado na issue (inseri comentário por um usuário qualquer e posteriormente tentei rejeitar com o usuário criador da conversa) e obtive o erro 500

O pr ainda não foi aceito, por isso que o teste não funcionou
