### ISSUE TITLE
Exportar dados do admin do facebook para obtermos modelo

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#99]
Fazer a exportação via admin da página

**Comment by ricardopoppi** [comment]
Dados gerais da página:


Data | Lifetime Total Likes | Daily New Likes | Daily Unlikes | Daily Page Engaged Users | Weekly Page Engaged Users | 28 Days Page Engaged Users | Daily Total Reach | Weekly Total Reach | 28 Days Total Reach | Daily Organic Reach | Weekly Organic Reach | 28 Days Organic Reach | Daily Paid Reach | Weekly Paid Reach | 28 Days Paid Reach | Daily Viral Reach | Weekly Viral Reach | 28 Days Viral Reach | Daily Total Impressions | Weekly Total Impressions | 28 Days Total Impressions | Daily Organic impressions | Weekly Organic impressions | 28 Days Organic impressions | Daily Paid Impressions | Weekly Paid Impressions | 28 Days Paid Impressions | Daily Viral impressions | Weekly Viral impressions | 28 Days Viral impressions | Daily Logged-in Page Views | Weekly Logged-in Page Views | Daily Logged-in Page Views | Weekly Logged-in Page Views | Daily Reach Of Page Posts | Weekly Reach Of Page Posts | 28 Days Reach Of Page Posts | Daily Organic Reach of Page posts | Weekly Organic Reach of Page posts | 28 Days Organic Reach of Page posts | Daily Paid Reach of Page posts | Weekly Paid Reach of Page posts | 28 Days Paid Reach of Page posts | Daily Viral Reach Of Page Posts | Weekly Viral Reach Of Page Posts | 28 Days Viral Reach Of Page Posts | Daily Total Impressions of your posts | Weekly Total Impressions of your posts | 28 Days Total Impressions of your posts | Daily Organic impressions of your posts | Weekly Organic impressions of your posts | 28 Days Organic impressions of your posts | Daily Paid impressions of your posts | Weekly Paid impressions of your posts | 28 Days Paid impressions of your posts | Daily Viral Impressions Of Your Posts | Weekly Viral Impressions Of Your Posts | 28 Days Viral Impressions Of Your Posts | Daily Total Consumers | Weekly Total Consumers | 28 Days Total Consumers | Daily Page Consumptions | Weekly Page Consumptions | 28 Days Page Consumptions | Daily Negative Feedback | Weekly Negative Feedback | 28 Days Negative Feedback | Daily Negative Feedback From Users | Weekly Negative Feedback From Users | 28 Days Negative Feedback From Users | Daily Total Check-Ins | Weekly Total Check-Ins | 28 Days Total Check-Ins | Daily Total Check-Ins | Weekly Total Check-Ins | 28 Days Total Check-Ins | Daily Total Check-Ins Using Mobile Devices | Weekly Total Check-Ins Using Mobile Devices | 28 Days Total Check-Ins Using Mobile Devices | Daily Total Check-Ins Using Mobile Devices | Weekly Total Check-Ins Using Mobile Devices | 28 Days Total Check-Ins Using Mobile Devices | Daily Total Organic Views | Weekly Total Organic Views | 28 Days Total Organic Views | Daily Total Promoted Views | Weekly Total Promoted Views | 28 Days Total Promoted Views | Daily Total Organic 30-Second Views | Weekly Total Organic 30-Second Views | 28 Days Total Organic 30-Second Views | Daily Paid 30-Second Views | Weekly Paid 30-Second Views | 28 Days Paid 30-Second Views | Daily Total Video Views | Weekly Total Video Views | 28 Days Total Video Views | Daily Total Auto-Played Views | Weekly Total Auto-Played Views | 28 Days Total Auto-Played Views | Daily Total Clicked Views | Weekly Total Clicked Views | 28 Days Total Clicked Views | Daily Video Repeats | Weekly Video Repeats | 28 Days Video Repeats | Daily Total Unique Video Views | Weekly Total Unique Video Views | 28 Days Total Unique Video Views | Daily Total 30-Second Views | Weekly Total 30-Second Views | 28 Days Total 30-Second Views | Daily Auto-Played 30-Second Views | Weekly Auto-Played 30-Second Views | 28 Days Auto-Played 30-Second Views | Daily Total Clicked 30-Second Views | Weekly Total Clicked 30-Second Views | 28 Days Total Clicked 30-Second Views | Daily Total 30-Second Repeats | Weekly Total 30-Second Repeats | 28 Days Total 30-Second Repeats | Daily Total Unique 30-Second Views | Weekly Total Unique 30-Second Views | 28 Days Total Unique 30-Second Views | Daily Total: total action count per Page | Weekly Total: total action count per Page | Daily Total get direction click count per Page | Weekly Total get direction click count per Page | Daily Total get direction click count per Page | Weekly Total get direction click count per Page | Daily Total phone calls click count per Page | Weekly Total phone calls click count per Page | Daily Total phone calls click count per Page | Weekly Total phone calls click count per Page | Daily Total website click count per Page | Weekly Total website click count per Page | Daily Total website click count per Page | Weekly Total website click count per Page |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ricardopoppi** [comment]
Dados sobre postagens específicas (post level):

Número de identificação da publicação | Link permanente | Publicar mensagem | Tipo | Países | Idiomas | Publicado | Direcionamento do público | Lifetime Post Total Reach | Lifetime Post organic reach | Lifetime Post Paid Reach | Lifetime Post Total Impressions | Lifetime Post Organic Impressions | Lifetime Post Paid Impressions | Lifetime Engaged Users | Lifetime Matched Audience Targeting Consumers on Post | Lifetime Matched Audience Targeting Consumptions on Post | Lifetime Negative Feedback from Users | Lifetime Negative Feedback | Lifetime Post Impressions by people who have liked your Page | Lifetime Post reach by people who like your Page | Lifetime Post Paid Impressions by people who have liked your Page | Lifetime Paid reach of a post by people who like your Page | Lifetime People who have liked your Page and engaged with your post | Lifetime Organic views to 95% | Lifetime Organic views to 95% | Lifetime Paid views to 95% | Lifetime Paid views to 95% | Lifetime Organic Video Views | Lifetime Organic Video Views | Lifetime Paid Video Views | Lifetime Paid Video Views | Lifetime Average time video viewed | Lifetime Video length
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ricardopoppi** [comment]
A princípio, na minha visão, seria mais útil integrar a infra de DS com os dados de (post level).

Exemplos dos xls gerados pelas duas exportações:
[Facebook Insights Data Export - Cidade Democrática - 2020-05-07.xlsx](https://github.com/cidadedemocratica/ej-server/files/4594052/Facebook.Insights.Data.Export.-.Cidade.Democratica.-.2020-05-07.xlsx)
[Facebook Insights Data Export (Post Level) - Cidade Democrática - 2020-05-07.xlsx](https://github.com/cidadedemocratica/ej-server/files/4594053/Facebook.Insights.Data.Export.Post.Level.-.Cidade.Democratica.-.2020-05-07.xlsx)

**Comment by davidCarlos** [comment]
@ricardopoppi isso aqui ainda tem alguma utilidade? Se não, pode fechar a issue.

**Comment by ricardopoppi** [comment]
sim, já obtivemos isso direto, fechando a issue
